anyproto/anytype-swift

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/New auth/PhraseTextView/PhraseTextValidator.swift
Anytype/Sources/PresentationLayer/New auth/PhraseTextView/PhraseTextView.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/Generated/FeatureFlags+Flags.swift

Validate typing and inserting recovery phrase - max 12 words + 8 characters per word, place it under the toggle.
Not so obvious in my opinion but we want to try how it will work.
https://github.com/anyproto/anytype-swift/assets/6065952/0b678fc5-7409-47fd-b1f3-809108e9449c

iOS-1523 Trim typed/inserted text in recovery phrase text view

---

Scripts/ruby/workers/download_file_worker.rb
Scripts/ruby/workers/remote_info_worker.rb

---
---
Github authentication token is no longer needed since anytype-heart repo went public. I removed the lines that are responsible for requesting auth so that the `make setup-middle` works without the `--token` argument. 
For now, there are still traces of the `token` variable left in the ruby script since i kept the changes to a minimal and it's easier to revert if needed in the future. But let me know if you'd prefer a comprehensive rewrite.
--
--

Remove github token for downloading middleware

---

Anytype/Sources/PresentationLayer/New auth/JoinFlow/CreatingSoulView/CreatingSoulView.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/CreatingSoulView/CreatingSoulViewModuleAssembly.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/JoinFlowCoordinator.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/JoinFlowModuleAssembly.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/JoinFlowOutput.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/JoinFlowView.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/JoinFlowViewModel.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/KeyPhraseView/KeyPhraseView.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/KeyPhraseView/KeyPhraseViewModuleAssembly.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/SoulView/SoulView.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/SoulView/SoulViewModuleAssembly.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/VoidView/VoidViewModel.swift

Move `JoinFlowState` creating to the `JoinFlowViewModel` to recreate every time we go to the join flow + 
Replace `ObservedObject` with `StateObject` on the join flow

iOS-1614 Update JoinFlowState creating logic

---

Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift

Remove sorting by name for options (it's actual for statuses and tags) to have the same behaviour like on desktop

iOS-1578 Remove redundant sorting for the options (tags / statuses)

---

Anytype/Sources/Models/Extensions/ObjectType+Extensions.swift
Anytype/Sources/PresentationLayer/Templates/Views/Selection/Dataview/DataViewTemplateSelectionInteractorProvider.swift
Anytype/Sources/PresentationLayer/Templates/Views/Selection/Objects/TemplatePreviewModel.swift
Anytype/Sources/PresentationLayer/Templates/Views/Selection/TemplatesSelectionViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorPageAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/ServiceLayer/Object/ObjectType/ObjectTypeProvider.swift
Anytype/Sources/ServiceLayer/Object/ObjectType/ObjectTypeProviderProtocol.swift
Anytype/Sources/ServiceLayer/Object/ObjectType/Subscription/ObjectTypeSubscriptionDataBuilder.swift
Modules/Services/Sources/Models/ObjectType.swift

1. Support object type default template if no activeview's template was selected
2. Support object type default templates changing via subscription to objectTypeProvider.syncPublisher
3. Add logic with `blank` to make difference with ""

iOS-1707 Support default type template if no activeview's template was selected

---

Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/Components/SpacePlusRow.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/Components/SpaceRowView.swift

Example - RED shadow
Bug
https://github.com/anyproto/anytype-swift/assets/2483784/1e87208d-b4f7-4c90-a665-6b33e58e96df
Fix
https://github.com/anyproto/anytype-swift/assets/2483784/f007ffe7-de2e-4b25-bba9-ed8a377641a1

IOS-1945 Space Switch | Fix shadow for long tap

---

Anytype/Sources/Models/Documents/Document/BaseDocument.swift
Anytype/Sources/ServiceLayer/DocumentsProvider/DocumentsProvider.swift

We should add it to BaseDocument subscriptions for changing type in document from Anytype Library. 
Otherwise it look like deleted

iOS-2113 Subscribe on objectType updates in BaseDocument

---

Scripts/middle-install.sh

Added error validation for middleware download for more user friendly setup. Based on my own experience.

IOS-2205 Add robust error message for make install

---

AnyTypeTests/Text/KeyboardActionHandlerTests.swift
Anytype/Sources/PresentationLayer/Common/UIKit/TextView/Models/CustomTextViewKeyboardAction.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/KeyboardActionHandler/KeyboardActionHandler.swift

Logic was changed, now we add new block above current block instead of split when set Enter in the beginning (`enterAtTheBegining`), so we don't need range and string

iOS-2376 Editor | Refactoring fixes | Remove redundant params

---

Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/FeaturedRelations/FeaturedRelationsBlockViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/TableOfContents/TableOfContentsView.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Code/CodeBlockViewModel.swift

⚠️ Warning
`Warning: applying updates in a non-thread confined manner is dangerous and can lead to deadlocks. Please always submit updates either always on the main queue or always off the main queue - view=<Anytype.EditorCollectionView: 0x12c046400; baseClass = UICollectionView; frame = (0 0; 430 932); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x600000caed90>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x600000288ec0>; contentOffset: {0, 0}; contentSize: {430, 623}; adjustedContentInset: {0, 0, 184, 0}; layout: <Anytype.EditorCollectionFlowLayout: 0x12652e590>; dataSource: <TtGC5UIKit34UICollectionViewDiffableDataSourceO7Anytype13EditorSectionOS1_10EditorItem: 0x60000000f3c0>>`
💥 Crash
`*** Terminating app due to uncaught exception …

iOS-2515 Fix collection view diffing warning and crash

---

Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics.swift

This events were sent only by iOS and they sometimes overestimate retention, Vadim asked to remove this events from the app

iOS-2383 Disable trackingSessionEvents

---

Anytype/Sources/Models/ObjectPermissions/ObjectPermissions.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Buildes/WidgetObjectListMenuBuilder.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/WidgetObjectListViewModel.swift

https://github.com/anyproto/anytype-swift/assets/2483784/e56c7b1d-df3d-4fc4-9d4b-1b76947a5d01

IOS-2492 Widget Object List | Support permissions in actions

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Flows/SpaceShareCoordinator/SpaceShareCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceShareCoordinator/SpaceShareCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceMoreInfo/SpaceMoreInfoView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift

https://github.com/anyproto/anytype-swift/assets/2483784/7d453059-135d-4121-b5d2-f17973f9773f

IOS-2533 Multiplayer | More info screen

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierExtensions.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipTierInfoView.swift
Modules/Services/Sources/Services/Membership/Model/MembershipTier.swift

Use tiers feature list from middleware api

IOS-2456 Membership | Use features from API

---

Modules/AnytypeCore/AnytypeCore/Utils/Publishers/PublishedDictionary.swift
Modules/AnytypeCore/AnytypeCore/Utils/Synchronized colections/SynchronizedDictionary.swift

Sometimes it crashes on the start in `publishAllValues`

iOS-2584 Fix PassthroughSubjectDictionary crash on the start

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/RelationsListView.swift

iOS-2596 Remove edit/+ buttons in Relations list when object is locked

---

Anytype.xcodeproj/project.pbxproj
Anytype.xcodeproj/xcshareddata/xcschemes/Anytype.xcscheme
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Resources/Strings/en.lproj/Localizable.stringsdict
Anytype/Sources/Helpers/Extensions/StringExtensions.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipPricingView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTeirView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierExtensions.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierPaymentTypeExtension.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetViewModel.swift
Anytype/Supporting files/LocalStoreKitConfiguration.storekit
Modules/AnytypeCore/AnytypeCore/Utils/AsyncHelpers.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift
Modules/Services/Sources/Services/Membership/Model/MembershipTier.swift
Modules/Services/Sources/Services/Membership/Model/MembershipTierPaymentType.swift

IOS-2594 Membership | Use price data from StoreKit and Middelware

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Auth/JoinFlow/KeyPhraseMoreInfoView/KeyPhraseMoreInfoView.swift
Anytype/Sources/PresentationLayer/Auth/JoinFlow/KeyPhraseView/KeyPhraseView.swift
Anytype/Sources/PresentationLayer/Auth/LoginFlow/LoginView.swift

iOS-2661 Update onboarding key screen

---

Anytype.xcodeproj/project.pbxproj
Anytype/Supporting files/Info.plist
fastlane/FastfileDeploy

If you build release and dev for simulator or device by cabel, difficult to understand where is which build. This change fixed it

IOS-2718 Core | Rename debug project

---

Anytype/Sources/Models/Documents/Events/EventsListener.swift
Modules/Services/Sources/Models/Block/IndentationBuilder.swift

Middleware uses div block for split a lot of child items. If block contains ~40 items, middleware will split one big block to two div blocks with ~20 child items. We did not support this case.
https://github.com/anyproto/anytype-swift/assets/2483784/e35ed9fb-1997-4638-9def-5c756d7ee1bc

IOS-2053 Editor | Fix numeric list

---

Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/Stylers/TextBlockLeadingView.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockContentView.swift

Toggle action in TextBlockLeadingStyle was not update during the reuse. Added block id for reuse comparation.

IOS-2785 Editor | Fix checkbox

---

Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareTip/SpaceShareTip.swift

Without text tip can't be shown

IOS-2907 SpaceShareTip | Fix show

---

Anytype/Sources/ServiceLayer/Auth/LoginStateService.swift

Desktop and Android apps are not waiting for the MembershipGetStatus to finish.
Because when you do it with noCache=true it can take a while if you have a bad internet connection

IOS-2958 Do not wait for membership subscription to start

---

Anytype/Sources/PresentationLayer/Auth/LoginFlow/LoginViewModel.swift
Modules/Services/Sources/Services/Auth/AuthMiddleService.swift
Modules/Services/Sources/Services/Auth/Errors/SelectAccountError.swift

It happens when we cancel selectAccount by tap back - should skip this error

iOS-3050 Handle accountSelect cancelation error

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/IconsGroupView.swift

iOS-3265 Version history | Update grouped icon + add counter

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Coordinator/VersionHistoryCoordinatorView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Coordinator/VersionHistoryCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Object/ObjectVersionData.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Object/ObjectVersionView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Object/ObjectVersionViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetFullHeader.swift

https://github.com/user-attachments/assets/6405043a-f830-4d5d-81ab-4808b89d8af4

iOS-3267 Version history | Impl version restoration

---

Anytype/Sources/Models/Documents/Events/MentionMarkupEventProvider.swift

This problem reproduced if text contains emoji + link to object. Emoji before the link. Emoji contains two or more utf-16 characters.
Example:
Text: 🦫 <ins>All</ins>
🦫 - 2 utf-16 characters
Middleware uses utf-16 for range. We are using string interpretation where 🦫 - 1 symbol. 
If we get `string.count` for exaple it will be 5, but for middleware is 6

IOS-1561 Editor | Fix range in mentions

---

Anytype/Sources/PresentationLayer/ObjectCreationSettings/SetObjectCreationSettingsCoordinator.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/TemplatesCoordinator.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModelConfiguration.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Empty/ObjectHeaderEmptyContentView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/HeaderBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeader.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeaderEmptyData.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/ObjectHeaderConstants.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Object/ObjectVersionView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Object/ObjectVersionViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetFullHeader.swift

https://github.com/user-attachments/assets/dba5aa51-7eff-4972-b76a-f8500c8e8a10

iOS-3276 Version history | Update empty header height

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchState.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchViewModel.swift
Anytype/Sources/ServiceLayer/Object/GlobalSearchSavedStates/GlobalSearchSavedStatesService.swift
Anytype/Sources/ServiceLayer/ServicesDI.swift

https://github.com/user-attachments/assets/2c10b94c-fecc-4a7f-864f-e1a990671753

iOS-3282 Global search | Save last search state for each space

---

Modules/Services/Sources/Services/SearchService/SearchHelper.swift

Change archive / hidden / deleted / hiddenDiscovery from  `.equal` -> `false` to `.notEqual` -> `true` because the last one exclude problem with nil values (this logic works on desktop and android)

iOS-3502 Update archive / hidden / deleted / hiddenDiscovery filters condition

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/EmptyStateView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Container/RelationListContainerView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/SearchView/SearchView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchView.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentView.swift
Anytype/Sources/PresentationLayer/Modules/GalleryInstallationPreview/GalleryInstallationPreviewView.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Bin/WidgetObjectListBinViewModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Chats/WidgetObjectListChatsViewModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Collections/WidgetObjectListCollectionsViewModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Common/Internal/WidgetObjectListInternalViewModelProtocol.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Common/WidgetObjectListView.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Common/WidgetObjectListViewModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Favorites/WidgetObjectListFavoritesViewModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Files/WidgetObjectListFilesViewModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Recent/WidgetObjectListRecentViewModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Sets/WidgetObjectListSetsViewModel.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift

Also add an option to EmptyView to create it without Image (for searches)

iOS-3536 Add empty state for Widget list screens

---

Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageBlocksStateManager.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandler.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandlerProtocol.swift
Modules/Services/Sources/Services/BlockService/BlockService.swift
Modules/Services/Sources/Services/BlockService/BlockServiceProtocol.swift

---
---
Moving several blocks to a new page does not always preserve the order.
The `EditorPageBlocksStateManager` iterates over all selected blocks and moves them one at a time (seemingly synchronously) via the `BlockActionHandler`. However, the action handler internally fires a `Task` to asynchronously move the block via the `BlockService`. Without any synchronization, it is undefined in which order the tasks will run, resulting in the elements being moved out of order.
Don't hide a task inside `BlockActionHandler.moveToPage(blockId:pageId)`, instead make it `async throws`, then await for each move to complete before iterating to the next block.
I marked the method as throws so errors are propagated up, but it gets ignored anyway in the enclosing task. I didn't notice error handling in …

fix: blocks moved to another object are out of order

---

Anytype/Sources/ApplicationLayer/GlobalEnv/AppInterfaceStyle.swift
Anytype/Sources/ApplicationLayer/GlobalEnv/KeyboardDismiss.swift
Anytype/Sources/ApplicationLayer/GlobalEnv/PresentedDismiss.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/AsyncStandardButtonGroup.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DragAndDrop/DragAndDropFrames.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DragAndDrop/DragAndDropModels.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/NavigationView/AnytypeNavigationAdditionalSafeArea.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/NavigationView/AnytypeNavigationItemData.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/Support/PageNavigation.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/BottomPanel/HomeBottomPanelStateEnvironment.swift
Anytype/Sources/PresentationLayer/Notifications/CommonViews/NotificationDismissEnvironment.swift

Before
```
struct KeyboardDismiss: EnvironmentKey {
static let defaultValue: () -> Void = {}
}
extension EnvironmentValues {
var keyboardDismiss: () -> Void {
get { self[KeyboardDismiss.self] }
set { self[KeyboardDismiss.self] = newValue }
}
}
```
After
```
extension EnvironmentValues {
@Entry var keyboardDismiss: () -> Void = {}
}
```

iOS-3708 Integrate @Entry macro

---

Anytype/Sources/FrameworkExtensions/Foundation/DateExtension.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DateCalendarView/DateCalendarView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/Date/SetFiltersDateRowView.swift

`0...3000` years range is available now on all platforms

iOS-3725 Date as an object | Add limited date range to all date pickers

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/View+DragIndicator.swift
Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Anytype/Sources/PresentationLayer/RelationValueFlow/RelationValueCoordinator/RelationValueCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/RelationValueFlow/RelationValueCoordinator/RelationValueProcessingService.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorViewModel.swift

Date module init with `date` now, not `objectId`
https://github.com/user-attachments/assets/72f749f4-37e3-4072-ab52-3f3d84fd3ee0

iOS-3764 Date as an object | Open date object on locked relations

---

Anytype/Sources/Models/Documents/Events/DocumentViewModelSetter.swift
Anytype/Sources/Models/Documents/Events/MentionMarkupEventProvider.swift
Anytype/Sources/Models/Documents/MentionTextUpdateHandler/MentionTextUpdateHandler.swift
Anytype/Sources/ServiceLayer/ServicesDI.swift
Anytype/Sources/ServiceLayer/Subscriptions/Tree/TreeSubscriptionDataBuilder.swift

Just move logic from `MentionMarkupEventProvider` to `MentionTextUpdateHandler` and call it in `DocumentViewModelSetter` to update any mention title on document set (for date as well too)

iOS-3827 Date as an object | Update mentions texts if needed

---

Anytype/Sources/PresentationLayer/Search screen/View/LegacySearchView.swift

Before
https://github.com/user-attachments/assets/07a8a037-1d3e-4796-9035-84678c868c7b
After
https://github.com/user-attachments/assets/61f30c8a-25b4-4914-b70f-ae71afdccf83

iOS-3929 Avoid accident tapping on row when scrolling in LegacySearch

---

Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift

We don't need to close object after turning into collection

iOS-3877 Basic quality | Fix turn into collection

---

Anytype/Sources/PresentationLayer/Flows/EditorFlow/EditorCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/AllObject/BookmarksCompactListWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/AllObject/BookmarksListWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/Models/AllObjectWidgetType.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/AllContent/WidgetObjectListBookmarksView.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift

https://github.com/user-attachments/assets/294cd9bd-dd10-4bc7-bde0-c079741cd26e

iOS-4012 Widgets | support bookmarks widget

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Flows/SpaceHub/Support/NavigationHeader.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/Legacy/SpaceSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/NewSpaceSettingsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/NewSpaceSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsModuleOutput.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Views/SpaceDetails/SpaceDetailsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Views/SpaceDetails/SpaceDetailsViewModel.swift
Modules/Services/Sources/Services/Workspace/WorkspaceSetDetails.swift

https://github.com/user-attachments/assets/f2237cfe-4953-4aff-b209-69b2c7dfdbed

Ios-4104 New settings | 1st iteration of space edit screen

---

Anytype/Sources/Models/Documents/Document/BaseDocument.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/Views/ObjectsList/ObjectTypeObjectsListViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/Builders/SetPermissionsBuilder.swift

Now we use relations from target object id for templates. Before we were using relations from Template type
https://github.com/user-attachments/assets/1a2a645e-3e96-44ad-8c61-8a87e775bf5d

Ios-4125 Primitives | Build relations for templates based on target object id

---

Anytype/Sources/Analytics/AnalyticsConstants.swift
Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
Anytype/Sources/ApplicationLayer/AppSceneHandler/AppSceneUrlHandlerModifier.swift
Anytype/Sources/ApplicationLayer/AppSceneHandler/AppSceneUrlHandlerModifierModel.swift
Anytype/Sources/PresentationLayer/Auth/Auth/AuthViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/ServiceLayer/AppActions/AppAction.swift
Modules/DeepLinks/Sources/DeepLinks/DeepLinkSource.swift

only for external openings (`object.any.coop` site for example)

iOS-4247 Add analytics for open object by link

---

AnyTypeTests/Markdown/Mocks/MockPropertiesService.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/PropertyDetailsViews/Date/PropertyCalendarViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/PropertyDetailsViews/PropertyOptionSettings/PropertyOptionSettingsViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/PropertyDetailsViews/PropertySelectedOptions/PropertySelectedOptionsModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/PropertyDetailsViews/Text/TextPropertyDetailsService/TextPropertyEditingService.swift
Anytype/Sources/PresentationLayer/PropertyValueFlow/PropertyValueCoordinator/PropertyValueProcessingService.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/PropertiesSearchViewModel/PropertiesInteractor.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSettingsPrimitivesConflictManager.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Properties/Views/ObjectFieldsView/ObjectPropertiesViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Properties/Views/TypePropertiesView/Model/TypePropertiesMoveHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Properties/Views/TypePropertiesView/TypePropertiesViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/CreateObject/CreateObjectViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/PropertyCreationViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetPropertiesViewModel.swift
Anytype/Sources/ServiceLayer/Extensions/PropertiesServiceProtocolExtensions.swift
Modules/Services/Sources/Services/Properties/PropertiesService.swift
Modules/Services/Sources/Services/Properties/PropertiesServiceProtocol.swift

- Renamed all method names in PropertiesServiceProtocol from "Relation" to "Property" terminology
- Updated all method implementations and call sites throughout the codebase
- Fixed compilation errors and verified build passes successfully

IOS-4660 Rename PropertiesService methods from Relation to Property terminology

---

Anytype.xcodeproj/project.pbxproj

- Converted all test groups from PBXGroup to PBXFileSystemSynchronizedRootGroup 
- Removed individual file references for test files and mocks to use file system synchronization
- This completes the migration allowing Xcode to automatically

IOS-4750 Migrate test groups to file system synchronized folders

---

Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsView.swift

- Changed template count threshold from >2 to >1 for showing edit button
- Now the edit button appears when there are one or more templates

IOS-4475 Show edit button when there is 1 template

---

Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift

- Added objectType to excluded layouts in link to object search functionality
- This prevents object types from appearing in the search results when linking objects

IOS-4550 Filter object types from link to object search

---

.claude/commands/cpp.md
.claude/settings.json
CLAUDE.md

- Moved read-only bash commands from local settings to public settings for everyone to access by default
- Cleaned up local settings to only include write/modify commands that should remain local

IOS-4689 Move read-only commands to public settings

---

Modules/Loc/Sources/Loc/Generated/Strings.swift

- Updated "Vault and access" to "Vault and key" in app settings
- Updated "Access" section header to "Key"
- Regenerated localization constants
Fixes the localization strings as requested in the Linear task.

IOS-4789 Rename 'access' to 'key' in settings

---

Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Modules/Services/Sources/Models/Block/BlockContainer/InfoContainer+ModelHelpers.swift
Modules/Services/Sources/Models/Block/BlockContainer/Models+Events/BlockRelation+Handle.swift
Modules/Services/Sources/Models/Block/BlockContent/BlockContent.swift
Modules/Services/Sources/Models/Block/BlockContent/Content/BlockProperty.swift
Modules/Services/Sources/Models/Block/BlockConverters/BlockPropertyConverter.swift
Modules/Services/Sources/Services/PropertyListWithValue/PropertyListWithValueService.swift
Modules/Services/Sources/ServicesDI.swift

- Rename RelationListWithValueService to PropertyListWithValueService
- Rename BlockRelation to BlockProperty
- Rename BlockRelationConverter to BlockPropertyConverter  
- Update all references throughout codebase

IOS-4660 Rename relation to property in block models and services

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift
Anytype/Sources/PreviewMocks/Mocks/WorkspacesStorageMock.swift
Anytype/Sources/ServiceLayer/SpaceStorage/Models/SpaceView.swift
Anytype/Sources/ServiceLayer/SpaceStorage/Models/SpaceViewMock.swift
Anytype/Sources/ServiceLayer/SpaceStorage/WorkspacesSubscriptionBuilder.swift

- Updated SpaceView model to use spaceOrder string instead of isPinned boolean
- Refactored complex sorting logic in SpaceHubViewModel into a clean, readable method
- Improved code maintainability with pattern matching and clear separation of concerns

IOS-4818 Refactor SpaceHub sorting logic

---

Anytype/Sources/PresentationLayer/Flows/SpaceHub/QRCodeScannerViewModifier.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift

- Extracted QR code scanner logic from SpaceHubCoordinatorViewModel into a reusable QRCodeScannerViewModifier
- Added camera permission validation before scanning
- Created extension method .qrCodeScanner(shouldScan:) for easy integration in any view

IOS-4784 Refactor QR code scanner into reusable view modifier

---

Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/Block/TextBlock/SimpleTablesTextBlockActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageBlocksStateManager.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandler.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandlerProtocol.swift
AnytypeTests/Markdown/Mocks/BlockActionHandlerMock.swift

- Remove spaceId parameter from BlockActionHandlerProtocol methods (createEmptyBlock, addBlock, createPage, createTable)
- Update implementations to use document.spaceId internally instead of accepting spaceId as parameter
- Update all call sites across the codebase to remove spaceId argument
- Fix document scanner integration in slash menu to use proper method call
- Cleaner API that doesn't require callers to pass spaceId
- Consistent with other methods that use document.spaceId internally
- Reduces parameter count and potential for passing incorrect spaceId

IOS-4778 Remove spaceId from BlockActionHandlerProtocol methods

---

.claude/settings.json

- Moved read-only Claude permissions from local to global settings for team consistency
- Added gh pr list/diff, git fetch, od, awk, git stash show, and figma tools to global permissions
- Ensures all team members have the same Claude Code capabilities for read-only operations

IOS-4861 Move read-only Claude permissions to global settings

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/Subviews/SpaceCardLabel.swift
Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Pin.imageset/Contents.json

- Add active color styling to pinned space icon in SpaceCardLabel
- Configure pin icon as template rendering for proper color theming
-

IOS-4875 Add active color styling to pinned space icon

---

Anytype/Sources/Analytics/AnalyticsConstants.swift
Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelActions.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandler.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandlerProtocol.swift
AnytypeTests/Markdown/Mocks/BlockActionHandlerMock.swift
CLAUDE.md

- Add UploadMediaRoute enum with camera, scan, filePicker routes for detailed analytics tracking
- Update logUploadMedia function to accept route parameter  
- Add route context to all upload function calls in BlockActionHandler
- Update protocols and test mocks to match new signatures

IOS-4861 Analytics | Add route tracking to upload media analytics

---

Modules/Services/Sources/Services/Publishing/Models/PublishingModels.swift
Modules/Services/Sources/Services/Publishing/PublishingService.swift
Modules/Services/Sources/ServicesDI.swift

- Added PublishingService with methods for creating, removing, listing, resolving, and getting status of published objects
- Created PublishingModels with PublishState, PublishStatus, and PublishingServiceError types
- Added PublishingService to dependency injection container

IOS-4898 Add PublishingService for managing object publishing

---

Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageTextBuilder.swift

There is no verification on the middle. 
Some client is incorrect working with mentions. There's no point in sending an assertion, there's nothing we can do about it.
I asked the middle to add a check on their side.

IOS-4932 Chat | MessageTextBuilder | remove assert

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/PropertyDetailsViews/Text/Actions/TextPropertyCopyActionViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/LinkToObject/LinkToObjectSearchViewModel.swift
Anytype/Sources/PresentationLayer/Modules/PublishToWeb/View/PublishingPreview.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceProfile/SpaceProfileView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceProfile/SpaceProfileViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionRow.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

- Updated space sharing section design to show 3 action buttons instead of 2
- Added new "Copy link" functionality alongside existing "Share link" and "QR code" options
- Applied consistent styling with rounded icon containers and improved spacing
- Updated both SpaceSettingsView and SpaceProfileView for design consistency
Icon for sharing will be updated when design team will update design system
https://github.com/user-attachments/assets/94a64864-9153-448a-a570-a9be0d7b2958

IOS-4936 Design update of space sharing buttons

---

Anytype/Sources/Analytics/AnalyticsConstants.swift
Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
Anytype/Sources/PresentationLayer/Modules/PublishToWeb/PublishToWebInternalView.swift
Anytype/Sources/PresentationLayer/Modules/PublishToWeb/PublishToWebInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/PublishToWeb/View/PublishingPreview.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsViewModel.swift

- Implemented all 12 analytics events from IOS-4900 for publish to web feature
- Track objectType for all events and differentiate create/update actions  
- Added route tracking for copy URL and open page actions

IOS-4900 Add analytics events for publishing to web

---

.github/workflows/branch_build.yaml
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageController.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

We made cell.contentConfiguration two times - when create cell and during registration, fix that - configure cell only one time

iOS-5040 Attempt to fix collection view reuse crash in Editor

---

Anytype/Sources/PresentationLayer/Settings/Settings/Sections/SettingsSectionItemView.swift

Current problem to fix on global level: Text + anytypeStyle do not account for line height 
before
after

IOS-5091 Fix join button text not centering

---

Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

- Removed hideWebPayments feature flag definition
- Updated membership views to permanently hide web-based payment options
- Cleaned up unused code (contactUs method, moreInfoButton method, unused imports)

IOS-4807 Remove hideWebPayments feature flag and keep TRUE branch logic
