.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.github/workflows/cla.yml
README.md
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md
docs/SECURITY.md

---
---
Make contributing possible
https://linear.app/anytype/issue/OPEN-26/prepare-anytype-swift-for-external-contributions
https://github.com/orgs/anyproto/discussions/23
https://github.com/orgs/anyproto/discussions/9

Make contributing possible

---

Anytype/Sources/PresentationLayer/Templates/TemplateSelectionCoordinator.swift
Anytype/Sources/PresentationLayer/Templates/Views/Selection/Dataview/DataViewTemplateSelectionInteractorProvider.swift
Anytype/Sources/PresentationLayer/Templates/Views/Selection/Dataview/MockTemplateSelectionInteractorProvider.swift
Anytype/Sources/PresentationLayer/Templates/Views/Selection/EditableView.swift
Anytype/Sources/PresentationLayer/Templates/Views/Selection/Objects/TemplatePreview.swift
Anytype/Sources/PresentationLayer/Templates/Views/Selection/Objects/TemplatePreviewModel.swift
Anytype/Sources/PresentationLayer/Templates/Views/Selection/TemplateOptionAction.swift
Anytype/Sources/PresentationLayer/Templates/Views/Selection/TemplatesSelectionView.swift
Anytype/Sources/PresentationLayer/Templates/Views/Selection/TemplatesSelectionViewModel.swift
Anytype/Sources/ServiceLayer/Subscriptions/TemplatesSubscriptionService.swift

IOS-1587 Template selection. Change alert type.

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/Factories/AlertsFactory.swift
Anytype/Sources/PresentationLayer/New auth/LoginFlow/LoginFlowCoordinator.swift
Anytype/Sources/PresentationLayer/New auth/LoginFlow/LoginFlowOutput.swift
Anytype/Sources/PresentationLayer/New auth/LoginFlow/LoginView.swift
Anytype/Sources/PresentationLayer/New auth/LoginFlow/LoginViewModel.swift

iOS-1581 Update qr camera alert text and style

---

Anytype/Sources/CoreLayer/Sentry/SentryConfiguration.swift

Example issue
https://sentry.anytype.io/organizations/anytype/issues/17916/?environment=development&project=6&referrer=project-issue-stream

IOS-1593 Sentry | Add middleware version

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/DotsView/DotView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DotsView/DotsView.swift

https://github.com/anyproto/anytype-swift/assets/2483784/3866264f-f80f-479b-949b-06237c054751

IOS-1185 DesignSystem | Update button dots animation

---

Anytype/Sources/FrameworkExtensions/Foundation/NSAttributedString+Convenience.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/KeyPhraseView/KeyPhraseView.swift
Anytype/Sources/PresentationLayer/New auth/LoginFlow/LoginView.swift
Anytype/Sources/PresentationLayer/New auth/PhraseTextView/PhraseTextView.swift
Anytype/Sources/PresentationLayer/New auth/PhraseTextView/UIPhraseTextView.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/Generated/FeatureFlags+Flags.swift

Unfortunately I didn’t have time to do it with TextKit, so it’s a simple version for now, hope to remake it in the future because this version has some hacks and limitations
https://github.com/anyproto/anytype-swift/assets/6065952/a2b7198a-5f81-4c1c-9aec-671ca00a9b89

iOS-1202 Colourful recovery phrase

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Analytics/AnalyticsConstants.swift
Anytype/Sources/Analytics/Converters/ObjectType+Analytics.swift
Anytype/Sources/PresentationLayer/Assemblies/WidgetsSubmoduleDI.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsRegistry.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Models/WidgetSource.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/CompactList/RecentCompactListWidgetModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/List/RecentListWidgetModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/Models/RecentWidgetType.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/RecentWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Tree/Specific/RecentTreeWidgetModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Internal/WidgetObjectListRecentViewModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/WidgetObjectListModuleAssembly.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/WidgetSourceSearchViewModel/WidgetSourceSearchInteractor.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/WidgetSourceSearchViewModel/WidgetSourceSearchViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorPageAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
Anytype/Sources/ServiceLayer/Subscriptions/RecentSubscriptionService.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/Generated/FeatureFlags+Flags.swift
Modules/Services/Sources/Models/Details/Entities/AnytypeWidgetId.swift

https://github.com/anyproto/anytype-swift/assets/2483784/ae1a6aa2-85c7-451c-896f-269b2b9c7f2c

IOS-1608 Widget | New recent edited widget

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Assemblies/WidgetsSubmoduleDI.swift
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsRegistry.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Submodules/HomeBottomPanel/HomeBottomPanelModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Submodules/HomeBottomPanel/HomeBottomPanelViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/CommonWidgetModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Space/Models/SpaceAccessibility+Localization.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Space/SpaceWidgetModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Space/SpaceWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Space/SpaceWidgetViewModel.swift
Anytype/Sources/ServiceLayer/Subscriptions/BundledRelationKey+CommonKeys.swift
Modules/Services/Sources/Models/Details/Entities/SpaceAccessibility.swift
Modules/Services/Sources/Models/Relations/Provider/Bundled/Helpers/BundledRelationValueProvider+CustomFields.swift

https://github.com/anyproto/anytype-swift/assets/2483784/53ecfeba-6ec9-4876-b718-e284be77ac9f

IOS-1486 Multi Space | Add space widget (to space branch)

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Assemblies/ModulesDI.swift
Anytype/Sources/PresentationLayer/Assemblies/ModulesDIProtocol.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorAssembly.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/RemoteStorage/RemoteStorageModuleAssembly.swift
Anytype/Sources/PresentationLayer/SpaceSettings/RemoteStorage/RemoteStorageModuleOutput.swift
Anytype/Sources/PresentationLayer/SpaceSettings/RemoteStorage/RemoteStorageView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/RemoteStorage/RemoteStorageViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsModuleOutput.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift

https://github.com/anyproto/anytype-swift/assets/2483784/e95e4b2c-481f-40a2-b231-e3705adf4077

iOS-1633 Remote storage screen (to space branch)

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchViewModel.swift
Anytype/Sources/PresentationLayer/Settings/Account/SettingsAccountView.swift
Anytype/Sources/PresentationLayer/Settings/FileStorage/FileStorageView.swift
Anytype/Sources/PresentationLayer/Settings/Settings/SettingsView.swift
Anytype/Sources/PresentationLayer/Settings/Settings/SettingsViewModel.swift

https://github.com/anyproto/anytype-swift/assets/2483784/d1ab3870-e2f6-4e67-9081-fa13539428e1

iOS-1635 Update global settings (to space branch)

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Assemblies/ModulesDI.swift
Anytype/Sources/PresentationLayer/Assemblies/ModulesDIProtocol.swift
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorAssembly.swift
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/Components/SpaceRowView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Views/SpaceTypeView.swift
Modules/Services/Sources/Services/Workspace/WorkspaceService.swift

https://github.com/anyproto/anytype-swift/assets/2483784/b872b812-f895-46df-8969-fecf89159d88

iOS-1610 Create space screen (to space branch)

---

Anytype/Sources/FrameworkExtensions/SwiftUI/VerticalScrollViewWithOverlayHeader.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchView.swift

Uploading Simulator Screen Recording - iPhone 14 Pro - 2 - 2023-08-14 at 18.09.34.mp4…

iOS-1621 Space Switch Screen | shadow for scrolling (to space branch)

---

Anytype/Sources/Models/Documents/Document/BaseDocumentProtocol.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/GenericIconPickerViewModel/TextIconPickerViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/ObjectBasicIconPicker.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/ObjectIconPicker.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/ObjectIconPickerViewModel.swift

Added document state handling to wait initial data.

IOS-1672 Object Icon picker | Fix when document wasn't receive initial state

---

Anytype.xcodeproj/project.pbxproj
Anytype.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Anytype/Sources/ApplicationLayer/AppConfigurators/AppConfigurator.swift
Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/AnalyticsConfigurator.swift
Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/NonFatalAlertConfigurator/NonFatalAlertConfigurator.swift
Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/NonFatalAlertConfigurator/NonFatalLoggerHandler.swift
Anytype/Sources/CoreLayer/MiddlewareHandler/InvocationMesagesHandler.swift
Anytype/Sources/CoreLayer/Sentry/SentryConfiguration.swift
Anytype/Sources/CoreLayer/Sentry/SentryNonFatalLogger.swift
Anytype/Sources/Helpers/SwiftEntryKit+DebugError.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/Generated/FeatureFlags+Flags.swift
Modules/Logger/Package.swift
Modules/Logger/Sources/Logger/Assertation/AssertionLogger.swift
Modules/ProtobufMessages/Sources/Invocation.swift

IOS-1682 Logs | Add error alert and split request and response

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/IconView.swift

https://github.com/anyproto/anytype-swift/assets/2483784/bf4031e9-48e9-4cab-83cb-407e5d9040c9

IOS-978 IconView | Fix animation for login screen

---

Anytype.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Anytype/Sources/Models/Mention/MentionObject.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionViewController/MentionsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Search/EditorSearchCell.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Search/EditorSearchCellData.swift

IOS-960 Object Icon | Delete icon from mention search

---

Anytype/Sources/CoreLayer/NetwrokLayer/Kingfisher+Async.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/IconView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Painters/IconMaker.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Painters/IconPainter.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/Support/BlockLinkState+Icon.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Subscriptions/SetSubscriptionDataBuilder.swift

- Fix show gradient icon in sets and collections
- Fix draw on main thread
- Fix kingfisher when we download the same image multiple times

IOS-1663 ObjectIcon | fixes

---

Anytype/Sources/PresentationLayer/Templates/Views/Selection/Dataview/DataViewTemplateSelectionInteractorProvider.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorPageAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsViewModel.swift
Anytype/Sources/ServiceLayer/Object/Templates/TemplatesInteractor.swift
Modules/Services/Sources/Models/Block/BlockContent/Content/DataView/DataviewView.swift

https://github.com/anyproto/anytype-swift/assets/6065952/9bebcd41-22ba-43fa-a806-c1664a9fb187

iOS-1707 Support templates for default object + set Page if default object wasn't set

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Resources/SystemColors.xcassets/Auth/body.colorset/Contents.json
Anytype/Sources/Analytics/AnalyticsConstants.swift
Anytype/Sources/Design system/Fonts/AnytypeFont.swift
Anytype/Sources/Design system/Fonts/AnytypeFontConfig.swift
Anytype/Sources/PresentationLayer/New auth/Auth/AuthView.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/CreatingSoulView/CreatingSoulView.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/KeyPhraseMoreInfoView/KeyPhraseMoreInfoView.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/KeyPhraseView/KeyPhraseView.swift
Anytype/Sources/PresentationLayer/New auth/JoinFlow/KeyPhraseView/KeyPhraseViewModel.swift

https://github.com/anyproto/anytype-swift/assets/6065952/5f3fd2d7-2097-4b6a-90dc-14ebb3998f4e

iOS-1717 Update login texts and design

---

Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorView.swift

https://github.com/anyproto/anytype-swift/assets/2483784/57cf0fb3-e09b-42eb-8e91-43bb0b8c5767

iOS-1721 Switch space | Add background shadow (to space branch)

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Templates/Views/Selection/Dataview/DataViewTemplateSelectionInteractorProvider.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/MockSetDocument.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocument.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocumentProtocol.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SetViewSettings/SetViewSettingsCoordinatorView/SetViewSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SetViewSettings/SetViewSettingsList/SetViewSettings.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SetViewSettings/SetViewSettingsList/SetViewSettingsList.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SetViewSettings/SetViewSettingsList/SetViewSettingsListModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SetViewSettings/SetViewSettingsList/SetViewSettingsListModuleAssembly.swift
Anytype/Sources/ServiceLayer/Object/Templates/TemplatesInteractor.swift

iOS-1644 Add default type / default template to settings v1 (not editable)

---

AnytypeShareExtension/Info.plist

IOS-1741 Info plist type change

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/IconView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Painters/IconMaker.swift

- Fix swift diff
- Add load from cache without placeholder

iOS-1740 IconView | fix problem with displaying checkboxes in the view grid

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/CodeLanguage/CodeLanguageLegacyListViewController.swift
Anytype/Sources/PresentationLayer/Modules/CodeLanguage/CodeLanguageLegacyListViewModel.swift
Anytype/Sources/PresentationLayer/Modules/CodeLanguage/CodeLanguageListView.swift
Anytype/Sources/PresentationLayer/Modules/CodeLanguage/CodeLanguageListViewModel.swift
Anytype/Sources/PresentationLayer/Modules/CodeLanguage/CodeLanguageModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/CodeLanguage/CodeLanguageRowModel.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Code/CodeBlockView.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Code/Support/CodeLanguage.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouterProtocol.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/Generated/FeatureFlags+Flags.swift

- Add languages
- Update design
- Add titles

iOS-987 Code Language List | Redesign & add languages

---

Anytype/Resources/Strings/zh-Hans.lproj/InfoPlist.strings

Create InfoPlist.strings | Add Chinese Simplified translations

---

Anytype/Resources/Strings/zh-Hans.lproj/Localizable.strings

---
---
I have read the CLA Document and I hereby sign the CLA

Create Localizable.strings | Add Chinese Simplified languages

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Assemblies/ModulesDI.swift
Anytype/Sources/PresentationLayer/Assemblies/ModulesDIProtocol.swift
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorAssembly.swift
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Submodules/HomeBottomPanel/HomeBottomPanelModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Submodules/HomeBottomPanel/HomeBottomPanelView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Submodules/HomeBottomPanel/HomeBottomPanelViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/Assembly/ObjectTypeSearchModuleAssembly.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/ObjectTypesSearchViewModel/ObjectTypesSearchViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/View/NewSearchView.swift
Anytype/Sources/PresentationLayer/Search screen/ViewModel/NewSearchViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorBrowserAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorBrowser/EditorBrowserController.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorBrowser/EditorBrowserCoordinator.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorBrowser/View/EditorBottomNavigationView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorBrowser/View/EditorBrowserButton.swift
Anytype/Sources/ServiceLayer/Dashboard/DashboardService.swift
Anytype/Sources/ServiceLayer/Dashboard/DashboardServiceProtocol.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/Generated/FeatureFlags+Flags.swift

https://github.com/anyproto/anytype-swift/assets/2483784/788e5a99-1a9f-4719-97c1-8ab023f05de4

iOS-1796 ObjectCreate | Select object type by long tap

---

Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Editing/TemplateEditingViewController.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/ChangeTypeAccessoryView/ChangeTypeAccessoryView.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/CursorModeView/CursorModeAccessoryView.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/MarkupModeView/MarkupAccessoryView.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionView.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/SlashMenuView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorBrowser/EditorBrowserController.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageController.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/Generated/FeatureFlags+Flags.swift

https://github.com/anyproto/anytype-swift/assets/2483784/32472079-5452-484e-903b-3de464c96469

IOS-1751 iPad | Increase width

---

docs/CONTRIBUTING.md

---
---
Added a subheading for translations in the contributing guidelines which redirects to the Crowdin page.

Add Translations to Contributing.md

---

Anytype/Sources/Analytics/AnalyticsConstants.swift
Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/SetObjectCreationSettingsCoordinator.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsViewModel.swift
Anytype/Sources/ServiceLayer/Object/ObjectType/ObjectTypeProvider.swift

Add analytics to the set view settings then default type was changed

iOS-1768 Add route to the logDefaultObjectTypeChange

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/ServerConfiguration.swift
Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinator.swift
Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinatorAssembly.swift
Anytype/Sources/ApplicationLayer/AppCoordinator/WindowManager.swift
Anytype/Sources/PresentationLayer/Assemblies/CoordinatorsDI.swift
Anytype/Sources/PresentationLayer/Assemblies/CoordinatorsDIProtocol.swift
Anytype/Sources/PresentationLayer/Flows/InitialCoordinator/InitialCoordinatorAssembly.swift
Anytype/Sources/PresentationLayer/Flows/InitialCoordinator/InitialCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/InitialCoordinator/InitialCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/Alerts/DashboardLogoutAlert/DashboardLogoutAlertModel.swift
Anytype/Sources/Utilities/UserDefaults/UserDefaultsConfig.swift

https://github.com/anyproto/anytype-swift/assets/2483784/30605ffa-aa5f-4d13-893a-2763d86b1f67

IOS-1861 Core | Add switch to staging

---

docs/Setup_For_Middleware.md

Fix broken link

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Models/Extensions/DataviewType+Extensions.swift
Modules/Services/Sources/Models/Block/BlockContent/Content/DataView/DataviewViewType.swift

https://github.com/anyproto/anytype-swift/assets/6065952/2e651a0b-7203-4c8e-a913-e53a749049c3

iOS-1904 Fallback for Calendar view (the same as for Kanban)

---

Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/AccessoryViewBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/ChangeTypeAccessoryView/ChangeTypeAccessoryViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorPageAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandler.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandlerProtocol.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionService/BlockActionService.swift
AnytypeTests/Markdown/Mocks/BlockActionHandlerMock.swift

and fix analytics
https://github.com/anyproto/anytype-swift/assets/6065952/5907d0c9-0db2-4554-a22c-2967a7abd596

iOS-1907 Apply default template for type change if templates picker available

---

Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Picker/TemplatePickerView.swift

iOS-1800 Fix blank template design

---

Anytype/Sources/PresentationLayer/ToastPresenter/ToastPresenter.swift

- Fix when we open multiple toasts
- Fix status bar color

IOS-1902 Toast | Show fixes

---

Anytype/Sources/ServiceLayer/Object/Search/Common/SearchHelper.swift
Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift
Anytype/Sources/ServiceLayer/Subscriptions/RecentSubscriptionService.swift

If you know more places where it should be - please let me know

iOS-1931 Filter templates from global search and recently widgets

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Utils/AlertsFactory+ObjectOpen.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouterProtocol.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetRouter.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Modules/Services/Sources/Services/BlockActionsServiceSingle/BlockActionsServiceSingle.swift
Modules/Services/Sources/Services/BlockActionsServiceSingle/ObjectOpenError.swift

iOS-1924 Editor & Set | Object Open  - add error alert

---

Anytype/Sources/PresentationLayer/ObjectCreationSettings/TemplatesCoordinator.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorPageAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModelConfiguration.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetRouter.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift

It works with flags, we don't need to have another conditions

iOS-1920 Remove redundant condition `shouldShowTemplateSelection`

---

Anytype/Sources/PresentationLayer/ObjectCreationSettings/SetObjectCreationSettingsCoordinator.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Editing/TemplateEditingViewController.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorPageAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift

https://github.com/anyproto/anytype-swift/assets/6065952/23d49538-8f4f-435d-b26c-012728e79904

iOS-1940 Remove Select template button when creating + add toast

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Common/ListWidgetViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Models/DataviewView+View.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/ViewPicker/SetViewPickerViewModel.swift

https://github.com/anyproto/anytype-swift/assets/2483784/ba1ff0f0-916b-457e-a1e8-867227aa72f4

IOS-1725 Widgets | Hide tabs for one view in set & fix untitle name

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift

Will be remake from the middle side in the future
https://linear.app/anytype/issue/GO-2360/add-typechange-restriction-to-the-templates-objects

iOS-1971 Disable type change for Templates

---

Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorAssembly.swift
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorPageAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorBrowser/EditorBrowserCoordinator.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
Anytype/Sources/ServiceLayer/Object/Search/Common/SearchHelper.swift
Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift
Anytype/Sources/ServiceLayer/ServiceLocator.swift
Modules/Services/Sources/Models/Account/AccountInfo.swift

https://github.com/anyproto/anytype-swift/assets/2483784/c1ea5b0c-f2e6-4899-9c13-82e3ea0b2009

iOS-1998 Search | Add profile from system space

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Models/WidgetSource.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectAction.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViews/ObjectActionRow.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViews/ObjectActionsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingModuleAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsViewModel.swift
Modules/ProtobufMessages/Sources/DebugHelper.swift
Modules/ProtobufMessages/Sources/Invocation.swift
Modules/Services/Sources/Models/WidgetPosition.swift

Dashboard icon changed in navigation [PR](https://github.com/anyproto/anytype-swift/pull/555)
https://github.com/anyproto/anytype-swift/assets/2483784/801d3505-5f9b-4d37-a08e-307ed2b9facb

IOS-2013 Editor | Add create widget action

---

Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/CreateObject/CreateObjectView.swift

iOS-2039 Blue done button on object create from Sets/Collections

---

Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/ChangeTypeAccessoryView/ChangeTypeAccessoryViewModel.swift

It should fix at least this 3 crashes
https://sentry.anytype.io/organizations/anytype/issues/26930/?project=6&referrer=project-issue-stream
https://sentry.anytype.io/organizations/anytype/issues/26841/?project=6&referrer=project-issue-stream
https://sentry.anytype.io/organizations/anytype/issues/27957/?project=6&referrer=project-issue-stream

iOS-2080 Fix ChangeTypeAccessoryViewModel crash

---

Anytype/Sources/Models/Documents/Parsers/MiddlewareString.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Creation/SetObjectCreationCoordinator.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Creation/SetObjectCreationHelper.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/CreateObject/CreateObjectModuleAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/CreateObject/CreateObjectViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/CreateObject/CreateObjectViewModelProtocol.swift
Anytype/Sources/ServiceLayer/ServiceLocator.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Models/ObjectType.swift

https://github.com/anyproto/anytype-swift/assets/6065952/7b4c4809-6126-47e2-8d11-5e4c7ac6551c

iOS-2078 Place text into the first text block in Note when creating from Set/Collection/Widget

---

Anytype.xcodeproj/project.pbxproj
Anytype/Supporting files/Info.plist
AnytypeTests/Info.plist

Update dev version

---

Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelView.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

https://github.com/anyproto/anytype-swift/assets/6065952/d4858bda-7f1a-430d-b209-87e74516cf3b

iOS-2087 Make back button on bottom navigation always back

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift

Restriction was added on the middle side

iOS-1976 Remove manual type change filter from Template object

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/TextEditor/Views/Alerts/DocumentCommonOpenErrorView.swift

iOS-2087 Change common error text

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/IconViewUIKit.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/BlockLinkCardView.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/BlockTextLinkView.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/Support/BlockLinkState+Icon.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/Support/BlockLinkState+Text.swift

https://github.com/anyproto/anytype-swift/assets/2483784/499515cc-c2ef-4b76-beeb-23420b88c4f5

IOS-1802 Icon | Fix dark mode in block text/card

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Painters/Common/Container/SquareIconPainter.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/Components/SpaceRowView.swift

https://github.com/anyproto/anytype-swift/assets/2483784/c8dc72f0-031b-41fa-bf71-83467f50c264

IOS-2081 Icon | Fix background for space icon

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocument.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SetViewSettings/SetViewSettingsList/SetViewSettings.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SetViewSettings/SetViewSettingsList/SetViewSettingsListModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/ViewPicker/SetViewRow.swift
Modules/Services/Sources/Models/Block/BlockContainer/Array+Dataview.swift

iOS-1995 Automatic fallback to grid view type for all unsupported

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/Alerts/DashboardAccountDeletionAlert/DashboardAccountDeletionAlert.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/Alerts/DashboardAccountDeletionAlert/DashboardAccountDeletionAlertModel.swift
Anytype/Sources/ServiceLayer/Auth/AccountDeleteError.swift
Anytype/Sources/ServiceLayer/Auth/AuthService.swift

IOS-2079 Account | Add delete error

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Date/DateRelationDetailsRowView.swift
Anytype/Supporting files/Info.plist
AnytypeTests/Info.plist

Cherry pick this PR https://github.com/anyproto/anytype-swift/pull/634 and up patch version

iOS-1969 Hot fix | Can't choose exact date in date relation

---

Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Subviews/WidgetObjectListRowView.swift

Fix: Use tap action for menu action

IOS-2193 Fix: Use tap action for menu action

---

Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetSwipeActionView.swift

https://github.com/anyproto/anytype-swift/assets/2483784/d544f567-3dd0-46b1-a463-29ab63d3c317

IOS-2153 Widget | Add gesture for widget without create new action

---

Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift

Copy space id instead targetSpaceId

IOS-2186 Copy space id instead targetSpaceId

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/EditorConstants.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Creation/SetObjectCreationCoordinator.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Creation/SetObjectCreationHelper.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/CreateObject/CreateObjectModuleAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/CreateObject/CreateObjectViewModel.swift
Modules/Services/Sources/Models/ObjectType.swift

I will migrate to async await in the next PR

IOS-2132 Write title of of Note types to the first block

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchInteractor.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/Assembly/NewSearchModuleAssembly.swift
Anytype/Sources/PresentationLayer/Search screen/Assembly/ObjectTypeSearchModuleAssembly.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/Legacy_ObjectTypeSearchViewModel/Interactor/Legacy_ObjectTypeSearchInteractor.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/Legacy_ObjectTypeSearchViewModel/Legacy_ObjectTypeSearchViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/Legacy_ObjectTypeSearchViewModel/MultiselectObjectTypesSearchViewModel.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Models/ObjectType.swift

Not in final design, not yet support all the functions but already working.

IOS-2091 First iteration of new type picker module

---

Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsViewModel.swift
Modules/Services/Sources/Models/Extensions/DetailsLayout+Visible.swift

Disable creation of objects in sets by non-page-like types

IOS-2111 Disable creation of objects in sets by non-page-like types

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Container/RelationListContainerView.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

\+ fix some texts
Will be merged to the base relation editing [PR](https://github.com/anyproto/anytype-swift/pull/695)
https://github.com/anyproto/anytype-swift/assets/6065952/0f6750b5-81eb-4d26-95dd-e2b8b4338017

iOS-2228 Empty state for blocked select relation

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchInteractor.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel+State.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/Assembly/ObjectTypeSearchModuleAssembly.swift
Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift

IOS-2091 Add support for multi-sectioned types representation

---

Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchInteractor.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/Legacy_ObjectTypeSearchViewModel/Interactor/Legacy_ObjectTypeSearchInteractor.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/Legacy_ObjectTypeSearchViewModel/Legacy_ObjectTypeSearchViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsSearchInteractor.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsSearchViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Creation/SetObjectCreationHelper.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/MockSetDocument.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocument.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocumentProtocol.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsViewModel.swift
Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift
Modules/Services/Sources/Models/Details/Entities/MarketplaceId.swift

Just renames without any logic changes

IOS-2091 new design for type selection menu

---

Anytype.xcodeproj/project.pbxproj
Anytype.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/SetObjectCreationSettingsCoordinator.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/Assembly/NewSearchModuleAssembly.swift
Anytype/Sources/PresentationLayer/Search screen/Assembly/NewSearchModuleAssemblyProtocol.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetRouter.swift

Ios 2091 new design for type selection menu

---

Anytype/Sources/PresentationLayer/ObjectCreationSettings/Assembly/SetObjectCreationSettingsModuleAssembly.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/Dataview/SetObjectCreationSettingsInteractor.swift
Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift

Ios 1982 support recently used order of types in all menus where user

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/SwiftUI/Alerts/ShareEnvironment.swift
Anytype/Sources/PresentationLayer/Modules/ShareOptions/SharingTip/SharingTipAssembly.swift
Anytype/Sources/PresentationLayer/Modules/ShareOptions/SharingTip/SharingTipCoordinator.swift
Anytype/Sources/PresentationLayer/Modules/ShareOptions/SharingTip/SharingTipView.swift
Anytype/Sources/PresentationLayer/Modules/ShareOptions/SharingTip/SharingTipViewModel.swift

https://github.com/anyproto/anytype-swift/assets/2483784/9328d989-c510-42d9-8da5-820fd791ba05

IOS-2198 Sharing | Fix crash on ipad

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/Models/Relations/Entities/RelationValue/RelationObject.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Container/RelationListContainerView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/Coordinator/ObjectRelationListCoordinatorAssembly.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/Coordinator/ObjectRelationListCoordinatorView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/Coordinator/ObjectRelationListCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/Interactor/FileRelationListInteractor.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/Interactor/ObjectRelationListInteractor.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/Interactor/ObjectRelationListInteractorProtocol.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationListModuleAssembly.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationListView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationListViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationOption.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationOptionView.swift
Anytype/Sources/PresentationLayer/RelationValueFlow/RelationValueCoordinator.swift
Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

It looks in the same way like Object relation except of long tap actions (there is no duplication here)
https://github.com/anyproto/anytype-swift/assets/6065952/01400bd3-845f-4fb6-9d03-84180c17ddbe

iOS-2259 Make files relation list

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchInteractor.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel+State.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
Anytype/Sources/ServiceLayer/Object/TypeProvider/ObjectTypeProviderProtocol.swift
Anytype/Sources/ServiceLayer/Object/TypesService/TypesService.swift
Anytype/Sources/ServiceLayer/Object/TypesService/TypesServiceProtocol.swift
Anytype/Sources/ServiceLayer/ServiceLocator.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Services/Workspace/WorkspaceService.swift

IOS-2255 Type picker | Longtap actions

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Relations/RelationViewProvider/RelationValueView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Relations/RelationViewProvider/ValueViews/SwiftUI/CheckboxRelationView.swift

iOS-2122 Add name to the checkbox relations (in featured view and in sets)

---

Anytype/Sources/PresentationLayer/Auth/JoinFlow/SoulView/SoulViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationOptionView.swift

iOS-2270 Fix auth analytic event

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/CoreLayer/StoreLayer/AppActions/AppAction.swift
Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceJoinMVPView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceShareMPVView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceShareMVPView.swift
Anytype/Sources/ServiceLayer/DeeplinkParser/DeepLinkParser.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
Modules/ProtobufMessages/Sources/Protocol/models.pb.swift
Modules/Services/Sources/Models/Gallery/GalleryManifest.swift
Modules/Services/Sources/Models/Space/SpaceInvite.swift
Modules/Services/Sources/Models/Space/SpaceInviteView.swift
Modules/Services/Sources/Services/Gallery/GalleryService.swift
Modules/Services/Sources/Services/Workspace/WorkspaceService.swift
Shared/SharedContants.swift

https://github.com/anyproto/anytype-swift/assets/2483784/25ba986b-5c02-440b-9c7e-cc4fb06ce96e

iOS-2267 Multispaces | join and share flow MVP ONLY for testing (to space branch)

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Assemblies/CoordinatorsDI.swift
Anytype/Sources/PresentationLayer/Assemblies/CoordinatorsDIProtocol.swift
Anytype/Sources/PresentationLayer/Assemblies/ModulesDI.swift
Anytype/Sources/PresentationLayer/Assemblies/ModulesDIProtocol.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorAssembly.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceShareCoordinator/SpaceShareCoordinatorAssembly.swift
Anytype/Sources/PresentationLayer/Flows/SpaceShareCoordinator/SpaceShareCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceShareCoordinator/SpaceShareCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsModuleOutput.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift

https://github.com/anyproto/anytype-swift/assets/2483784/f8f58c32-abba-4634-a3f3-7d50623c7361

iOS-2160 Multispaces | Add empty share space flow (to multispace branch)

---

AnyTypeTests/Home/HomePathTests.swift
Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/HomePath.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelView.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
🚨🚨🚨🚨🚨🚨🚨🚨ATTENTION🚨🚨🚨🚨🚨🚨🚨🚨
🚨🚨🚨🚨🚨🚨🚨UNIT TEST ZONE🚨🚨🚨🚨🚨🚨🚨
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

IOS-2256 Home Navigation | Add swipe gesture for test

---

Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
Anytype/Sources/ServiceLayer/Object/TypesService/TypesPinStorage.swift
Anytype/Sources/ServiceLayer/Object/TypesService/TypesService.swift
Anytype/Sources/ServiceLayer/Object/TypesService/TypesServiceProtocol.swift
Modules/AnytypeCore/AnytypeCore/Extensions/Array+Extensions.swift

- Remove context menu actions from library types
- Filter out deleted and archived types from pins section

IOS-2255 type picker | Polishing

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/LinkToObjectFlow/LinkToObjectCoordinatorAssembly.swift
Anytype/Sources/PresentationLayer/LinkToObjectFlow/LinkToObjecttCoordinator.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/CompactList/CollectionsCompactListWidgetModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/CompactList/FavoriteCompactListWidgetModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/CompactList/SetsCompactListWidgetModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/List/CollectionsListWidgetModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/List/FavoriteListWidgetModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/List/SetsListWidgetModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/CollectionsWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/FavoriteWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/ObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetsWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Tree/Specific/FavoriteTreeWidgetModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Tree/Specific/ObjectTreeWidgetModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/ShareOptions/ShareOptionsInteractor.swift
Anytype/Sources/PresentationLayer/Modules/ShareOptions/ShareOptionsModuleAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/AccessoryViewBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/MarkupModeView/MarkupAccessoryViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionViewController/MentionsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/Page/EditorPageModuleAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/SimpleTableDependenciesBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
Anytype/Sources/ServiceLayer/Dashboard/DashboardService.swift
Anytype/Sources/ServiceLayer/Object/DefaultObjectCreationService/DefaultObjectCreationService.swift
Anytype/Sources/ServiceLayer/Object/PageService/PageRepository.swift
Anytype/Sources/ServiceLayer/ServiceLocator.swift

Use object service for object creation
Renamed PageRepository -> DefaultObjectCreationService and make it single responsibility only

iOS-2282 Service layer celanup

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Container/RelationListContainerView.swift

iOS-2294 Update empty state for objects relation + remove search if there are no objects yet

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Resources/Strings/en.lproj/Localizable.stringsdict
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/InviteLinkView.swift
Modules/Services/Sources/Models/Space/SpaceInvite.swift
Modules/Services/Sources/Services/Workspace/WorkspaceService.swift

iOS-2293 Multispaces | invite link

---

Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/SetObjectCreationSettingsCoordinator.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/Dataview/SetObjectCreationSettingsInteractor.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/Assembly/NewSearchModuleAssembly.swift
Anytype/Sources/PresentationLayer/Search screen/Assembly/NewSearchModuleAssemblyProtocol.swift
Anytype/Sources/PresentationLayer/Search screen/Assembly/ObjectTypeSearchModuleAssembly.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/Legacy_ObjectTypeSearchViewModel/Interactor/Legacy_ObjectTypeSearchInteractor.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/ChangeTypeAccessoryView/ChangeTypeAccessoryViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Builders/SlashMenuItemsBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetRouter.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/MockSetDocument.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocument.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocumentProtocol.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Subscriptions/Set/SetSubscriptionData.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsViewModel.swift
Anytype/Sources/ServiceLayer/Object/TypesService/TypesService.swift
Anytype/Sources/ServiceLayer/Object/TypesService/TypesServiceProtocol.swift
Modules/Services/Sources/Models/Extensions/DetailsLayout+Visible.swift

Also separate availability settings and create button
https://github.com/anyproto/anytype-swift/assets/6065952/2f7b2031-dbbe-4050-b4bb-12157b657c17

iOS-2272 Support file visibility: Set

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/SwiftUI/Alerts/Bottom/BottomAlertButtonView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Alerts/Bottom/BottomAlertButttonStack.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Alerts/Bottom/BottomAlertView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Alerts/Bottom/ButtomAlertHeaderImageView.swift

https://github.com/anyproto/anytype-swift/assets/2483784/24147332-f3fa-43ea-8f76-817ae8b44c57

IOS-2319 BottomAlert | Custom button layout & update container

---

Anytype/Sources/CoreLayer/StoreLayer/AppActions/AppAction.swift
Anytype/Sources/CoreLayer/StoreLayer/QuickActions/QuickAction.swift
Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/HomeCreateObjectTip.swift
Anytype/Sources/ServiceLayer/DeeplinkParser/DeepLinkParser.swift

Fix app action analytics routing
Fix selectType tooltip analytics

iOS-2323 Analytics fixes

---

Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/Page/EditorPageModuleAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/Block/SimpleTableCellsBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/Block/TextBlock/SimpleTablesTextBlockActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/SimpleTableDependenciesBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageBlocksStateManager.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
Anytype/Sources/ServiceLayer/Block/Pastboard/Operations/PasteboardTask.swift
Anytype/Sources/ServiceLayer/Block/Pastboard/PasteboardHelper.swift
Anytype/Sources/ServiceLayer/Block/Pastboard/PasteboardService.swift
Anytype/Sources/ServiceLayer/Block/Pastboard/PasteboardServiceProtocol.swift

iOS-2324 Pasteboard | Initial cleanup

---

Anytype/Sources/Analytics/AnalyticsConstants.swift
Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelViewModel.swift

IOS-2326 Remove unused analytics parameters

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Text/Actions/TextRelationReloadContentActionViewModel.swift
Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/HomeCreateObjectTip.swift
Anytype/Sources/PresentationLayer/Modules/ShareOptions/ShareOptionsInteractor.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/AccessoryViewBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/AccessoryViewSwitcher.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/ChangeTypeAccessoryView/ChangeTypeAccessoryViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/ChangeTypeAccessoryView/HorizonalTypeListView.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/ChangeTypeAccessoryView/HorizonalTypeListViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/Page/EditorPageModuleAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel+ChangeType.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/CreateObject/CreateBookmarkViewModel.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandler.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandlerProtocol.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionService/BlockActionService.swift
Anytype/Sources/ServiceLayer/Block/Pastboard/PasteboardHelper.swift
Modules/Services/Sources/Services/Bookmark/BookmarkService.swift
Modules/Services/Sources/Services/Bookmark/BookmarkServiceProtocol.swift

IOS-2324 Pasteboard | Add paste support to editor accessory view

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/Interactor/FileRelationListInteractor.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/Interactor/ObjectRelationListInteractor.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/Interactor/ObjectRelationListInteractorProtocol.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationListView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationListViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationOption.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationOptionView.swift
Modules/Services/Sources/Models/Details/ObjectDetails.swift

https://github.com/anyproto/anytype-swift/assets/6065952/d11e7f2b-e59b-41d0-b7d3-75d2bbb8eb52

iOS-2342 Add restrictions for the object / files relations list

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/Alerts/Bottom/BottomAlertButtonView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Alerts/Bottom/BottomAlertView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceChangeAccessView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceParticipantRemoveView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceRequestView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceShareParticipantView.swift
Anytype/Sources/PresentationLayer/TextEditor/Views/Alerts/DocumentCommonOpenErrorView.swift
Anytype/Sources/ServiceLayer/Subscriptions/ParticipantsSubscriptionBySpaceService.swift
Modules/Services/Sources/Services/SearchService/SearchHelper.swift
Modules/Services/Sources/Services/Workspace/WorkspaceService.swift

https://github.com/anyproto/anytype-swift/assets/2483784/1ac75eb9-b2ee-4168-b5e3-e95145c5b974

iOS-2303 Multiplayer | Participant actions

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceShareParticipantView.swift

https://github.com/anyproto/anytype-swift/assets/2483784/7d2dde1a-4f9a-47a4-87d6-172db4441145

iOS-2387 Multispaces | Confirm removing action

---

Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Bookmark/BlockBookmarkViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/Block/TextBlock/SimpleTablesTextBlockActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/ContextualMenu/EditorContextualMenu.swift
Modules/AnytypeCore/AnytypeCore/Utils/HandlerKeyStorage.swift
Modules/Services/Sources/Models/Block/BlockConverters/BlockBookmarkConverter.swift
Modules/Services/Sources/Models/Block/BlockConverters/BlocksModelsConverter.swift

Just fix `paste as bookmark`, other problems in progress
https://github.com/anyproto/anytype-swift/assets/6065952/9ff8d049-54be-40ab-bb89-5983e6b223bc

iOS-2367 Editor | Fix paste as bookmark

---

Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionViewController/MentionsViewModel.swift

It was redundant string - checked it

iOS-2373 Editor | Remove redundant string - fix mention warning

---

Anytype/Sources/PresentationLayer/Assemblies/ModulesDI.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpceMembers/SpaceMembersModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/SpceMembers/SpaceMembersView.swift
Anytype/Sources/PresentationLayer/Modules/SpceMembers/SpaceMembersViewModel.swift
Anytype/Sources/ServiceLayer/Subscriptions/ParticipantsSubscriptionBySpaceService.swift
Modules/Services/Sources/Services/SearchService/SearchHelper.swift

https://github.com/anyproto/anytype-swift/assets/2483784/2d597491-2a4f-4503-89b9-7c893c1c02a6

iOS-2357 Space Members | Show data

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Design system/Fonts/AnytypeFont.swift
Anytype/Sources/Design system/Fonts/AnytypeFontConfig.swift
Anytype/Sources/PresentationLayer/Assemblies/ModulesDI.swift
Anytype/Sources/PresentationLayer/Assemblies/ModulesDIProtocol.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinatorAssembly.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinatorModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/EmailVerification/EmailVerificationAssembly.swift
Anytype/Sources/PresentationLayer/Modules/Membership/EmailVerification/EmailVerificationView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/EmailVerification/EmailVerificationViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTeirView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionAssembly.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipTierInfoView.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift

https://github.com/anyproto/anytype-swift/assets/6589348/7317e58f-1f58-46b1-a560-811a24503981

IOS-2397 Membership | First iteration of email validation

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/ImageAssets.swift
Anytype/Generated/Strings.swift
Anytype/Resources/Assets.xcassets/Membership/tier_builder_large.imageset/Contents.json
Anytype/Resources/Assets.xcassets/Membership/tier_builder_large.imageset/logo builder.pdf
Anytype/Resources/Assets.xcassets/Membership/tier_cocreator_large.imageset/Contents.json
Anytype/Resources/Assets.xcassets/Membership/tier_cocreator_large.imageset/logo Co-Creator.pdf
Anytype/Resources/Assets.xcassets/Membership/tier_explorer_large.imageset/Contents.json
Anytype/Resources/Assets.xcassets/Membership/tier_explorer_large.imageset/Group 3787.pdf
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/StandardButtonConfig.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/StandardButtonStyle.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/iOS15Wrappers/View+Autofocus.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinatorModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/EmailVerification/EmailVerificationAssembly.swift
Anytype/Sources/PresentationLayer/Modules/Membership/EmailVerification/EmailVerificationView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/EmailVerification/EmailVerificationViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionAssembly.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Views/MembershipTierSuccessView.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift

https://github.com/anyproto/anytype-swift/assets/6589348/2e18def6-4550-458e-90b8-56f60b38b9e7

iOS-2433 Membership | Tier explorer - Add resend email timer and success screen

---

Anytype/Sources/PresentationLayer/Assemblies/CoordinatorsDI.swift
Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorAssembly.swift
Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorViewModel.swift

iOS-2422 Relations editing | Use snackbar instead of toastPresenter

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/AsyncStandardButton.swift
Anytype/Sources/PresentationLayer/Modules/Membership/EmailVerification/EmailVerificationViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTeirView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierListView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTier.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipTierInfoView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Views/MembershipTierSuccessView.swift
Anytype/Sources/PresentationLayer/Settings/Settings/Sections/SettingsSectionItemView.swift
Anytype/Sources/PresentationLayer/Settings/Settings/SettingsModuleAssembly.swift
Anytype/Sources/PresentationLayer/Settings/Settings/SettingsView.swift
Anytype/Sources/PresentationLayer/Settings/Settings/SettingsViewModel.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift

https://github.com/anyproto/anytype-swift/assets/6589348/6060af74-06c4-47a6-b2ce-29f90285150f

Ios-2433 Membership | Dynamic settings badge

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipOwnerInfoSheetView.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift
Modules/Services/Sources/Services/Name/NameService.swift
Modules/Services/Sources/ServicesDI.swift

https://github.com/anyproto/anytype-swift/assets/6589348/309ffd2f-80e4-4a80-a501-98982fb88eb5

IOS-2444 Membership | Add name input view

---

Anytype/Generated/Assets.swift
Anytype/Generated/Color+Assets.swift
Anytype/Generated/Color+Info.swift
Anytype/Generated/ImageAssets.swift
Anytype/Generated/Strings.swift
Anytype/Generated/UIColor+Assets.swift
Anytype/Resources/Assets.xcassets/Membership/tier_custom_small.imageset/Contents.json
Anytype/Resources/Assets.xcassets/Membership/tier_custom_small.imageset/Membership Logo.pdf
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Resources/SystemColors.xcassets/Gradients/fadingSky.colorset/Contents.json
Anytype/Sources/Design system/Colors/Gradients/BannerGradient.swift
Anytype/Sources/Design system/Colors/Gradients/MembershipTeirGradient.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinatorModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTeirView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierExtensions.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipOwnerInfoSheetView.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift
Modules/Services/Sources/Services/Membership/Model/EmailVerificationData.swift
Modules/Services/Sources/Services/Membership/Model/MembershipStatus.swift

IOS-2456 Membership | Support custom tier

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetViewModel.swift

IOS-2456 Membership | Add minimum number of characters prompt

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinatorModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTeirView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierListView.swift
Anytype/Sources/PresentationLayer/Settings/Settings/SettingsViewModel.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift
Modules/Services/Sources/Services/Membership/Model/EmailVerificationData.swift
Modules/Services/Sources/Services/Membership/Model/MembershipStatus.swift
Modules/Services/Sources/Services/Name/NameService.swift

iOS-2456 integration of middleware | Supported membership status pending

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinatorModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTeirView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierListView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipStatusExtension.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipOwnerInfoSheetView.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift
Modules/Services/Sources/Services/Membership/Model/MembershipStatus.swift

Supported membership end date
Supported payment method display

iOS-2456 Membership | integration of middleware branch

---

Anytype/Sources/Models/Documents/Document/BaseDocument.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelView.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Manager/HomeWidgetsStateManager.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Submodules/HomeBottomPanel/HomeBottomPanelView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Submodules/HomeBottomPanel/HomeBottomPanelViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/LinkWidgetViewContainer.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetContainerView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetContainerViewModel.swift
Anytype/Sources/ServiceLayer/AccountParticipantsStorage/AccountParticipantsStorage.swift
Anytype/Sources/ServiceLayer/ServiceLocator.swift

https://github.com/anyproto/anytype-swift/assets/2483784/add80abc-1046-4766-84dd-4e5302614c09

iOS-2388 Multiplayer | Viewer access |  home readonly

---

Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/WidgetObjectListModuleAssembly.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/WidgetObjectListView.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/WidgetObjectListViewModel.swift

https://github.com/anyproto/anytype-swift/assets/2483784/2f87324a-2cda-4e76-851c-cd94e3a9b16d

iOS-2388 Multiplayer | Viewer access | widget list readonly

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Notifications/NotificationCoordinator.swift
Anytype/Sources/PresentationLayer/Notifications/Specific/ParticipantApprove/ParticipantApproveNotificationView.swift
Anytype/Sources/PresentationLayer/Notifications/Specific/ParticipantApprove/ParticipantApproveNotificationViewModel.swift
Anytype/Sources/PresentationLayer/Notifications/Specific/ParticipantDecline/ParticipantDeclineNotificationView.swift
Anytype/Sources/PresentationLayer/Notifications/Specific/ParticipantDecline/ParticipantDeclineNotificationViewModel.swift

https://github.com/anyproto/anytype-swift/assets/2483784/6674cfcf-3828-4186-8a9b-2a17e9ab0391
https://github.com/anyproto/anytype-swift/assets/2483784/f1f7f11a-1076-4a6b-9600-93538a5f20b9

iOS-2466 Multiplayer | Remove and access notifications for participant

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/Coordinator/ObjectRelationListCoordinatorView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/Coordinator/ObjectRelationListCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationListData.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationListView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationListViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/RelationSelectedOptions/RelationSelectedOptionsModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Select/Coordinator/SelectRelationListCoordinatorView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Select/Coordinator/SelectRelationListCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Select/SelectRelationListData.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Select/SelectRelationListView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Select/SelectRelationListViewModel.swift
Anytype/Sources/PresentationLayer/RelationValueFlow/RelationValueCoordinator/RelationValueCoordinatorViewModel.swift

After moving relations modules to the new DI

iOS-2455 Add struct if needed, clean a little

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Notifications/NotificationCoordinator.swift
Anytype/Sources/PresentationLayer/Notifications/Specific/ParticipantRemove/ParticipantRemoveNotificationView.swift
Anytype/Sources/PresentationLayer/Notifications/Specific/ParticipantRemove/ParticipantRemoveNotificationViewModel.swift

https://github.com/anyproto/anytype-swift/assets/2483784/b552627e-c4ef-4cf8-8e9a-8950b452e5cb

IOS-2466 Multiplayer | Add ParticipantRemove Notification

---

Anytype/Sources/Models/Documents/Document/BaseDocument+Extensions.swift

Missed after Editor refactoring

iOS-2535 Fix displaying empty backlinks in objects featured relations

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceJoin/SpaceJoinView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceJoin/SpaceJoinViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceJoin/Subivews/SpaceJoinConfirmationView.swift
Anytype/Sources/PresentationLayer/Modules/SpacesManager/SpacesManagerView.swift

https://github.com/anyproto/anytype-swift/assets/2483784/20a44c60-67d2-455a-a5b0-af75644dd195

IOS-2472 Request to join | open space manager

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Models/Relations/Entities/ObjectImportType+Loc.swift
Anytype/Sources/Models/Relations/RelationsBuilder.swift
Modules/Services/Sources/Models/ObjectImportType.swift

iOS-2229 Add mapping in UI for relation importType

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/SwiftUI/Alerts/Bottom/BottomAlertButtonView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Alerts/Bottom/BottomAlertView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/AsyncStandardButton.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/AsyncStandardButtonGroup.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/StandardButton.swift

https://github.com/anyproto/anytype-swift/assets/2483784/28cf5928-9def-44a0-be82-56ed019839b5

IOS-2521 Buttons | disable buttons if one is active

---

.github/workflows/automerge.yaml

iOS-2553 CI | Auto-merge for bot

---

Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTeirView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierListView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipStatusExtension.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipOwnerInfoSheetView.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift
Modules/Services/Sources/Services/Membership/Model/MembershipStatus.swift

IOS-2456 Membership | Support any name display

---

Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTeirView.swift

IOS-2456 Membership | Disable pending interactions

---

Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinatorModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTeirView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierListView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierExtensions.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipTierInfoView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Views/MembershipTierSuccessView.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift
Modules/Services/Sources/Services/Membership/Model/MembershipStatus.swift

MembershipTier -> MembershipTierId

IOS-2456 Rename

---

Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockActionHandler.swift

https://github.com/anyproto/anytype-swift/assets/6065952/bef4aa7e-e579-47a9-a821-3321df29b330

iOS-2367 Editor refactoring | Fix links

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/Models/Documents/Document/BaseDocument.swift
Anytype/Sources/Models/Documents/Document/BaseDocumentProtocol.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/ButtonForeground.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/AccessoryViewSwitcher.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeaderViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/Builders/SetPermissionsBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocument.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocumentProtocol.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetPermissions.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Empty/EditorSetEmptyView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Empty/EditorSetEmptyViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SetViewSettings/SetViewSettingsList/SetViewSettingsList.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SetViewSettings/SetViewSettingsList/SetViewSettingsListModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/ViewPicker/SetViewPicker.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/ViewPicker/SetViewPickerViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Table/SetTableViewHeader.swift
Anytype/Sources/ServiceLayer/DocumentsProvider/DocumentsProvider.swift

https://github.com/anyproto/anytype-swift/assets/2483784/ed599569-159b-4692-85e2-b9fde86c5227

iOS-2162 Set editor | read only

---

Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Code/CodeBlockContentConfiguration.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Code/CodeBlockView.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Code/CodeBlockViewModel.swift

OLD WITH BUG
https://github.com/anyproto/anytype-swift/assets/2483784/65c57c04-6c2e-40f0-ae92-94e860859dd0
FIXED
https://github.com/anyproto/anytype-swift/assets/2483784/38fab0d4-23fc-49e7-aafd-b9beeefbf823

IOS-2558 Editor | fix code block

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierExtensions.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Views/MembershipTierSuccessView.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift

iOS-2456 Membership | Small updates

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Resources/Strings/en.lproj/Localizable.stringsdict
Anytype/Sources/PresentationLayer/Settings/Settings/Sections/SettingsSectionItemView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift

IOS-2460 Space settings | Add requests counter & change text

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Models/ObjectPermissions/ObjectPermissions.swift
Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorAssembly.swift
Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectAction.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViews/ObjectActionRow.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViews/ObjectActionsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingModuleAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsViewModel.swift
Modules/DeepLinks/Sources/DeepLinks/DeepLink.swift
Modules/DeepLinks/Sources/DeepLinks/DeepLinkParser.swift

https://github.com/anyproto/anytype-swift/assets/2483784/a75b746e-bad3-416e-bc23-a2eedb39ba7e

iOS-2497 DeepLinks | support deep link to object

---

Anytype/Sources/Models/Documents/Document/BaseDocument.swift

BUG
https://github.com/anyproto/anytype-swift/assets/2483784/3d629d9a-b107-4933-bd03-1636f29cf0ad
FIX
https://github.com/anyproto/anytype-swift/assets/2483784/ec16a4ea-7f37-4256-821d-d3b2cc4c5d5c

IOS-2581 Editor | Fix relation animation

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/List/ListSectionHeaderView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/List/SectionHeaderView.swift

iOS-2579 Search | Add ability to add content to the right side of list header

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/EmptyStateView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Container/RelationListContainerView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/SearchView/SearchView.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Modules/GalleryInstallationPreview/GalleryInstallationPreviewView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift

https://github.com/anyproto/anytype-swift/assets/6065952/e0254d43-c8c4-44cd-9bd3-e1b1978fe628

iOS-2579 Search | Update empty state in SearchView

---

Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift

IOS-2594 Membership | Show test tiers

---

Anytype/Sources/Models/Extensions/Participant+Extensions.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift
Anytype/Sources/ServiceLayer/ActiveSpaceParticipantsStorage/ActiveSpaceParticipantStorage.swift
Modules/Services/Sources/Models/Participant.swift

IOS-2585 Show space owner resolved name

---

Modules/Services/Sources/Models/Details/BundledRelationValueProvider+CustomFields.swift

iOS-2281 Add extension for all files layout objects

---

Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinator.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
Anytype/Sources/ServiceLayer/Block/Mention/MentionObjectsService.swift
Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift
Anytype/Sources/ServiceLayer/Object/Search/SearchServiceProtocol.swift

https://github.com/anyproto/anytype-swift/assets/6065952/6f46532b-692f-41a7-8b22-2fb960a8affb

iOS-2279 Show object and files in mention and /linkto menu

---

Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinatorModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipOwnerInfoSheetView.swift

Uploading Simulator Screen Recording - iPhone 15 - 2024-04-08 at 12.58.16.mp4…

IOS-2594 Membership | Support simple payments 

---

Anytype/Sources/Models/Relations/RelationsBuilder.swift

Use identity as a fallback for globalName

IOS-2606 Hack globalName relation value

---

Anytype/Resources/Assets.xcassets/Common/arrowForward.imageset/Contents.json
Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/DynamicForeground.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/IconView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/TodoIconView.swift
Anytype/Sources/PresentationLayer/Settings/Settings/Sections/SettingsSectionItemView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/ViewPicker/SetViewPicker.swift

IOS-2605 Multiplayer | support disable state for text

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/SpaceJoin/SpaceJoinView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceJoin/SpaceJoinViewModel.swift

https://github.com/anyproto/anytype-swift/assets/2483784/d1b9b4fc-b24c-49fa-b48c-ebbaf1653674

IOS-2601 Space Join | Add alert | Already a member

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/List/ListSectionHeaderView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/List/SectionHeaderView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchView.swift

https://github.com/anyproto/anytype-swift/assets/6065952/438be9da-d42c-4020-b9e1-087c9a1009af

iOS-2593 Search | Add backlinks swipe action

---

AnyTypeTests/Services/UniversalLinkParserTests.swift
Anytype.xcodeproj/project.pbxproj
Anytype/Anytype.entitlements
Anytype/Sources/ApplicationLayer/AppDelegate.swift
Anytype/Sources/ApplicationLayer/SceneDelegates/SceneDelegate.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Anytype/Sources/ServiceLayer/ServicesDI.swift
Anytype/Sources/ServiceLayer/UniversalLinks/UniversalLink.swift
Anytype/Sources/ServiceLayer/UniversalLinks/UniversalLinkParser.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

https://github.com/anyproto/anytype-swift/assets/2483784/49ebd16f-6ecb-425c-a0bc-e49aa55b9edc

iOS-2400 Space Share | Support universal links

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Auth/Auth/AuthView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/EmptyStateView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleView.swift
Anytype/Sources/PresentationLayer/Settings/About/AboutApp.swift
Anytype/Sources/PresentationLayer/Settings/About/AboutViewModel.swift
Anytype/Supporting files/LocalStoreKitConfiguration.storekit

IOS-2574 Add actionable report bug link

---

Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Empty/EditorSetEmptyView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Empty/EditorSetEmptyViewModel.swift

https://github.com/anyproto/anytype-swift/assets/6065952/fba5e20b-6ab1-4352-8460-fbce6e4a4de3

iOS-1240 Basic | Add empty state for set with empty list

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Auth/LoginFlow/LoginView.swift

iOS-2663 Update onboarding log in screen

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Auth/JoinFlow/KeyPhraseMoreInfoView/KeyPhraseMoreInfoView.swift
Anytype/Sources/PresentationLayer/Auth/LoginFlow/LoginView.swift

iOS-2662 Update onboarding key info screen

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Auth/JoinFlow/KeyPhraseMoreInfoView/KeyPhraseMoreInfoView.swift
Anytype/Sources/PresentationLayer/Auth/JoinFlow/KeyPhraseView/KeyPhraseView.swift
Anytype/Sources/PresentationLayer/Auth/JoinFlow/SoulView/SoulView.swift
Anytype/Sources/PresentationLayer/Auth/LoginFlow/LoginView.swift

iOS-2660 Update onboarding name screen

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/InfoPlist.strings
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Resources/Strings/en.lproj/Localizable.stringsdict
Anytype/Sources/PresentationLayer/Auth/DeletedAccount/DeletedAccountViewModel.swift
Anytype/Sources/PresentationLayer/Auth/LoginFlow/LoginViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchView.swift
Anytype/Sources/PresentationLayer/Debug/DebugMenuView.swift
Anytype/Sources/PresentationLayer/Flows/InitialCoordinator/InitialCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/Alerts/DashboardLogoutAlert/DashboardLogoutAlert.swift
Anytype/Sources/PresentationLayer/Settings/About/AboutViewModel.swift
Anytype/Sources/PresentationLayer/Settings/Account/SettingsAccountView.swift
Anytype/Sources/PresentationLayer/Settings/KeychainPhraseView/KeychainPhraseView.swift
Anytype/Sources/PresentationLayer/Settings/KeychainPhraseView/KeychainPhraseViewModel.swift
Anytype/Sources/PresentationLayer/Settings/Settings/SettingsView.swift
Anytype/Sources/ServiceLayer/Auth/AuthServiceError+Localize.swift

`Recovery phrase` -> `Key`
`Account` -> `Vault`

iOS-2664 Update texts in whole app

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierView/MembershipTierView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipOwnerInfoSheetView.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift

IOS-2668 Show manage subscription screen

---

Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/AccessoryViewStateManager.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockActionHandler.swift

- Fix bug when use add slash text and try to tap enter
- Hide slash or mention search after two spaces
https://github.com/anyproto/anytype-swift/assets/2483784/16df42fa-d7ad-413c-9a6d-c36fc9e4e9ed
https://github.com/anyproto/anytype-swift/assets/2483784/c17a54c1-ca62-4ca7-a23c-70d17ffe9875

IOS-2592 Editor | fix mentions and slash menu and add hidden logic

---

Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Collection/Cell/SetGalleryViewCell.swift

iOS-2696 Fix gallery layout in Set / Collection

---

Anytype/Sources/Design system/Fonts/AnytypeFont.swift
Anytype/Sources/Design system/Fonts/AnytypeFontConfig.swift
Anytype/Sources/Design system/Fonts/SwiftUIFont.swift
Anytype/Sources/Design system/Fonts/UIKitFont.swift
Anytype/Sources/Helpers/Extensions/StringExtensions.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleView.swift

iOS-2445 Membership | Add fallback font for non latin languages

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionCarousel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareView.swift

https://github.com/anyproto/anytype-swift/assets/6589348/c8c89531-4e8f-4652-9666-ada3bc4647ee

IOS-2620 Membership | Add carousel for tiers display

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/SwiftUI/AnytypeIndexView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionCarousel.swift

https://github.com/anyproto/anytype-swift/assets/6589348/fab3617b-5ae4-459b-a364-3b2c410a3e17

iOS-2559 Membership | Add fancy index view

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Models/ExceptionalSetSort.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Models/SetContentViewDataBuilder.swift

Made it like on desktop
https://github.com/anyproto/anytype-swift/assets/6065952/21f8201d-8473-43c2-8a6f-94b636e9fd14

iOS-2712 Force insert Done relation after the Name for all Sets/Collections

---

crowdin.yml

IOS-2732 Update crowdin

---

Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/CursorModeView/CursorModeAccessoryViewModel.swift

https://github.com/anyproto/anytype-swift/assets/6065952/519f71cd-8839-4c94-b00f-3a329a15c9c4

iOS-2070 Reduce cursor accessory view items for description

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/Design system/Fonts/UIKitFont.swift
Anytype/Sources/FrameworkExtensions/SwiftUI/Geometry/FrameCatcher.swift
Anytype/Sources/FrameworkExtensions/SwiftUI/Geometry/View+ReadSize.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DragAndDrop/DragAndDropModels.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DragAndDrop/View+DragAndDrop.swift

- Fix time for get font
- Fix update where is not needed

IOS-2745 Home | fix slow updates

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageController.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift

iOS-2786 Attempt to fix crash call layout from the background thread

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Models/Extensions/MembershipServiceError+Localisation.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetViewModel.swift
Anytype/Sources/ServiceLayer/StoreKitService/StoreKitService.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift

IOS-2395 Support middleware receipt validation errors

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Models/SetSort.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Sorts/Coordinator/SetSortsListCoordinatorView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Sorts/List/SetSortsListViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Sorts/Types/SetSortTypeItem.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Sorts/Types/SetSortTypesListView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Sorts/Types/SetSortTypesListViewModel.swift

iOS-2810 Add additional sorting options for empty values

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/HomeFlow/Views/MembershipNameFinalization/MembershipNameFinalizationView.swift
Anytype/Sources/PresentationLayer/Flows/HomeFlow/Views/MembershipNameFinalization/MembershipNameFinalizationViewModel.swift
Modules/Services/Sources/Services/Membership/MembershipService.swift

IOS-2797 Membership | Support finalise membership

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/Attributes/AttributeScopes+Custom.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchCell.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchDataBuilder.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchDataSection.swift
Anytype/Sources/ServiceLayer/RelationStorage/RelationDetailsStorage.swift
Anytype/Sources/ServiceLayer/RelationStorage/RelationDetailsStorageProtocol.swift

Highlight searched words with custom markdown - works for blocks and text relations
https://github.com/anyproto/anytype-swift/assets/6065952/18bb2694-f8cd-4153-9206-dfd97791f459

iOS-2578 Highlight searched words with custom markdown

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/Attributes/AttributeScopes+Custom.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchCell.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchDataBuilder.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchDataSection.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchViewModel.swift
Anytype/Sources/ServiceLayer/RelationStorage/RelationDetailsStorage.swift
Anytype/Sources/ServiceLayer/RelationStorage/RelationDetailsStorageProtocol.swift

Remove description as default row, add textWithHighlight for block search - raw version

iOS-2578 Raw block search results show

---

Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift

https://github.com/anyproto/anytype-swift/assets/6589348/d41985e5-cb2c-4453-a2ff-4f50d5d28004

IOS-2780 Add drag overlay to dismiss tiers sheets

---

Anytype/Sources/PresentationLayer/Settings/Appearance/AppIcon/AppIcon.swift
Anytype/Sources/PresentationLayer/Settings/Appearance/AppIcon/AppIconManager.swift
Anytype/Sources/PresentationLayer/Settings/Appearance/SettingsAppearanceView.swift
Modules/Services/Sources/Services/Membership/MembershipModelBuilder.swift

IOS-2826 Settings | Add scrollable icon picker

---

Anytype/Sources/PresentationLayer/Debug/DebugMenuView.swift

https://github.com/anyproto/anytype-swift/assets/6589348/96613812-2f37-4cc2-b350-08ce43b05b27
https://github.com/anyproto/anytype-swift/assets/6589348/e08470d2-d7a1-4a9d-b21b-670640d1dd99

IOS-2836 Cleanup debug menu

---

Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift

iOS-2824 Fix set / collection creation via slash menu

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/Page/EditorPageModuleAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/Set/EditorSetModuleAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageController.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewInput.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModelConfiguration.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/EditorBlockCollectionController.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

Scroll block to the center vertically without animation
https://github.com/anyproto/anytype-swift/assets/6065952/da34eea6-d976-4710-b7bc-5dc5eacacbca

iOS-2845 Search | Scroll to searched block

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierView/MembershipTierView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierView/MembershipTierViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/OwnershipView/MembershipOwnerInfoSheetView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/OwnershipView/MembershipOwnerInfoSheetViewModel.swift
Anytype/Sources/PreviewMocks/Mocks/MembershipStatusStorageMock.swift
Anytype/Sources/ServiceLayer/MembershipStatusStorage/MembershipStatusStorage.swift
Anytype/Sources/ServiceLayer/MembershipTierInfoProvider/MembershipMetadataProvider.swift
Anytype/Sources/ServiceLayer/MembershipTierInfoProvider/MembershipTierOwningState.swift
Anytype/Sources/ServiceLayer/ServicesDI.swift

Implement membership metadata provider for Appstore related metadata

IOS-2848 Membership | Implement membership metadata provider

---

Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierView/MembershipTierView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierExtensions.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/OwnershipView/MembershipOwnerInfoSheetView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/OwnershipView/MembershipOwnerInfoSheetViewModel.swift
Modules/Services/Sources/Services/Membership/Model/MembershipStatus.swift
Modules/Services/Sources/Services/Membership/Model/MembershipTier.swift

iOS-2848 Membership | Add AnyTeam tier easter egg descriptions

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Auth/Auth/AuthView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetView.swift

IOS-2862 Add agreement disclamer

---

Anytype/Sources/Analytics/AnalyticsConstants.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchViewModel.swift

https://github.com/anyproto/anytype-swift/assets/6065952/bff69a19-9807-4c9e-b9ed-cc5a68086a35

iOS-2866 Search | Add default create object to global search

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/StandardButtonConfig.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/StandardButtonStyle.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DotsView/DotsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/RemoteStorage/RemoteStorageView.swift
Anytype/Sources/PreviewMocks/MockView.swift
Anytype/Sources/PreviewMocks/Mocks/FileLimitsStorageMock.swift
Modules/Services/Sources/Models/Usage/SpaceUsage.swift

Miscellaneous updates for storage incentives implementation

iOS-2864 Membership | add storage incentive preparation

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipConstants.swift
Anytype/Sources/PresentationLayer/SpaceSettings/RemoteStorage/RemoteStorageView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/RemoteStorage/RemoteStorageViewModel.swift
Anytype/Sources/PreviewMocks/Mocks/FileLimitsStorageMock.swift

IOS-2864 Membership | Use new design for storage incentive

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/SwiftUI/DragAndDrop/DragAndDropFrames.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DragAndDrop/DragAndDropModels.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DragAndDrop/DragAndDropVerticalDelegate.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DragAndDrop/View+DragAndDrop.swift

Rollback [this](https://github.com/anyproto/anytype-swift/pull/1342/files#diff-4bcf3690b44373ba6471996f1cd6df6ae4db29f4ab81e3f5b987f3c760017d84R20) pr and make new decition

IOS-2893 Home | fix dnd

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchView.swift

iOS-2908 Search | Fix swipe left and tap gesture clashing

---

Anytype/Sources/PresentationLayer/Debug/Views/MembershipDebugView.swift

https://github.com/anyproto/anytype-swift/assets/6589348/77b98710-889b-4fa1-a4ff-81f855a770a0

iOS-2395 Membership | Add transactions list to debug view

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/iOS15Wrappers/AutofocusedTextField.swift

Checked on different iOS versions and phones (simulators) - looks ok

iOS-2915 Remove textfield focus delay

---

Anytype.xcodeproj/project.pbxproj
Anytype.xcodeproj/xcshareddata/xcschemes/Anytype.xcscheme
Anytype.xcodeproj/xcshareddata/xcschemes/AnytypeShareExtension.xcscheme
Anytype.xcodeproj/xcshareddata/xcschemes/AnytypeWidgetExtension.xcscheme

IOS-2919 Core | Update xcode project settings

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Membership/MembershipUpgradeEmailBottomAlert.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTier+Upgrade.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierExtensions.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/RemoteStorage/RemoteStorageView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/RemoteStorage/RemoteStorageViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift

https://github.com/anyproto/anytype-swift/assets/6589348/351dadf7-6c24-4771-a6fb-9a764aa5b288

IOS-2926 Membership | Add space members incentive

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchViewModel.swift

https://github.com/anyproto/anytype-swift/assets/6065952/cb93c927-cdd8-4f2c-b768-16f5a652eff6

iOS-2903 Open first searched object by keyboard Go button

---

Anytype.xcodeproj/project.pbxproj
fastlane/FastlaneComment

IOS-2953 Fix fastlane

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Membership/MembershipUpgradeEmailBottomAlert.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceRequestView/SpaceRequestAlert.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceRequestView/SpaceRequestAlertModel.swift
Anytype/Sources/PresentationLayer/Notifications/NotificationCoordinatorView.swift
Anytype/Sources/PresentationLayer/Notifications/NotificationCoordinatorViewModel.swift

https://github.com/anyproto/anytype-swift/assets/6589348/7034f93a-763a-4cf5-9f5d-9ca3e541c43b
https://github.com/anyproto/anytype-swift/assets/6589348/234b02a6-4653-4b64-a350-57c2600ca64b

IOS-2926 Membership x Multiplayer | Add membership upgrade buttons in request actions

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/View+URL.swift

https://github.com/anyproto/anytype-swift/assets/2483784/f8432167-6986-44eb-9235-f7323c48a588

IOS-2927 Universal links | Add handle inside common url open method

---

Anytype.xcodeproj/project.pbxproj
Anytype.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinatorModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipStatusExtension.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Views/ConfettiOverlay.swift

https://github.com/anyproto/anytype-swift/assets/6589348/3d561922-4ea0-4e07-8538-0d9ed8510dee

iOS-2994 Membership | Add fun to tier purchase experience

---

Anytype/Sources/Models/Documents/Document/BaseDocument.swift
Anytype/Sources/Models/Documents/Events/EventConverters/MiddlewareEventConverter.swift
Anytype/Sources/Models/Documents/Events/Model/DocumentUpdate.swift

reproduced - when user delete a space

iOS-3010 Core | fix warning when we try to close document when closed by middleware side

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Specific/SetObjectGalleryWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/View/SetObjectViewRows.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/View/SetObjectViewWidgetSubmoduleView.swift

https://github.com/anyproto/anytype-swift/assets/2483784/a9742048-3c08-4a0c-a560-f76eb5a91cc1

IOS-2965 Set Widget | Add empty gallery view

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Models/BlockWidget+Limits.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetRow.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/View/SetObjectViewRows.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/View/SetObjectViewWidgetSubmoduleView.swift

https://github.com/anyproto/anytype-swift/assets/2483784/8d8b6efc-f3a4-4fb8-9a0a-b1eddb06d3e4

IOS-2965 Set widget | Add gallery item

---

Anytype/Sources/Models/Mention/MentionAttachment.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/TodoIconView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/ObjectIconView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationOptionView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Relations/FlowRelationsView/FlowRelationsView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Relations/FlowRelationsView/FlowRelationsViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Relations/RelationViewProvider/ValueViews/Views/Object/ObjectRelationView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/SearchView/Cell/SearchCell.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchCell.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/TitleWIthIconView/TitleWithIconView.swift
Anytype/Sources/PresentationLayer/Debug/Examples/ObjectIconExample.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetRow.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Tree/Common/Rows/TreeWidgetRowView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Tree/Common/TreeWidgetViewModel.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/Objects/TemplatePreview.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/BlockLinkViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/Support/BlockLinkState+Text.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Collection/Cell/SetGalleryViewCell.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Collection/Cell/SetListViewCell.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Models/SetContentViewDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Table/Row/SetContentViewItemConfiguration.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Table/Row/SetTableViewRow.swift
Modules/Services/Sources/Models/Details/BundledRelationsValueProvider+Icon.swift
Modules/Services/Sources/Models/Details/ObjectIcon.swift

- Enabled by default
- Disable for relations, search, mentions

IOS-3020 IconView | Support change checkbox for todo icon

---

Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceRequestView/SpaceRequestAlert.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceRequestView/SpaceRequestAlertModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceShareParticipantView.swift
Anytype/Sources/PresentationLayer/Notifications/NotificationCoordinatorViewModel.swift

https://github.com/anyproto/anytype-swift/assets/6589348/e8644768-7167-4550-be01-b2e544f2ac6f

IOS-3001 Space request | Add Icon to space request bottom alert

---

Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockActionHandler.swift

https://github.com/anyproto/anytype-swift/assets/6065952/17a2e1d0-a16d-4e25-9dd0-6ba40a3abc31

iOS-2925 Editor | Fix links clashing

---

Anytype.xcodeproj/project.pbxproj
Anytype.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

https://github.com/scenee/FloatingPanel/issues/635

IOS-2916 Update FloatingPanel to compile in XCode 16.0 beta

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Models/Documents/Document/BaseDocument.swift
Anytype/Sources/Models/Relations/RelationsBuilder.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetSwipeActionView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetRow.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetShowAllView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Common/Content/Subviews/ListWidgetCompactRow.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Common/Content/Subviews/ListWidgetRow.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Common/Content/Subviews/ListWidgetRowModel+ObjectDetails.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Common/Content/Subviews/ListWidgetRowModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Common/ListWidgetViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/View/SetObjectViewWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetDI.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocument.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocumentProtocol.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Models/SetContentViewDataBuilder.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

https://github.com/anyproto/anytype-swift/assets/2483784/6294b7ff-b355-4187-88d1-c35e18d17bdd

iOS-3019 Gallery widget | add cover

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/Analytics/SentryConstants.swift
Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/NonFatalAlertConfigurator/NonFatalLoggerHandler.swift
Anytype/Sources/CoreLayer/Sentry/SentryNonFatalLogger.swift
Anytype/Sources/ServiceLayer/StoreKitService/StoreKitService.swift
Modules/AnytypeCore/AnytypeCore/Logging/ErrorDomain.swift
Modules/AnytypeCore/AnytypeCore/Utils/Asserts.swift
Modules/Logger/Sources/Logger/Assertation/AssertionLogger.swift

IOS-3023 Add tags to payment errors

---

Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/ChangeTypeAccessoryView/ChangeTypeAccessoryView.swift

IOS-2459 Fix done button width

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/EqualFitWidthHStack.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/HomeEditButtonStyle.swift

IOS-3046 Widgets | Add button

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Models/Extensions/DataviewType+Extensions.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/View/SetObjectViewWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/View/SetUnsupportedView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsViewModel.swift

https://github.com/anyproto/anytype-swift/assets/2483784/cc7b3e8b-6705-493d-9d9d-dee01bea80d0

IOS-3042 Set & Widgets | Add unsupported view alert

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/OwnershipView/MembershipExternalPaymentMethod+NoticeTitle.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/OwnershipView/MembershipOwnerInfoSheetView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/OwnershipView/MembershipOwnerInfoSheetViewModel.swift
Anytype/Sources/PreviewMocks/Mocks/MembershipStatusStorageMock.swift
Anytype/Sources/ServiceLayer/MembershipTierInfoProvider/MembershipMetadataProvider.swift
Anytype/Sources/ServiceLayer/MembershipTierInfoProvider/MembershipTierOwningState.swift

IOS-2961 Add Users Notice text for different platforms

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchCell.swift

https://github.com/anyproto/anytype-swift/assets/6065952/ad369166-4908-4c9b-8b4d-97da3ca80555

iOS-3055 Add visual indicator when objects have some connections before having to swipe left

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/LinkWidgetViewContainer.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/WidgetContainerWithEmptyState.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/WidgetEmptyView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Common/Content/ListWidgetContentView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Common/ListWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Common/ListWidgetViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Tree/Common/TreeWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/View/SetObjectViewWidgetSubmoduleView.swift

iOS-3041 Widget | Change empty state

---

Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/AudioBlockContentConfiguration.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/AudioBlockContentView.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/AudioBlockPlayerDelegate.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/AudioBlockViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/Audioplayer/AnytypeAudioPlayerProtocol.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/Audioplayer/AnytypeSharedAudioplayer.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/Views/AudioPlayerView.swift

https://github.com/anyproto/anytype-swift/assets/6065952/94a6e85f-4f8f-4e46-9ba5-56e0044dfc5b

iOS-2254 Stop playing music when out from the page

---

Anytype/Sources/PresentationLayer/Common/UIKit/BottomSheets/ColorView/ColorView.swift

https://github.com/anyproto/anytype-swift/assets/6065952/2d501e38-0791-46d4-8999-3a7c6e13a403

iOS-973 Synchronize text / background color with text selection

---

Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift

https://github.com/anyproto/anytype-swift/assets/6065952/d01e28ec-d1c3-4126-af26-9b0a9dabeb6e

iOS-2996 Open Set/Collection from widget with selected active view

---

Anytype.xcodeproj/project.pbxproj
Anytype.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Base/Configuration/EditorContentView.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Code/CodeBlockView.swift

First block:
before: `~235 ms`
after: `~ 35 ms`
Folowing blocks:
before: `~235 ms`
after: `~ 3 ms`
Aslo I deleted double-update for the all blocks on init ✨

iOS-3065 Improve code block performance

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/EditorFlow/EditorCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

https://github.com/anyproto/anytype-swift/assets/2483784/524b734b-4b3e-4879-9623-6f59c622675d

IOS-3088 Discussion | Add empty module and coordinator

---

Anytype/Sources/PresentationLayer/Flows/InitialCoordinator/InitialCoordinatorView.swift

Update text copy in crash view

---

Anytype/Sources/PresentationLayer/Modules/Discussion/Input/DiscusionInput.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Input/DiscussionTextView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Input/DiscussionTextViewCoordinator.swift

https://github.com/anyproto/anytype-swift/assets/2483784/51e5c2bd-c0a5-46ec-b4e0-385364070eed

iOS-3099 Discussions | add default styles & resize

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/Discussion/Input/DiscussionAttributes.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Input/DiscussionTextView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Input/DiscussionTextViewCoordinator.swift

https://github.com/anyproto/anytype-swift/assets/2483784/61d68273-61cc-4634-a8e3-2ab2595cf27d

iOS-3118 Discussions | support inline markdown

---

Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/DataView/DataViewBlockViewModel.swift

Ios-3128 Fix broken inline set in editor

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/SwiftUI/SyncStatus/Model/SyncStatusInfoExtension.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/SyncStatus/SyncStatusInfoView.swift
Anytype/Sources/PreviewMocks/MockView.swift
Anytype/Sources/PreviewMocks/Mocks/SyncStatusStorageMock.swift

https://github.com/anyproto/anytype-swift/assets/6589348/8a15f326-dd98-418a-92d9-21a08d6079de

IOS-3069 Support preview mock

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/SwiftUI/SyncStatus/Model/Optional+SyncStatusInfo.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/SyncStatus/Model/SyncStatusInfoExtension.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/SyncStatus/SyncStatusInfoNetworkIcon.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/SyncStatus/SyncStatusInfoView.swift

https://github.com/anyproto/anytype-swift/assets/6589348/8419b936-a3fc-4725-b2c6-9f53760bb488

IOS-3069 Add sync status loading animation

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/Discussion/Container/DiscussionSpacingContainer.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Input/DiscusionInput.swift

This is not interactively dismiss mode. Only when start and end edit text view
https://github.com/user-attachments/assets/f0d878f9-e71d-45bb-855b-3cc29a132e5f

iOS3126 Discussion | support navigation height in bottom spacing

---

Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/Date/SetFiltersDateRowView.swift

https://github.com/user-attachments/assets/1342c8b5-ecb2-4f73-8931-10c8744bca9a

iOS-3127 Fix exact date filter in Sets

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/EditorFlow/EditorCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Input/DiscusionInput.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift

https://github.com/user-attachments/assets/b3ca1b67-7eb7-469b-b9b6-bcc3b07ee9ac

IOS-3147 Discussions | Add open screen for link to action (without action implementation)

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchInteractor.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchViewModel.swift

https://github.com/user-attachments/assets/0a3879a3-bdde-4dfa-b409-7037491b6562

iOS-3150 Widget Source | Add new object button

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchCell.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchDataBuilder.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchDataSection.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchViewModel.swift

https://github.com/user-attachments/assets/892997e6-b33a-4c3c-b266-1c124d8e84a8

iOS-3119 Add highlights to title in global search

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageBlock.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionRow.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViewModel.swift

Show text blocks:
https://github.com/user-attachments/assets/ae134b5f-a297-4ab5-833d-b4bf9e0257de

IOS-3177 Discussion | Open document as discussion (only for test)

---

Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscusionInput.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionTextView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionTextViewCoordinator.swift

https://github.com/user-attachments/assets/0be72dbc-c684-48ba-9720-15216a10f947

iOS-3178 Discussion |  send message for document

---

Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageBlock.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageView.swift

https://github.com/user-attachments/assets/9a069872-d8ad-4cf7-b03a-519e8f24b39b

iOS-3174 Discussions | Add simple message design

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/DiscussionScrollView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageView.swift

This is easy implementation for current MVP. I think a lot of logic with scrollview will be changed, because pagination it will be difficult
https://github.com/user-attachments/assets/fba6e87c-25f1-4cd5-82c9-58a9de6dee55

IOS-3182 Discussion | Add scroll to bottom item after update

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Alerts/Bottom/BottomAlertButtonView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/AsyncStandardButton.swift
Anytype/Sources/PresentationLayer/Debug/DebugMenuView.swift
Anytype/Sources/PresentationLayer/Flows/HomeFlow/Views/MembershipNameFinalization/MembershipNameFinalizationView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetView.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipEmailActionView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceJoin/SpaceJoinView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/InviteLinkView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceShareParticipantView.swift

Now it is the same API as StandardButton

IOS-2829 remove text arg name from AsyncStandardButton

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDataSection.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryViewModel.swift
Modules/Services/Sources/Models/VersionHistory.swift
Modules/Services/Sources/Services/HistoryVersionsService/HistoryVersionsService.swift
Modules/Services/Sources/ServicesDI.swift

https://github.com/user-attachments/assets/904f3ff4-6c56-4e4e-b831-ea198c28b862

iOS-3161 Version history | Plain version history rows

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Reaction/MessageReactionAddView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Reaction/MessageReactionList.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Reaction/MessageReactionModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Reaction/MessageReactionView.swift
Anytype/Sources/PresentationLayer/Modules/MessageReactionPicker/MessageReactionPickerView.swift
Anytype/Sources/PresentationLayer/Modules/MessageReactionPicker/MessageReactionPickerViewModel.swift

https://github.com/user-attachments/assets/8922d34f-ebac-4f42-bab7-344baed7b1c8

IOS-3176 Chat | Show reactions for message

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDataGroup.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDataSection.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDateFormatter.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryGroupContainer.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryViewModel.swift

iOS-3217 Version history | Grouped version history screen

---

Anytype/Sources/Analytics/SentryConstants.swift
Anytype/Sources/CoreLayer/Sentry/SentryConfiguratior.swift
Anytype/Sources/PresentationLayer/Debug/DebugMenuView.swift
Modules/AnytypeCore/AnytypeCore/Utils/BuildTypeProvider.swift
Modules/Services/Sources/Services/Membership/MembershipModelBuilder.swift

Fingers crossed, it will work 🤞

iOS-3184 | Add BuildTypeProvider

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryGroupContainer.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryViewModel.swift

https://github.com/user-attachments/assets/e61a638d-2fd6-4146-8220-dc45a82f070d

iOS-3230 Version history | Collapse / expand group

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Filled/Subviews/Icon/ObjectHeaderIconView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/IconsGroupView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryGroupContainer.swift

iOS-3235 Version history | Move grouped icons to separate view + update design

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Helpers/Extensions/AttributedString+Extensions.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscusionInput.swift

https://github.com/user-attachments/assets/3e2b90bb-38ab-4b0e-8150-057f19ac62eb

IOS-3234 Message Input | Add placeholder for empty state

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/Models/IdentifiableExtension.swift
Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinatorModel.swift
Modules/DeepLinks/Sources/DeepLinks/Array+Search.swift
Modules/DeepLinks/Sources/DeepLinks/DeepLink.swift
Modules/DeepLinks/Sources/DeepLinks/DeepLinkParser.swift

https://github.com/user-attachments/assets/fef51581-46ff-4225-96a6-625c761df167

IOS-3209 Support membership deeplink

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/FrameworkExtensions/SwiftUI/View+CornerRadius.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessageLinkInputViewContainer.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessageLinkObjectView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessageLinkObjectViewStyle.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessageLinkViewContainer.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageViewModel.swift

https://github.com/user-attachments/assets/48f1ba6d-d017-4333-9360-5ba6113f47d1

IOS-3175 Message | Add linked objects

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Container/RelationListContainerView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationListView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationListViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Select/SelectRelationListView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Select/SelectRelationListViewModel.swift

iOS-3210 Remake to task id on view in Relations

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionKeys+Menu.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionTextViewCoordinator.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/NSAttributedString+MessageExtensions.swift

https://github.com/user-attachments/assets/423b5519-a735-483a-be75-30d98fe2db88

IOS-3189 Message input | Add style menu

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Coordinator/VersionHistoryCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Object/ObjectVersionView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Object/ObjectVersionViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDataGroup.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryViewModel.swift

iOS-3251 Version history | Add icon and date time title

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Object/ObjectVersionViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDataBuilder.swift

iOS-3263 Version history | Join versions in one minute from one author

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchCell.swift

iOS-3273 Fix global search grid

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDateFormatter.swift

Remove current year from the dates

iOS-3275 Version history | Update date formats

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/StandardButton.swift
Anytype/Sources/PresentationLayer/Modules/SpaceJoin/SpaceJoinView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceJoin/SpaceJoinViewModel.swift

https://github.com/user-attachments/assets/9e1883d8-f5b7-469b-ada7-261d0c80ac9a

IOS-3252 Space Join Alert | add placeholder

---

Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Models/SetContentViewDataBuilder.swift
Modules/Services/Sources/Models/ObjectType.swift

https://github.com/user-attachments/assets/f184b38f-3076-4002-9774-7c4d71e40050

iOS-3255 Support cover in Set by image

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorOutput.swift
Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/SetObjectCreationSettingsCoordinator.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/TemplatesCoordinator.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/Page/EditorPageModuleOutput.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Coordinator/VersionHistoryCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Object/ObjectVersionViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift

Show through swiftui toast where its possible 
https://github.com/user-attachments/assets/135270f7-77b3-4ed1-90b5-82256bd2f316

iOS-3297 Version history | Add restoration toast

---

Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/Dataview/SetObjectCreationSettingsInteractor.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/DataView/DataViewBlockViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Creation/SetObjectCreationHelper.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/Builders/SetPermissionsBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocument.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Subscriptions/Group/SetGroupSubscriptionDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Subscriptions/Set/SetSubscriptionData.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SetViewSettings/SetViewSettingsList/SetViewSettingsListModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/ViewPicker/SetViewPickerViewModel.swift

https://sentry.anytype.io/organizations/anytype/issues/41854/?project=6&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d

iOS-3145 Add filteredSetOf property to fix source filter

---

Anytype/Sources/Design system/Colors/CoverColor.swift
Anytype/Sources/Models/Documents/Document/Cover/BackgroundType.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift

Use wallpaper color for card background
Add settings and space creation
https://github.com/user-attachments/assets/2e71e24c-2638-49f1-9ce9-dae54e8b9030

iOS-3317 space hub prototype

---

Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionService/BlockActionService.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionService/BlockActionServiceProtocol.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/KeyboardActionHandler/KeyboardActionHandler.swift
AnytypeTests/Markdown/Mocks/BlockActionServiceMock.swift

https://github.com/user-attachments/assets/c37f72fc-acfd-429d-99e8-cd8fa79c1563

iOS-3156 Attempt to fix split error - set text before split

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/Block/SimpleTableBlockView+UICollectionViewDelegate.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/Block/SimpleTableStateManager.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageBlocksStateManager.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageController+UICollectionViewDelegate.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageController.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Utils/EditorNavigationBarHelper/EditorNavigationBarHelper.swift

https://github.com/user-attachments/assets/b59de4b6-0173-4cb1-9cd5-64fdf15aa6f0

iOS-3076 Add Select all blocks button

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/ServerConfiguration/ServerConfigurationViewModel.swift
Anytype/Sources/PresentationLayer/Modules/ServerConfiguration/ServerLocalConfigurationAlert.swift

iOS-3325 Update local config buttons text / style

---

Anytype/Resources/Assets.xcassets/DesignSystem/x32/Island/Vault.imageset/Contents.json
Anytype/Resources/Assets.xcassets/DesignSystem/x32/Island/add.imageset/Contents.json
Anytype/Resources/Assets.xcassets/DesignSystem/x32/Island/back.imageset/Contents.json
Anytype/Resources/Assets.xcassets/DesignSystem/x32/Island/search.imageset/Contents.json
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift

Ios-3322 Space hub | blur in the background of spaces

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/SyncStatus/Model/SyncStatusInfoExtension.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/SyncStatus/SyncStatusInfoView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/SyncStatus/SyncStatusInfoViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/NavigationBar/SyncStatus/SyncStatusData.swift
Anytype/Sources/Shared/SharedContants.swift

https://github.com/user-attachments/assets/cdca4ef4-a4f1-4223-a3d4-1a8be44159c7

IOS-3339 Support networkNeedsUpdate sync status

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageBlocksStateManager.swift

https://github.com/user-attachments/assets/5e4bfdfa-d893-4198-9cdc-0fac016559a3

iOS-3334 Add object to collection when dnd between link and collection

---

Anytype/Sources/PresentationLayer/Notifications/NotificationCoordinatorView.swift
Anytype/Sources/PresentationLayer/Notifications/NotificationCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Notifications/Specific/ParticipantRemove/ParticipantRemoveNotificationView.swift
Anytype/Sources/PresentationLayer/Notifications/Specific/ParticipantRemove/ParticipantRemoveNotificationViewModel.swift

iOS-3330 Remove delete space button from the notif

---

AnyTypeTests/Markdown/Mocks/UserDefaultsStorageMock.swift
AnyTypeTests/Services/CustomSpaceOrderBuilderTests.swift
Anytype.xcodeproj/project.pbxproj
Anytype/Generated/ImageAssets.swift
Anytype/Resources/Assets.xcassets/DesignSystem/x24/Blur.imageset/Contents.json
Anytype/Resources/Assets.xcassets/DesignSystem/x24/Blur.imageset/blur.pdf
Anytype/Sources/Models/Documents/Document/Cover/SpaceWallpaperType.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/DashboardWallpaper.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift
Anytype/Sources/PresentationLayer/Settings/Wallpaper/WallpaperColorsGridView.swift
Anytype/Sources/PresentationLayer/Settings/Wallpaper/WallpaperPickerView.swift
Anytype/Sources/PresentationLayer/Settings/Wallpaper/WallpaperPickerViewModel.swift
Anytype/Sources/PreviewMocks/Mocks/WorkspacesStorageMock.swift
Anytype/Sources/ServiceLayer/SpaceStorage/Models/SpaceViewMock.swift
Anytype/Sources/Utilities/UserDefaults/UserDefaultsStorage.swift

https://github.com/user-attachments/assets/7b2e5752-9d14-400b-9570-92d632e15089

iOS-3356 SpaceHub| Support blurred icon background

---

Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Reaction/MessageReactionList.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Reaction/MessageReactionView.swift
Anytype/Sources/PresentationLayer/Modules/MessageReactionPicker/MessageReactionPickerView.swift
Anytype/Sources/PresentationLayer/Modules/MessageReactionPicker/MessageReactionPickerViewModel.swift
Modules/Services/Sources/Services/Chat/ChatService.swift

https://github.com/user-attachments/assets/f5526223-5f17-44a4-a0b6-b1b1dd4aeeb2

iOS-3365 Chat Message | integrate reactions API (chat branch)

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageViewModel.swift
Anytype/Sources/ServiceLayer/ServicesDI.swift
Anytype/Sources/ServiceLayer/Subscriptions/ObjectIdsSubscriptionService.swift
Modules/Services/Sources/Models/ChatModels.swift

https://github.com/user-attachments/assets/b6d1510a-4195-43aa-9a67-5a84f3ea6e23

iOS-3369 Chat Attachments | integrate api and subscription

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/Models/Documents/Document/BaseDocumentProtocol+Block.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageBlocksStateManager.swift

iOS-3377 Restrict move to the same object

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentViewModel.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/Subscription/AllContentSubscriptionService.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/Legacy_ObjectTypeSearchViewModel/MultiselectObjectTypesSearchViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/ObjectsSearchViewModel/ObjectsSearchViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/ObjectsSearchViewModel/RowView/SearchObjectRowView+Init.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/ObjectsSearchViewModel/RowView/SearchObjectRowView.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchViewModel.swift
Anytype/Sources/ServiceLayer/ServicesDI.swift

https://github.com/user-attachments/assets/1d93c50b-8748-40a9-901f-71c3470d0341

iOS-3411 All Content | Impl AllContentSubscriptionService for all objects

---

Anytype/Resources/SystemColors.xcassets/Widget/card.colorset/Contents.json
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetSwipeActionView.swift

Old with widget background alpha. Look at the plus
https://github.com/user-attachments/assets/07773c70-f9d3-402e-a894-f4152f54babf
Fixed
https://github.com/user-attachments/assets/f853b212-4fa1-4750-91cc-8c8f3ce9aa9a

IOS-3412 Widget | Change background & add mask

---

Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentState.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentViewModel.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/Subscription/AllContentSubscriptionService.swift
Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift
Anytype/Sources/ServiceLayer/Object/Search/SearchServiceProtocol.swift
Modules/Services/Sources/Services/SearchService/SearchHelper.swift

Add search all method to avoid search on each tab, but maybe will be changed in the future
https://github.com/user-attachments/assets/7432bec5-a148-4738-9344-5e3b3b91c819

iOS-3415 All Content | Add search bar with `searchAll` method

---

Anytype/Sources/PresentationLayer/Flows/CreateWidgetFlow/CreateWidgetCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/CreateWidgetFlow/CreateWidgetCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetChangeSourceSearchView.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchView.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/Internal/WidgetSourceSearchChangeInternalViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/Internal/WidgetSourceSearchSelectInternalViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/Models/WidgetChangeSourceSearchModuleModel.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchInternalViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchViewModel.swift

https://github.com/user-attachments/assets/034243ab-2777-42a5-8f8b-dab89cddb4a9

IOS-3292 Widget | open new source

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Design system/Fonts/Text+Style.swift
Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/DiscussionEmptyState/DiscussionEmptyStateView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/DiscussionEmptyState/DiscussionEmptyStateViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscusionInput.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Object/ObjectIconPicker.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Object/ObjectIconPickerViewModel.swift
Modules/Services/Sources/Models/Details/BundledDetails.swift

https://github.com/user-attachments/assets/e9ba1da5-07df-445d-a3d4-7e2593c7139e

iOS-3173 Chat | Add empty state

---

Anytype/Sources/PresentationLayer/Settings/Wallpaper/WallpaperColorsGridView.swift
Anytype/Sources/PresentationLayer/Settings/Wallpaper/WallpaperPickerView.swift

IOS-3410 Highlight currently selected wallpaper

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentMode.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentState.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentViewModel.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/Subscription/AllContentSubscriptionService.swift
Modules/Services/Sources/Services/SearchService/SearchHelper.swift

https://github.com/user-attachments/assets/699c297f-5303-4dfd-a1ea-d2ffacbc0a6e

iOS-3419 All Content | Add unlinked mode

---

Anytype/Sources/PresentationLayer/Flows/EditorFlow/EditorCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentViewModel.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/Coordinator/AllContentCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/Coordinator/AllContentCoordinatorViewModel.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

https://github.com/user-attachments/assets/6bee3c0b-fdab-499e-9ae4-3af9e2bfcaf1

iOS-3420 All Content | Open object

---

Anytype/Generated/Error+Localization.swift
Anytype/GeneratorConfig/Templates/error-localization.stencil
Anytype/Sources/FrameworkExtensions/CoreGraphics+Hash.swift
Anytype/Sources/Helpers/Extensions/CGSizeExtension.swift
Anytype/Sources/Models/Extensions/MembershipServiceError+Localisation.swift
Anytype/Sources/Models/Extensions/ObjectActionsServiceError+Localization.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/SyncStatus/Model/Anytype_Event.Space.SyncError+Localizable.swift
Anytype/Sources/PresentationLayer/Debug/DebugMenuView.swift
Anytype/Sources/PresentationLayer/FileDownloading flow/FileLoader/FileLoader.swift
Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinatorModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipStatusExtension.swift
Anytype/Sources/PresentationLayer/Settings/Appearance/UIUserInterfaceStyle+Settings.swift
Anytype/Sources/PreviewMocks/Mocks/WorkspacesStorageMock.swift
Anytype/Sources/ServiceLayer/Auth/AccountDeleteError+Localize.swift
Anytype/Sources/ServiceLayer/Auth/AuthServiceError+Localize.swift
Anytype/Sources/ServiceLayer/Auth/CreateAccountServiceError.swift
Anytype/Sources/ServiceLayer/Auth/WalletRecoveryError+Localize.swift
Anytype/Sources/ServiceLayer/KeychainStore/Internals/KeychainError.swift

IOS-3344 Fix new xcode warnings

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Builders/FilterModels/SlashMenuComparator.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Builders/FilterModels/SlashMenuItemFilterMatch.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/Actions/SlashActionMedia.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashAction.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashMenuItemDisplayData.swift

https://github.com/user-attachments/assets/ba8b577d-faec-49ee-913f-d30b7f84ea99

iOS-3414 Rename /Picture to /Image in slash menu + add titleSynonyms

---

Modules/Services/Sources/Models/Block/BlockRestrictions/HighlightedBlockRestrictions.swift

https://github.com/user-attachments/assets/edec3e28-35dd-44f6-9df1-c5c80b49f02a

iOS-3364 Fix highlightedBlock restrictions

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscusionInput.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionAttributes.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionInputConverter.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionTextView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionTextViewCoordinator.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageViewModel.swift
Modules/Services/Sources/Models/Block/BlockModels.swift
Modules/Services/Sources/Models/ChatModels.swift

https://github.com/user-attachments/assets/c8cef4a3-2f99-4f24-aa80-ab0dc6caa0cc

iOS-3191 Message | Support basic markups (to chat)

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/FrameworkExtensions/SwiftUI/View+LegacyAdopt.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentMode.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentSettingsMenu.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentSort.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentViewModel.swift

https://github.com/user-attachments/assets/7f294f40-cde4-4a65-b67f-9b57a632a994

iOS-3439 All Content | Add new settings menu | Sorts

---

Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentSort.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentViewModel.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/Subscription/AllContentSubscriptionService.swift

https://github.com/user-attachments/assets/09394888-7799-4fca-819e-fe3f20d7b7e5

iOS-3431 All Content | Add grouping by date for date sorting

---

Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentSort.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentType.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentViewModel.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/Subscription/AllContentSubscriptionService.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift
Modules/Services/Sources/Models/Details/BundledRelationValueProvider+CustomFields.swift
Modules/Services/Sources/Models/Details/ObjectIconBuilder.swift
Modules/Services/Sources/Models/Extensions/DetailsLayout+Visible.swift

https://github.com/user-attachments/assets/342c2b6f-6627-499d-9e7e-434726cd81f2

iOS-3442 All Content | Add separate tab Media + fix filters

---

Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

https://github.com/user-attachments/assets/5759bc5e-5429-444b-aedd-6e231f40738d

IOS-3368 Add swipe to search

---

AnyTypeTests/Formatters/AnytypeRelativeDateTimeFormatterTests.swift
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Helpers/Formatters/AnytypeRelativeDateTimeFormatter.swift

https://github.com/user-attachments/assets/fff4857c-0d75-4ce2-96b0-56500c024abc

iOS-3431 All Content | Update relative date formatter

---

Anytype.xcodeproj/project.pbxproj

Fix nighly dev build. Version 57 is already released in Testflight

IOS-3446 Bump build number

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentMode.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentSettingsMenu.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentView.swift

https://github.com/user-attachments/assets/b5a50783-06e1-4148-bba1-73b6b00f6695

iOS-3454 All Content | Add new settings menu | Unlinked

---

Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/DashboardWallpaper.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift

https://github.com/user-attachments/assets/31e22574-32de-4225-8b1c-90f14b687ee7

IOS-3453 Add parallax to space hub

---

Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/UIKit/Pickers/FilePicker/CommonViews+Pickers+File+UIKit.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentSettingsMenu.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouterProtocol.swift

iOS-3478 All Content | Settings menu design update (left sided checks)

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Analytics/AnalyticsConstants.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelView.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/SpaceSwitcherTip.swift

IOS-3448 Add space switcher tip

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/List/ListSectionHeaderView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/List/SectionHeaderView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentView.swift

Add separator for header only if rightContent is exist

iOS-3483 All Content | List design updates

---

AnyTypeTests/Markdown/Mocks/UserDefaultsStorageMock.swift
Anytype/Sources/PresentationLayer/Debug/DebugMenuView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/Utilities/UserDefaults/UserDefaultsStorage.swift

Restore state for widget screen + fixed restoration for editor screens

iOS-3480 Store and restore app state upon relaunch

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/DiscussionReadOnlyBottomView.swift

iOS-3403 Discussion | read-only text (to chat)

---

Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentType.swift

We already have bookmarks in separate tab

iOS-3486 All Content | Exclude Bookmarks from Objects tab

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Analytics/AnalyticsConstants.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/SpaceIconView/SpaceIconView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift
Modules/Services/Sources/Models/Details/ObjectIconBuilder.swift

https://github.com/user-attachments/assets/0a3a5aeb-a6bf-46de-8b1e-df23d820d460

IOS-3498 Support debug actions for spaces in loading state

---

Anytype/Sources/PresentationLayer/Auth/JoinFlow/JoinFlowView.swift

https://github.com/user-attachments/assets/369e3ae0-44e6-4490-8c97-8c63d8d900b5

iOS-3379 iOS 18 | Fix back navigation button after create account

---

Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchViewModel.swift

https://github.com/user-attachments/assets/bb7a5c5a-c265-4fc8-952b-d68a5ff41543

IOS-3507 Update space switcher design

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionAttributes.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionKeys+Menu.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionTextViewCoordinator.swift

iOS-3249 Chat style menu | change icon (to chat)

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentViewModel.swift

iOS-3504 All Content | Add empty states

---

AnytypeShareExtension/ShareViewController.swift

Fix for sharing extension iOS 18

IOS-3489 Use public api for url open

---

Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscusionInput.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionInputConverter.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionTextView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionTextViewCoordinator.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageViewModel.swift

https://github.com/user-attachments/assets/bb3d3e7e-e264-457c-8cb4-9c7f85f6c99f

IOS-3190 Chat | Add link to markup (to chat)

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/LinkToObject/LinkToObjectSearchViewModel.swift
Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/DiscussionCoordinator/DiscussionCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessageLinkInputViewContainer.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessageLinkViewContainer.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageViewModel.swift

https://github.com/user-attachments/assets/7d498776-5899-41da-84e1-3d3179b17c97

IOS-3521 Chat | Open objects in message (to chat)

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/Modifiers/ObjectIconBackgroundColorModifier.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/PlaceholderIconView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/ProfileIconView.swift

Agreed with Yura
https://github.com/user-attachments/assets/270b8d83-1524-4bd1-979e-ac3257ef98af

iOS-3499 All Content | Change icons background color

---

Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Debug/Flows/InternalDebug/DebugMenuView.swift
Anytype/Sources/PresentationLayer/Debug/Flows/InternalDebug/DebugMenuViewModel.swift
Anytype/Sources/PresentationLayer/Debug/Flows/PublicDebug/PublicDebugMenuView.swift
Anytype/Sources/PresentationLayer/Debug/Flows/PublicDebug/PublicDebugMenuViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/TIps/SpaceHubTip/SpaceHubTipView.swift
Modules/Services/Sources/Services/Debug/DebugService.swift

https://github.com/user-attachments/assets/26450b7a-12b6-4766-acd0-141d56018e6d

IOS-3524 Run profiler on app start

---

Anytype/Sources/ServiceLayer/ParticipantSpacesStorage/ParticipantSpacesStorage.swift

Provide custom subscription key

IOS-3487 Fix shared spaces limit subscription

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Assets.swift
Anytype/Generated/Color+Assets.swift
Anytype/Generated/Color+Info.swift
Anytype/Generated/UIColor+Assets.swift
Anytype/Resources/SystemColors.xcassets/Additional/messageInputShadow.colorset/Contents.json
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Models/DiscussionLinkedObject.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Models/FileData+DiscussionType.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Models/MediaFile.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscusionInput.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessageLink+RemoveButtom.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessageLinkImageView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessageLinkInputViewContainer.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessageLinkLocalImageView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessageLinkObjectView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessageLinkObjectViewStyle.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessageLinkedUploadedObject.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/LinkObject/MessgeLinkedLocalFile.swift
Anytype/Sources/PresentationLayer/Modules/ShareOptions/ShareOptionsInteractor.swift
Anytype/Sources/ServiceLayer/Block/File/FileActionsService.swift
Anytype/Sources/ServiceLayer/Block/File/FileActionsServiceProtocol.swift
Anytype/Sources/ServiceLayer/DiscussionChatActionService/DiscussionChatActionService.swift
Anytype/Sources/ServiceLayer/ServicesDI.swift

https://github.com/user-attachments/assets/4f3a00a6-625d-45fd-9d84-879b5b29ca23

iOS-3195 Chat | add attachments & image preview for input (to chat branch)

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift

https://github.com/user-attachments/assets/51126dfa-fc71-42f8-b34f-ebfac413d077

IOS-3525 Update drag preview style

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/Modifiers/ObjectIconCornerRadiusModifier.swift
Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/Components/SpaceRowView.swift

IOS-3532 Fix selected space corner radius

---

.github/workflows/branch_build.yaml
.github/workflows/dev_build.yaml
fastlane/Fastfile
fastlane/FastfileDeploy
fastlane/FastlaneBranchBuild
fastlane/Tools

iOS-3539 CI | Add version number and add comment for branch build

---

Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/SetObjectCreationSettingsCoordinator.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationData.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsView.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsView.swift

https://github.com/user-attachments/assets/e09849cc-eff2-4953-82c1-4d05c7205afc

iOS-3550 Move create object popup in Sets / Collections to anytypesheet

---

Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/SetObjectCreationSettingsCoordinator.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationData.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsView.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsView.swift

https://github.com/user-attachments/assets/36ce5bdc-3daf-476a-90f7-881c95af63e5

iOS-3550 Move create object popup in Sets / Collections to anytypesheet -> chat

---

Anytype/Sources/PresentationLayer/Auth/Auth/AuthBackgroundView.swift
Anytype/Sources/PresentationLayer/Auth/JoinFlow/KeyPhraseMoreInfoView/KeyPhraseMoreInfoView.swift

There is no background under the button

iOS-3547 Fix Skip button and Key more info

---

Anytype/Sources/PresentationLayer/Auth/Auth/AuthBackgroundView.swift
Anytype/Sources/PresentationLayer/Auth/JoinFlow/KeyPhraseMoreInfoView/KeyPhraseMoreInfoView.swift

There is no background under the button

iOS-3547 Fix Skip button and Key more info -> chat branch

---

Anytype/Sources/ServiceLayer/AccountParticipantsStorage/AccountParticipantsStorage.swift
Anytype/Sources/ServiceLayer/AccountParticipantsStorage/AcountParticipantSubscriptionBuilder.swift
Anytype/Sources/ServiceLayer/ParticipantSpacesStorage/ParticipantSpacesStorage.swift
Modules/Services/Sources/Services/SearchService/SearchHelper.swift

Use search by identity instead of identityProfileLink
Cleanup subscriptionService upon stopping subscription

Ios-3556 participant subscriptions refining

---

Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Services/ChatMessagesStorage.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageReplyView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageViewData.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageViewModel.swift
Modules/AnytypeCore/AnytypeCore/Utils/AsyncHelpers.swift
Modules/Services/Sources/Services/Chat/ChatService.swift

iOS-3559 Chat | show reply (to chat branch)

---

Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
Anytype/Sources/Models/ObjectPermissions/ObjectPermissions.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentType.swift
Anytype/Sources/PresentationLayer/Modules/ShareOptions/ShareContentModels.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Layout/ObjectLayoutPicker.swift
Modules/Services/Sources/Models/Extensions/DetailsLayout+Visible.swift

No business logic have changed 
**Before:**
**After:**

Ios-3518 Refactoring of DetailsLayout+Visible

---

Anytype/Generated/ImageAssets.swift
Anytype/Resources/Assets.xcassets/DesignSystem/EmptyIcon/date.imageset/Contents.json
Anytype/Resources/Assets.xcassets/DesignSystem/EmptyIcon/date.imageset/date.pdf
Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/EmptyObjectIconView.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Models/Details/ObjectIcon.swift
Modules/Services/Sources/Models/Extensions/DetailsLayout+Visible.swift

https://github.com/user-attachments/assets/13b262f3-be79-4a4f-9175-5965f8314b0f

iOS-3371 Date object | Add date object to visible layout

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Input/DiscussionInputReplyView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageTextBuilder.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageViewModel.swift
Anytype/Sources/ServiceLayer/DiscussionChatActionService/DiscussionChatActionService.swift

https://github.com/user-attachments/assets/61a7d6e2-d6c5-4fba-a9e1-949229db5e58

iOS3197 Message | add reply

---

Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/DiscussionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Services/ChatMessagesStorage.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/DiscussionCollectionView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/DiscussionCollectionViewScrollProxy.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageViewModel.swift
Anytype/Sources/ServiceLayer/DiscussionChatActionService/DiscussionChatActionService.swift
Modules/Services/Sources/Services/Chat/ChatService.swift

https://github.com/user-attachments/assets/bf78f1e6-f1fe-443f-82a3-4217fd7cfe91

iOS-3560 Chat message | scroll to reply by tap (to chat branch)

---

Anytype/Sources/PresentationLayer/Flows/HomeChatCoordinator/HomeChatCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/HomeChatCoordinator/HomeChatCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsCoordinator/HomeWidgetsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsCoordinator/HomeWidgetsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeTabBar/HomeTabBarCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/HomeTabBar/HomeTabBarCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeTabBar/HomeTabState.swift
Anytype/Sources/PresentationLayer/Modules/HomeTabBar/Subviews/HomeTabBarView.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

https://github.com/user-attachments/assets/3299fd74-3363-4d97-ac9b-0b2f971f68e6

iOS-3592 Chat | Preparing for space-level- chat (to chat)

---

Anytype/Sources/CoreLayer/Navigation/NavigationContext.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DateCalendarView/DateCalendarView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Date/DateRelationCalendarView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Date/DateRelationCalendarViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/AccessoryViewBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionViewController/MentionsViewController.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionViewController/MentionsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionViewController/Models/MentionDisplayData.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouterProtocol.swift

https://github.com/user-attachments/assets/b2077297-76e4-4f4f-ac85-abcfc0d5a71f

iOS-3371 Date as an object | Support select date in mentions

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/OpenFile/OpenFileBlockContentConfiguration.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/OpenFile/OpenFileBlockView.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/OpenFile/OpenFileBlockViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift

https://github.com/user-attachments/assets/3bc27e5c-1e0a-4ee7-910f-63410c0e5b91
https://github.com/user-attachments/assets/e71d3a24-e1b2-40a3-b1e7-5aeb846ef750

IOS-3632 Add open file button

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/DateCalendarView/DateCalendarData.swift
Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ChatHeader.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Date/ObjectCell.swift
Anytype/Sources/PresentationLayer/Modules/Date/ObjectCellData.swift
Anytype/Sources/PresentationLayer/Modules/Date/Subscription/DateRelatedObjectsSubscriptionService.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/NavigationBar/SyncStatus/SwiftUIEditorSyncStatusItem.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetMinimizedHeader.swift
Anytype/Sources/ServiceLayer/ServicesDI.swift
Modules/Services/Sources/Services/RelationListWithValue/RelationListWithValueService.swift
Modules/Services/Sources/ServicesDI.swift

iOS-3373 Date as an object |  Add related objects to Date with fake relations

---

Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentSettingsMenu.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

https://github.com/user-attachments/assets/8029369d-435a-4210-8fe0-e4076e7faad5

iOS-3667 Add dynamic Bin widget to home screen

---

Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ChatHeader.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeView.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/NavigationBar/SyncStatus/EditorBarItemState.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/NavigationBar/SyncStatus/EditorSyncStatusItem.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/NavigationBar/SyncStatus/SwiftUIEditorSyncStatusItem.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetMinimizedHeader.swift

https://github.com/user-attachments/assets/75be90a1-c230-4e93-a0a3-800798fa4ffb

Ios-3652 Type as object | Added navbar with sync status

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/TemplatePreview/TemplatePreview.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/TemplatePreview/TemplatePreviewModel.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeView.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/Dataview/MockSetObjectCreationSettingsInteractor.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/Dataview/SetObjectCreationSettingsInteractor.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsViewModel.swift
Modules/Services/Sources/Models/SubscriptionData/BundledRelationKey+CommonKeys.swift

IOS-3652 Add support for description badge

---

Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/TemplatesCoordinator.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Picker/TemplatePickerView.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Picker/TemplatePickerViewModel.swift

https://github.com/user-attachments/assets/692db3a5-1223-431b-a7f4-6283722048c2

IOS-3652 Support template editing for types

---

Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Error+Localization.swift
Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/MiddlewareMerticsConfigurator.swift
Libraryfile
Modules/ProtobufMessages/Sources/Generated/commands+invocation.swift
Modules/ProtobufMessages/Sources/Generated/service+invocation.swift
Modules/ProtobufMessages/Sources/Protocol/changes.pb.swift
Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
Modules/ProtobufMessages/Sources/Protocol/events.pb.swift
Modules/ProtobufMessages/Sources/Protocol/models.pb.swift
Modules/Services/Sources/Generated/BundledRelationKey+SystemKeys.swift
Modules/Services/Sources/Generated/BundledRelationKey.swift
Modules/Services/Sources/Generated/BundledRelationsValueProvider.swift
Modules/Services/Sources/Generated/ObjectTypeUniqueKey+Bundled.swift
Modules/Services/Sources/Services/Metrics/MetricsService.swift
Modules/Services/Sources/Services/Process/Process.swift

Also patch version update to `0.33.5`
⚠️  Middle version should be updated

iOS-3695 Patch 0.33.5 | Support new progress bar protocol (without design)

---

Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentType.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeView.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Layout/DetailsLayout+Metadata.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Layout/ObjectLayoutPicker.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Layout/ObjectLayoutPickerViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Layout/ObjectLayoutRow.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSettingBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingRow.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Models/Details/BundledDetails.swift

https://github.com/user-attachments/assets/91df645c-c3b7-459d-8830-536daff1cb81

Ios 3652  Add layout change button

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/StandardButton.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeView.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift

Support standard button with badge style
Add an ability to change type name

Ios-3636 | Type page design updates

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Entities/RelationsSectionBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/ObjectFieldsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift

[Update section building for relations menu](https://github.com/anyproto/anytype-swift/commit/fc4ff43c75538c781d09fefd49306f9f6d263ae9)
[Update relations banner design](https://github.com/anyproto/anytype-swift/commit/4ae56153905152fca3ab043bbbdde66e8d6346bc)

Ios-3636 | Relations related design update

---

Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeView.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/View/TypeDeleteAlert.swift

https://github.com/user-attachments/assets/56a7e092-e59e-4f37-a360-c812bfc5549b

IOS-3652 Add delete type action

---

Anytype/Sources/Models/Relations/Entities/Relation.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Entities/RelationsSectionBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsRelationsData.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsRelationsDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift

https://github.com/user-attachments/assets/d34bf9d6-7307-4c4a-8b8e-583aa7401569

IOS-3652 Updated design of type fields view

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/StandardButtonConfig.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/StandardButtonStyle.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsRelationsData.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsRelationsDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift

https://github.com/user-attachments/assets/62dc245b-6b42-493e-909d-76f7e3952497

Ios-3652 | New possibility to add fields to type

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
Modules/Services/Sources/Services/Relations/RelationsService.swift
Modules/Services/Sources/Services/Relations/RelationsServiceProtocol.swift

https://github.com/user-attachments/assets/a2252cc7-7d92-4295-8679-8f8cfd29fbda

IOS-3652 Add remove relations capabiliy

---

Anytype/Generated/ImageAssets.swift
Anytype/Resources/Assets.xcassets/DesignSystem/x24/Calendar.imageset/Calendar.pdf
Anytype/Resources/Assets.xcassets/DesignSystem/x24/Calendar.imageset/Contents.json
Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift

https://github.com/user-attachments/assets/8fe57dec-47f0-4f3b-b014-5e9df88a92f3

iOS-3737 Date as an object | Add date changing inside Date object

---

Anytype/Sources/PresentationLayer/Flows/ObjectTypeCoordinator/ObjectTypeCoordinator.swift
Anytype/Sources/PresentationLayer/Flows/ObjectTypeCoordinator/ObjectTypeCoordinatorModel.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeView.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/Views/ObjectsList/ObjectTypeObjectsListView.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/Views/ObjectsList/ObjectTypeObjectsListViewModel.swift

https://github.com/user-attachments/assets/723254e3-0b9f-4354-b706-7122aa775f3d

IOS-3652 Added ability to open object from list in type view

---

AnyTypeTests/Formatters/RelativeDateFormatterTests.swift
Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/FrameworkExtensions/Foundation/DateExtension.swift
Anytype/Sources/Helpers/Formatters/DateFormatter+Relation.swift
Anytype/Sources/Models/Relations/RelationsBuilder.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipStatusExtension.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionViewController/MentionsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/List/RelationFilterBuilder.swift

https://github.com/user-attachments/assets/67b1c0f0-440b-493a-8a4d-0bfa65b49339

iOS-3737 Date as an object | Add prev / next days arrows

---

Anytype/Sources/PresentationLayer/Modules/Date/DateModuleState.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Date/Subscription/DateRelatedObjectsSubscriptionService.swift
Modules/Services/Sources/Services/SearchService/SearchHelper.swift

https://github.com/user-attachments/assets/68e967bd-3b5f-4114-b147-1129a946d257

iOS-3740 Date as an object | Add custom sorting

---

Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift

And move to `objectShow` - we don't need to call `objectOpen` for virtual objects

iOS-3745 Date as an object | Filter relations

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/CoreLayer/Navigation/NavigationContext.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/CalendarView/CalendarConfirmationDateView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/CalendarView/CalendarView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DateCalendarView/DateCalendarData.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Date/DateRelationCalendarView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/RelationOptionSettings/RelationOptionSettingsConfiguration.swift
Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/View/LegacySearchView.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Kanban/Column/Settings/SetKanbanColumnSettingsView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/Checkbox/SetFiltersCheckboxView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/Date/SetFiltersDateView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/Selection/List/SetFiltersSelectionView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/Text/SetFiltersTextView.swift

iOS-3759 Date as an object | Add apply button to Calendar view

---

Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/ServiceLayer/MultispaceSubscriptionHelper/MultispaceOneActiveSubscriptionHeloper.swift
Anytype/Sources/ServiceLayer/Object/DefaultObjectCreationService/DefaultObjectCreationService.swift

Fix issues related to cold start of the app from create new object system widget

Ios-3720 Space hub issues

---

Anytype/Sources/Models/Documents/Document/BaseDocument.swift
Anytype/Sources/Models/Relations/ParsedRelations.swift
Anytype/Sources/Models/Relations/RelationsBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Models/SetContentViewDataBuilder.swift

It will come in handy in further relations overhaul

IOS-3636 Updated relations builder API

---

Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessageBuilder.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessagesStorage.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Collection/ChatCollectionView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Collection/ChatCollectionViewCoordinator.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageAuthorMode.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageViewData.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageViewSpacing.swift

Left - Old, Right - New
https://github.com/user-attachments/assets/89006837-6eb5-4eb5-9375-9af3b27f8bfb

IOS-3397 Chat | Add message group

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/View+DragIndicator.swift
Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Anytype/Sources/PresentationLayer/RelationValueFlow/RelationValueCoordinator/RelationValueCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/RelationValueFlow/RelationValueCoordinator/RelationValueProcessingService.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorViewModel.swift

Update empty state + update text

iOS-3670 Date as an object | Design review

---

Anytype/Sources/PresentationLayer/Modules/HomeTabBar/HomeTabBarCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/HomeTabBar/Subviews/Swipe/HomeTabBarAnimationProgress.swift
Anytype/Sources/PresentationLayer/Modules/HomeTabBar/Subviews/Swipe/HomeTabBarSwipeContainer.swift
Anytype/Sources/PresentationLayer/Modules/HomeTabBar/Subviews/Swipe/HomeTabLeftToRightGesture.swift

https://github.com/user-attachments/assets/6166db11-f6f4-4481-bef8-c5427cfebab6

IOS-3781 Home | Add swipe between chat and widgets (from iOS 18)

---

Anytype/Sources/PresentationLayer/Modules/HomeTabBar/HomeTabBarCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/HomeTabBar/HomeTabBarCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeTabBar/Subviews/HomeTabBarView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift

https://github.com/user-attachments/assets/1f2cd39b-18f1-4605-96fe-3d3fd04bcb1e

iOS-3769 Chat | Open space settings

---

Anytype/Resources/Strings/it.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Builders/SlashMenuItemsBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/Actions/SlashActionObject.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashAction.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockActionHandler.swift

https://github.com/user-attachments/assets/b7de551e-ff0d-4dde-b993-9a6678ef353b

iOS-3766 Date as an object | Add `/date` command

---

Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Date/ObjectCellData.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Builders/SlashMenuItemsBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/Actions/SlashActionObject.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashAction.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockActionHandler.swift

iOS-3670 Date as an object | Add To Bin action for objects

---

Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorViewModel.swift

https://github.com/user-attachments/assets/8315d952-bdf8-4f09-ad4d-4963af328dae

iOS-3801 Date as an object | Dismiss date object sheet by object tap

---

Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ChatReadOnlyBottomView.swift

IOS-3529 Chat | Fix read-only design

---

Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetContainerView.swift

https://github.com/user-attachments/assets/4cbb6362-9f1e-46fd-a8c2-3693d5aec6ae

iOS-3768 Hide change widget type option in case of one type

---

Anytype/Sources/PresentationLayer/Flows/ChatCoordinator/ChatCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/ChatCoordinator/ChatCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Reaction/MessageReactionList.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Reaction/MessageReactionView.swift
Anytype/Sources/PresentationLayer/Modules/Date/ObjectCellData.swift
Anytype/Sources/PresentationLayer/Modules/MessageParticipantsReaction/MessageParticipantsReactionView.swift
Anytype/Sources/PresentationLayer/Modules/MessageParticipantsReaction/MessageParticipantsReactionViewModel.swift
Anytype/Sources/ServiceLayer/Subscriptions/RecentSubscriptionService.swift
Anytype/Sources/ServiceLayer/Subscriptions/SetsSubscriptionService.swift
Modules/Services/Sources/Models/Participant.swift

https://github.com/user-attachments/assets/b0b7f765-86c9-404d-94fa-f8ce77dbdd4d

iOS-3761 Chat | Add reactions list screen

---

Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift

IOS-3593 Move update banner to the space hub

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatInput.swift

iOS-3809 Chat | Rename message actions

---

Anytype/Sources/PresentationLayer/Modules/ObjectType/Views/ObjectsList/Subscriptions/ObjectsListSubscriptionService.swift
Anytype/Sources/ServiceLayer/ActiveSpaceParticipantsStorage/ParticipantsSubscription.swift
Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift
Anytype/Sources/ServiceLayer/Object/SearchWithMeta/SearchWithMetaService.swift
Anytype/Sources/ServiceLayer/Subscriptions/FilesSubscriptionService.swift
Modules/Services/Sources/Services/SearchService/SearchHelper.swift

https://github.com/user-attachments/assets/d062df9b-d142-4bd4-af8b-fc22a9d1516d

Ios-3789 Filter out files created via clipboard

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/CalendarView/CalendarView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Date/Coordinator/RelationCalendarCoordinatorView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Date/Coordinator/RelationCalendarCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Date/RelationCalendarQuickOption.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Date/RelationCalendarView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Date/RelationCalendarViewModel.swift
Anytype/Sources/PresentationLayer/RelationValueFlow/RelationValueCoordinator/RelationValueCoordinatorViewModel.swift

https://github.com/user-attachments/assets/b866d05c-34a2-4759-8b27-259b4fe36bf8

iOS-3765 Date as an object | Add possibility to open Date object from calendar view

---

Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViewModel.swift
Modules/DeepLinks/Sources/DeepLinks/DeepLink.swift
Modules/DeepLinks/Sources/DeepLinks/DeepLinkParser.swift

Now we add invite for shared space in object deeplink

IOS-3520 Support invites in object deeplink

---

Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift

iOS-3815 Date as an object | Add weekday for date object

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ChatMentionList.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/MentionObjectModel.swift

https://github.com/user-attachments/assets/9e727ee3-654d-492a-afba-4c9d1a229103

iOS-3497 Chat | Add (You) in mentions and update design a little

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubDropDelegate.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Anytype/Sources/PreviewMocks/Mocks/WorkspacesStorageMock.swift

https://github.com/user-attachments/assets/8807aab6-90d2-4332-94d3-cf1968d10781

IOS-3785 Space hub | Add DnD to pinned spaces list

---

Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift

iOS-3837 Date as an object | Add relative tag

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Icon.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsModuleOutput.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Space/SpaceObjectIconPickerView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Space/SpaceObjectIconPickerViewModel.swift
Modules/Services/Sources/Models/Details/ObjectIcon.swift

https://github.com/user-attachments/assets/c366257a-5578-43eb-92ad-5a08e725fe74

iOS-3840 Fix space icon issue

---

Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/NewRelationCoordinatorView.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/NewRelationCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/NewRelationView.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/NewRelationViewModel.swift
Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsSearchViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/Coordinator/SetRelationsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationsListSearch/RelationsSearchCoordinatorView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationsListSearch/RelationsSearchCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationsListSearch/RelationsSearchData.swift

IOS-3541 Refactoring | Remove direct document use from RelationsSearchData

---

Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/NewRelationView.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/NewRelationViewModel.swift
Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsInteractor.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsModuleTarget.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsSearchInteractor.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsSearchViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsRelationsData.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationsListSearch/RelationsSearchCoordinatorView.swift
Modules/Services/Sources/Services/Relations/RelationsService.swift
Modules/Services/Sources/Services/Relations/RelationsServiceProtocol.swift

https://github.com/user-attachments/assets/5bd0620f-8dd4-46dd-a029-f0e72b811e07

IOS-3636 Relations | Support new api for relation creation

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Common/ImageIdIconView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Common/LoadingPlaceholderIconView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/ProfileIconView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessageBuilder.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageViewModel.swift
Modules/Services/Sources/Models/Details/ObjectIcon.swift

Left - Old, Right - New
https://github.com/user-attachments/assets/48740be4-6a96-4a80-bf36-42dc99d314a1

IOS-3798 Chat | fix if participants are not loaded immediately

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/Views/ObjectIsNotAvailableAlert.swift

https://github.com/user-attachments/assets/1e0c6f05-6fc8-4eeb-a666-81f635f87270

IOS-3860 Deeplinks | Show alert if object is not available and we do not have an invite

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

https://github.com/user-attachments/assets/9e56b15a-b4c8-4f92-a01b-9c07b0e1e37b

IOS-3859 Add new loading state to spaces

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
Modules/Services/Sources/Models/Block/BlockInformation/BlockInfromationExtension.swift

IOS-3450 Remove block file from file layout

---

Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatInput.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatTextViewCoordinator.swift

https://github.com/user-attachments/assets/8e0173ce-457b-41d9-8a7c-0c9564d35768

iOs-3354 Chat | Text limit

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/InfoPlist.strings
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/ImagePickerView/ImagePickerView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/SimpleCamera/SimpleCameraView.swift
Anytype/Sources/PresentationLayer/Flows/ChatCoordinator/ChatCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/ChatCoordinator/ChatCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatInput.swift
Anytype/Sources/ServiceLayer/Block/File/FileActionsService.swift
Anytype/Sources/ServiceLayer/Block/File/FileActionsServiceProtocol.swift
Anytype/Supporting files/Info.plist
Modules/AnytypeCore/AnytypeCore/Extensions/DateFormatter+Anytype.swift
Modules/SharedContentManager/Sources/SharedContentImporter.swift

https://github.com/user-attachments/assets/f301d7ec-36b3-4945-8f85-ac93fa30abc2

iOS-3775 Chat | Take photo / video from camera

---

AnyTypeTests/Services/ChatMessageLimitsTests.swift
Anytype.xcodeproj/project.pbxproj
Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessageLimits.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ChatSendLimitAlert.swift
Modules/AnytypeCore/AnytypeCore/Utils/AtomicStorage.swift

https://github.com/user-attachments/assets/2123b40d-e3c8-4ec4-9b55-19feab85e7d0

iOS-3782 Chat | limits on message sending speed

---

Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Reaction/MessageReactionView.swift

https://github.com/user-attachments/assets/778d964f-3b9f-4473-86ba-f0c1c2a08e58

iOS-3884 Chat | Fix reaction tap on iOS 17

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Analytics/AnalyticsConstants.swift
Anytype/Sources/PresentationLayer/Auth/Auth/AuthViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/ServiceLayer/ServerConfigirationStorage/ServerConfigirationStorage.swift
Modules/AnytypeCore/AnytypeCore/Extensions/StringExtension.swift
Modules/DeepLinks/Sources/DeepLinks/DeepLink.swift
Modules/DeepLinks/Sources/DeepLinks/DeepLinkParser.swift

https://github.com/user-attachments/assets/5f5e76bb-2354-460a-b592-bca39aa40d61

IOS-3882 Add deeplink for network config support

---

Anytype/Sources/ApplicationLayer/GlobalEnv/KeyboardDismiss.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatInput.swift

https://github.com/user-attachments/assets/1a124ce7-eda2-4c6d-ad9b-455a1ad45d68

IOS-3782 Chat | Time limit alert | fix keyboard on ipad

---

Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessageBuilder.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessagesStorage.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Collection/ChatCollectionViewCoordinator.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Attachments/MessageListAttachmentsViewContainer.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageAttachmentDetails.swift
Anytype/Sources/ServiceLayer/ChatActionService/ChatActionService.swift

https://github.com/user-attachments/assets/ab5210f4-564b-4c0b-a6ad-ce42eb0b8c48

IOS-3721 Chat | Attachments | Add loading state

---

Anytype/Sources/PresentationLayer/Modules/Chat/Models/ChatLinkedObject.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/MessageInputAttachmentsViewContainer.swift
Anytype/Sources/ServiceLayer/Block/File/FileActionsServiceProtocol.swift

https://github.com/user-attachments/assets/c7769e21-005d-46a4-9dce-054815b7ae3f

IOS-3900 Chat | Scroll to new attachments

---

Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Date/RelationItemData.swift

https://github.com/user-attachments/assets/18928ed1-c761-4323-a608-4b5622f58b0c

iOS-3865 Scroll to selected relation in Date object

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/CircleLoadingView/CircleLoadingView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/Local/MessageLinkLocalDownloading.swift

https://github.com/user-attachments/assets/72d197ad-4c1d-4843-8eff-bafbd9273979

iOS-3751 Chat | New loading indicator

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/DynamicForeground.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/Support/PageNavigationBackButton.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatInput.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelView.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelViewModel.swift

https://github.com/user-attachments/assets/b7fc0fc9-3a5c-4750-8d3c-f8b363bda171

iOS-3925 Home | New navigation | Sharing buttons

---

Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatExternalActionProvider.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/Models/ChatLinkFromPanel.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelView.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelViewModel.swift

https://github.com/user-attachments/assets/1617ca89-b671-4628-b535-ab38628135c4

iOS-3925 Home | New navigation | Add to chat button

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/NavigationView/AnytypeNavigationCoordinator.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/NavigationView/AnytypeNavigationView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/NavigationView/FullScreenSwipeNavigationController.swift

https://github.com/user-attachments/assets/072bd435-c9c4-4445-a527-a501a9670cbc

iOS-3925 Home | New navigation | Add full screen pop swipe

---

Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift

https://github.com/user-attachments/assets/7c966300-a94e-4449-a23b-85ca7a8ffd42

IOS-3912 Primitives | Fix description behavior in lists

---

Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/RelationInfoCoordinatorView.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/RelationInfoCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/RelationInfoView.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoModuleInput.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoModuleOutput.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoViewModel.swift
Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/Page/EditorPageModuleOutput.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/Legacy/RelationsListView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/Legacy/RelationsListViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouterProtocol.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationsListSearch/RelationsSearchCoordinatorView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationsListSearch/RelationsSearchCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetRelationsView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetRelationsViewModel.swift

Newly renamed module will be used for relation editing as well as creation

IOS-3755 Renamed NewRelation -> RelationInfo

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/RelationInfoCoordinatorView.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/RelationInfoCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/RelationInfoData.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/RelationInfoView.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoModuleOutput.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationsListSearch/RelationsSearchCoordinatorViewModel.swift

IOS-3755 Supported relation editing mode

---

Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/Local/MessageLinkLocalBinaryFileView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/MessageLinkBookmarkView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/MessageLinkObjectView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/MessageLinkedUploadedObject.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/LinkObject/Common/MessageLink+Styles.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Attachments/MessageListAttachmentsViewContainer.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Attachments/MessageObjectAttachmentView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Attachments/MessageObjectBookmarkView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageAttachmentDetails.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Bookmark/View/Сomponents/BlockBookmarkInfoView.swift
Anytype/Sources/ServiceLayer/Subscriptions/ObjectIdsSubscriptionService.swift

iOS-3776 Chat | Update bookmark design

---

Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/Local/MessageLinkLocalBinaryFileView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/Local/MessageLinkedLocalFile.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/MessageLinkBookmarkView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/MessageLinkObjectView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/MessageLinkedUploadedObject.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/LinkObject/Common/MessageLink+Styles.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Attachments/MessageListAttachmentsViewContainer.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Attachments/MessageObjectAttachmentView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Attachments/MessageObjectBookmarkView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageAttachmentDetails.swift
Anytype/Sources/PresentationLayer/Modules/ShareOptions/ShareOptionsInteractor.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Bookmark/View/Сomponents/BlockBookmarkInfoView.swift
Anytype/Sources/ServiceLayer/Block/File/FileActionsService.swift
Anytype/Sources/ServiceLayer/Block/File/FileActionsServiceProtocol.swift
Anytype/Sources/ServiceLayer/Subscriptions/ObjectIdsSubscriptionService.swift

iOS-3774 Chat | File attachment - add size

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/Models/Relations/Entities/Relation.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/RelationInfoData.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/RelationInfoView.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/Subviews/NewRelationSectionView.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsInteractor.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationsListSearch/RelationsSearchCoordinatorViewModel.swift
AnytypeTests/Markdown/Mocks/MockRelationsService.swift
Modules/Services/Sources/Models/Relations/Models/RelationDetails.swift
Modules/Services/Sources/Services/Relations/RelationsService.swift
Modules/Services/Sources/Services/Relations/RelationsServiceProtocol.swift

https://github.com/user-attachments/assets/0ab47700-02ed-4cc3-b4f5-408b825077ce

IOS-3755 Primitives | Add relation edit capabilities

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift

https://github.com/user-attachments/assets/ca64c26d-97ee-4caa-9fdb-00f0b2c6a339

IOS-3935 Space hub | Changed settings icon to profile icon

---

Anytype/Sources/Design system/Colors/Gradients/CoverGradient.swift
Anytype/Sources/PresentationLayer/Auth/DeletedAccount/DeletedAccountView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DashboardWallpaper.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Cover/CoverColors/CoverColorsGridViewModel.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

- Fix glitch when open hub with pop gesture

iOS-3933 SpaceHub | Fix space background performance

---

Anytype/Sources/PresentationLayer/Flows/ChatCoordinator/ChatCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/EditorFlow/EditorCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsCoordinator/HomeWidgetsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/ObjectTypeCoordinator/ObjectTypeCoordinatorModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/Support/PageNavigation.swift

No business logic have changed

Ios-3897 Navigation | Renamed push to open

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Profile/ProfileView.swift
Anytype/Sources/PresentationLayer/Modules/Profile/ProfileViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceShareParticipantView.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/AlertScreenData.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/ScreenData+Details.swift

https://github.com/user-attachments/assets/864a836f-6a83-416f-ba3f-b336df3d3034

Ios-3897 Participant profile updates

---

Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceShareParticipantView.swift
Anytype/Sources/PresentationLayer/Modules/SpceMembers/SpaceMembersView.swift
Anytype/Sources/PresentationLayer/Modules/SpceMembers/SpaceMembersViewModel.swift

https://github.com/user-attachments/assets/149333cc-0b4c-4ee5-9179-62f69e5cfd80

IOS-3897 Profile | Add participant actions to members view

---

Modules/Services/Sources/Models/Details/BundledRelationValueProvider+CustomFields.swift

Prerequisite for primitives migration

IOS-3941 Fallback layout to basic

---

Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeView.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/Views/ObjectsList/ObjectTypeObjectsListView.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/Views/ObjectsList/ObjectTypeObjectsListViewModel.swift

Ios 3908 do not provide edit function from certain types

---

Anytype/Sources/Models/Documents/Events/EventConverters/MiddlewareEventConverter.swift
Anytype/Sources/Models/Relations/RelationsBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Subscriptions/Set/SetSubscriptionDataBuilder.swift
Modules/Services/Sources/Models/Details/BundledRelationValueProvider+CustomFields.swift
Modules/Services/Sources/Models/SubscriptionData/BundledRelationKey+CommonKeys.swift
Modules/Services/Sources/Services/SearchService/SearchHelper.swift
Modules/Services/Sources/Services/Templates/TemplatesService.swift

https://github.com/user-attachments/assets/db00d334-f310-4613-aa47-58f2bd12ca5d

Ios-3818 Primitives | Support layout derived from type

---

Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift

https://github.com/user-attachments/assets/d961c09b-c755-4207-85cf-899ca75002b5

IOS-3897 New navigation | Open space before showing an alert

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchDataBuilder.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchDataSection.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchViewModel.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

iOS-3987 Global search v2.0 | Add remove action

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/SearchView/SearchBar.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchDataBuilder.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchDataSection.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchState.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchViewModel.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentView.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentViewModel.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/Models/AllContentState.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/Models/ObjectTypeSection.swift
Anytype/Sources/PresentationLayer/Modules/AllContent/Subscription/AllContentSubscriptionService.swift
Anytype/Sources/ServiceLayer/Object/SearchWithMeta/SearchWithMetaService.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

https://github.com/user-attachments/assets/0a76bc5c-102b-4317-99cd-707a8243f26a

iOS-3986 Global search v2.0 | Add objects sections

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Entities/RelationsSectionBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/ObjectFieldsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/Views/ObjectFieldsBottomAlert.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/RelationDetails+Identifiable.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
AnytypeTests/Markdown/Mocks/MockRelationsService.swift
Modules/Services/Sources/Services/Relations/RelationsService.swift
Modules/Services/Sources/Services/Relations/RelationsServiceProtocol.swift

https://github.com/user-attachments/assets/6a6fef50-aec8-4eab-86f5-1fcb37113948

Ios-3734 Primitives | Conflict relations in type

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/SearchView/SearchBar.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchView.swift

https://github.com/user-attachments/assets/158b03a5-f095-45ae-9bc8-386df6e0449f

iOS-3998 Global search v2.0 | Add animation for header

---

Anytype/Sources/Analytics/AnalyticsConstants.swift
Anytype/Sources/Analytics/Converters/ObjectType+Analytics.swift
Anytype/Sources/Models/AnytypeWigetId+Extensions.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Models/WidgetSource.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchInteractor.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Models/Details/Entities/AnytypeWidgetId.swift

IOS-4000 Widgets | Add source for all object types

---

Anytype/Sources/PresentationLayer/Flows/EditorFlow/EditorCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/AllObject/AllObjectCommonListWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/AllObject/PagesCompactListWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/AllObject/PagesListWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/AllObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/Models/AllObjectWidgetType.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/PagesWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Tree/Specific/PagesTreeWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/AllContent/WidgetObjectListAllContentViewModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/AllContent/WidgetObjectListPagesView.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift

https://github.com/user-attachments/assets/c7fbace7-d6f9-46d2-ae5a-27a9477febd3

iOS-4004 Widget | Support pages widget

---

Anytype/Sources/PresentationLayer/Flows/EditorFlow/EditorCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/AllObject/ListsCompactListWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/AllObject/ListsListWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/Models/AllObjectWidgetType.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/AllContent/WidgetObjectListListsView.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift

https://github.com/user-attachments/assets/9e673f2b-80e1-429d-9a21-4a4739bbe8b9

iOS-4009 Widget | Support lists widget 

---

Anytype/Sources/PresentationLayer/Flows/EditorFlow/EditorCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/AllObject/MediaCompactListWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/AllObject/MediaListWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/Models/AllObjectWidgetType.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/AllContent/WidgetObjectListMediaView.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift

https://github.com/user-attachments/assets/8971bf32-3513-4281-b160-7eb6d46c5423

IOS-4011 Widgets | Add media widget type

---

Anytype/Sources/PresentationLayer/Flows/EditorFlow/EditorCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/AllObject/FilesCompactListWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/AllObject/FilesListWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/Models/AllObjectWidgetType.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/AllContent/WidgetObjectListFilesView.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Files/WidgetObjectListFilesManagerView.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Files/WidgetObjectListFilesManagerViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift

https://github.com/user-attachments/assets/597ce27e-c9a6-498d-b27a-5b1048b69037

iOS-4013 Widgets | support files widget

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/Coordinator/ObjectSearchWithMetaCoordinatorView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/Coordinator/ObjectSearchWithMetaCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/ObjectSearchWithMetaModuleOutput.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/ObjectSearchWithMetaView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/ObjectSearchWithMetaViewModel.swift
Anytype/Sources/PresentationLayer/Flows/ChatCoordinator/ChatCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/ChatCoordinator/ChatCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatInput.swift
Anytype/Sources/ServiceLayer/Object/SearchWithMeta/SearchWithMetaService.swift

https://github.com/user-attachments/assets/a4abbc45-8c6e-460f-99e8-0ba506ae717f

iOS-3992 Chat | Support attach pages / lists from chat (without creation)

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/Coordinator/ObjectSearchWithMetaCoordinatorView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/Coordinator/ObjectSearchWithMetaCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/ObjectSearchCreationModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/ObjectSearchWithMetaModuleData.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/ObjectSearchWithMetaModuleOutput.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/ObjectSearchWithMetaView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/ObjectSearchWithMetaViewModel.swift
Anytype/Sources/PresentationLayer/Flows/ChatCreateObject/ChatCreateObjectCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/ChatCreateObject/ChatCreateObjectCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/ChatCreateObject/ChatCreateObjectDismissResult.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift

https://github.com/user-attachments/assets/ad7773a3-ab4c-4768-b99f-b592bbc407b9

iOS-3993 Chat | Add creation to pages / lists

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/ObjectSearchWithMetaModuleData.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearchWithMeta/ObjectSearchWithMetaViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift

iOS-4015 Chat | Filter used object types from More

---

Anytype/Sources/Models/Relations/Entities/Relation.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/RelationInfoData.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift

https://github.com/user-attachments/assets/14e53681-d23c-4e47-abeb-d132f8db3f17

Ios-3970 Primitives | Provide limited object type for editing relations view  @ignatovv

---

.github/workflows/ipa.yaml

IOS-3881-trigger the tests in test repo

---

Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessageBuilder.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Attachments/MessageGridAttachmentsContainer.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageViewData.swift

https://github.com/user-attachments/assets/fb851468-9b09-4931-a9b6-ad07d182a7f9

iOS-3955 Chat | profile icon | open profile

---

Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetView.swift
Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetViewModel.swift

https://github.com/user-attachments/assets/d187ecae-d723-4212-b295-c12b6686109d

iOS-4029 Add action To Bin in Simple Set

---

Anytype/Sources/PresentationLayer/Flows/EditorFlow/EditorCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SimpleSetCoordinator/SimpleSetCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SimpleSetCoordinator/SimpleSetCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetView.swift
Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SimpleSet/Subscription/SimpleSetSubscriptionService.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/ScreenData.swift
Anytype/Sources/ServiceLayer/ServicesDI.swift

https://github.com/user-attachments/assets/9cfbb101-1185-4d53-ba0e-48bd90f089a4

iOS-4029 Add empty SimpleSet module

---

Anytype/Sources/Design system/Fonts/UIKitFont.swift
Anytype/Sources/PresentationLayer/Common/UIKit/AnytypeUITextView/AnytypeUITextView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatPasteboardHelper.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatTextView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatTextViewCoordinator.swift
Anytype/Sources/ServiceLayer/Block/Pastboard/PasteboardHelper.swift

https://github.com/user-attachments/assets/88b0d877-d0e7-4669-ad24-8ec95ac2abd0

iOS-3913 Chat | Paste from buffer text with style

---

Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeView.swift

IOS-4051 Primitives | Supported new navigation

---

Anytype/Anytype.entitlements
Anytype/Sources/ApplicationLayer/AppDelegate.swift
Anytype/Sources/PresentationLayer/Debug/Flows/InternalDebug/Alerts/DebugMenuPushTokenAlert.swift
Anytype/Sources/PresentationLayer/Debug/Flows/InternalDebug/DebugMenuView.swift
Anytype/Sources/PresentationLayer/Debug/Flows/InternalDebug/DebugMenuViewModel.swift
Anytype/Sources/ServiceLayer/PushNotification/PushNotificationService.swift
Anytype/Sources/ServiceLayer/ServicesDI.swift
Anytype/Supporting files/Info.plist

https://github.com/user-attachments/assets/75f98f80-62f5-4090-a286-e31db9f82269

iOS-4071 Push Notification | get token for test

---

Anytype/Sources/FrameworkExtensions/UIKit/UIColor+Convenience.swift
Anytype/Sources/PresentationLayer/Common/UIKit/Extensions/UIImageExtensions.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageColor.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageReplyView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageTextBuilder.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageView.swift
Anytype/Sources/ServiceLayer/IconColorService/IconColorService.swift
Anytype/Sources/ServiceLayer/ServicesDI.swift

https://github.com/user-attachments/assets/addf04ab-a3bb-4b62-8139-57f9ac30cd04

iOS-4072 Chat Message | Experiment | Your bubble color for background

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Views/SpaceSettingsInfoView.swift

https://github.com/user-attachments/assets/14f0e936-1b13-4332-96a4-e05a2736bb40

IOS-4104 New settings | Move delete and space info away

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/CircularProgressBar/CircularProgressBar.swift

https://github.com/user-attachments/assets/f2a9f345-fdba-4ab3-af69-24ebeeae0b63

iOS-3934 Migration | Fix circular loader

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/RoundedButton.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/Legacy/SpaceSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/NewSpaceSettingsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/NewSpaceSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Legacy/SpaceSettingsModuleOutput.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsModuleOutput.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Views/SpaceDetails/SpaceDetailsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Views/SpaceDetails/SpaceDetailsViewModel.swift

Ios 4104 new settings | Updated settings UI

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/RoundedButton.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/IconView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/RemoteStorage/RemoteStorageSegmentInfo.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Views/SpaceSettingsInfoView.swift

https://github.com/user-attachments/assets/109ea5f9-f1c0-4cd1-b5d4-236f23e7e3dd

Ios-4104 new settings | Default object type preview

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsMoveHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsRow.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsRowBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
AnytypeTests/Markdown/Mocks/MockRelationsService.swift
Modules/Services/Sources/Services/Relations/RelationsService.swift
Modules/Services/Sources/Services/Relations/RelationsServiceProtocol.swift

https://github.com/user-attachments/assets/4f1a2bbe-3ccb-4396-af85-2ff6a8dd85d9

IOS-4008 Support recommended hidden relations api

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchInteractor.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchViewModel.swift

https://github.com/user-attachments/assets/803e15d7-d0d9-4183-9cda-e7109929557b

iOS-4148 Add object type section in Widget source screen

---

Anytype/Sources/PresentationLayer/Flows/HomeWidgetsCoordinator/HomeWidgetsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsCoordinator/HomeWidgetsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/NewSpaceSettingsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/NewSpaceSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsModuleOutput.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Views/SpaceDetails/SpaceDetailsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Views/SpaceDetails/SpaceDetailsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/ScreenData.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/SettingsScreenData.swift
Modules/Services/Sources/Models/Account/AccountInfo.swift

https://github.com/user-attachments/assets/9d845115-abb6-4c70-a5c6-57cd07770202

Ios-4104 New settings | Use page navigation for new settings

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Relations/FlowRelationsView/FlowRelationsView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/TitleWIthIconView/TitleWithIconView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetRow.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetRowModel+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Collection/Cell/SetGalleryViewCell.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Models/SetContentViewDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Table/Row/SetContentViewItemConfiguration.swift
Modules/Services/Sources/Models/Block/BlockContent/Content/DataView/DataviewView.swift

https://github.com/user-attachments/assets/70bd30d5-6bba-4aa3-8f0d-fdb7a02dc8f5

iOS-4164 Set | Support relation `Name` setting for `gallery` view

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Common/ImageIdIconView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Attachments/MessageObjectBigBookmarkView.swift

IOS-4165 Message | Update bookmark design

---

Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessageBuilder.swift

If reply contains
```
AAAA
BBBB
CCCC
```
Will be
```
AAAA
BBBB
CCCC
```

IOS-4157 Chat | Improve message in reply

---

AnyTypeTests/Chat/ChatInputLinkParserTests.swift
Anytype.xcodeproj/project.pbxproj
Anytype/Sources/PresentationLayer/Common/ObjectIcon/Models/Sets/ObjectIconImageFontSet.swift
Anytype/Sources/PresentationLayer/Common/ObjectIcon/Models/Sets/ObjectIconImageGuidelineSet.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Common/ImageUrlIconView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Icon.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/IconView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Models/ChatLinkedObject.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/ChatInputAttachmentsViewContainer.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/ChatLocalBookmarkView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatInput.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatInputLinkParser.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatTextView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatTextViewCoordinator.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/NSAttributedString+MessageExtensions.swift
Anytype/Sources/ServiceLayer/ChatActionService/ChatActionService.swift
Anytype/Sources/ServiceLayer/IconColorService/IconColorService.swift
Modules/Services/Sources/Services/Bookmark/BookmarkModels.swift
Modules/Services/Sources/Services/Bookmark/BookmarkService.swift
Modules/Services/Sources/Services/Bookmark/BookmarkServiceProtocol.swift

https://github.com/user-attachments/assets/7714dd30-c077-49b1-a80a-2cfd274d96fa

iOS-4173 Chat Input | Parse bookmark when typing

---

Anytype/Sources/PresentationLayer/Common/ObjectIcon/Models/Sets/ObjectIconImageFontSet.swift
Anytype/Sources/PresentationLayer/Common/ObjectIcon/Models/Sets/ObjectIconImageGuidelineSet.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/CustomIconView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/ObjectIconView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeader+Mutation.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Common/CustomIcons/CustomIconColorOverlay.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Common/CustomIcons/CustomIconGridView.swift
Anytype/Sources/ServiceLayer/ObjectHeaderUploadingService/ObjectHeaderUploadingService.swift
Modules/AnytypeCore/AnytypeCore/Structs/CustomIcon.swift
Modules/AnytypeCore/AnytypeCore/Structs/CustomIconColor.swift
Modules/Services/Sources/Models/Details/ObjectIcon.swift
Modules/Services/Sources/Models/Details/ObjectIconBuilder.swift

https://github.com/user-attachments/assets/175b3f1f-a947-4baf-9a3d-c807a7d8663b

IOS-4062 | Supported custom icons for objects

---

AnyTypeTests/Chat/ChatInputLinkParserTests.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatInputLinkParser.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatPasteboardHelper.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatTextViewCoordinator.swift
Anytype/Sources/ServiceLayer/Block/Pastboard/PasteboardHelper.swift

https://github.com/user-attachments/assets/cc27f6ef-75c3-4694-9d11-74c08817ed62

iOS-4173 Chat Input | Support paste links from buffer

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/RoundedButton.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/RoundedButtonView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift
Modules/Services/Sources/Services/Workspace/WorkspaceSetDetails.swift

https://github.com/user-attachments/assets/6e85404c-f895-4d41-b7ec-d0eca63ba587

Ios-4193 Settings | add chat toggle

---

Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetRow.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Collection/Cell/SetGalleryViewCell.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Table/Row/SetContentViewItemConfiguration.swift

iOS-4164 Fix gallery cover height

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Common/CustomIcons/CustomIconColorOverlay.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Common/CustomIcons/CustomIconGridView.swift

https://github.com/user-attachments/assets/597f46e3-1b7d-4501-b183-42c7b8b2e603

Ios4062 New Icons | Add dynamic overlay position

---

Anytype/Sources/Analytics/Converters/ObjectType+Analytics.swift
Anytype/Sources/Models/AnytypeWigetId+Extensions.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetSubmoduleView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsDI.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Models/HomeWidgetState.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Models/WidgetSource.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Bin/BinWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Bin/BinWidgetViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/WidgetActionsMenu/WidgetActionsViewCommonMenuProvider.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/WidgetActionsMenu/WidgetCommonActionsMenuView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetContainerView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetContainerViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchInteractor.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Models/Details/Entities/AnytypeWidgetId.swift

https://github.com/user-attachments/assets/39cef877-5cd3-4632-b8be-79906946fb39

iOS-4186 Widgets | Add bin widget from mw

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/DashboardWallpaper.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/LocalIconView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/SpaceIconView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Local/LocalObjectIconPickerView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Local/LocalObjectIconPickerViewModel.swift
Anytype/Sources/ServiceLayer/IconColorService/IconColorService.swift
Modules/Services/Sources/Models/Details/ObjectIcon.swift

https://github.com/user-attachments/assets/3c925d02-ab4d-410c-8709-513d040bba87

iOS-4227 Add opportunity to set space icon during space creation

---

Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Submodule/WidgetsHeader/WidgetsHeaderView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Submodule/WidgetsHeader/WidgetsHeaderViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceProfile/SpaceProfileView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceProfile/SpaceProfileViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Views/SpaceSettingsShareSection.swift

Space profile card for viewer with invite buttons
Ability to share invites for editors (not owners)
https://github.com/user-attachments/assets/e5b16e9f-a5a8-47ef-8593-8a64290c8e73

Ios-4194 New settings + Space profile

---

Anytype/Sources/PresentationLayer/SpaceSettings/SpaceProfile/SpaceProfileViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Views/SettingsInfoEditingView.swift

https://github.com/user-attachments/assets/1414ac7b-6579-4f05-ab5b-676343fc31cb

IOS-4104 New settings | Use new ux for name and description editing

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/StandardButtonConfig.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/StandardButtonStyle.swift
Anytype/Sources/PresentationLayer/Debug/Examples/ControlsExample.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift

https://github.com/user-attachments/assets/40bc88c0-db52-4fe6-9996-8add9f7dc8fa

iOS-4249 Widgets | Empty State

---

Anytype/Sources/Models/Extensions/ObjectType+Extensions.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
Anytype/Sources/ServiceLayer/Object/TypeProvider/ObjectTypeProvider.swift
Modules/Services/Sources/Models/ObjectType.swift

https://github.com/user-attachments/assets/c4447d98-408d-4c56-91af-1c3273f42f31

IOS-4204 Types search | Use restriction delete for types

---

Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Tips/HomeAnyAppBetaTip.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift

https://github.com/user-attachments/assets/d48bb5dc-e2b6-4271-a676-3a068c3e33f6

iOS-4223 Any App Beta Tip | Move from home to space hub

---

Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/Page/EditorPageModuleAssembly.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/Block/TextBlock/SimpleTablesTextBlockActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageBlocksStateManager.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelActions.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandler.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandlerProtocol.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionService/BlockActionService.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionService/BlockActionServiceProtocol.swift
AnytypeTests/Markdown/Mocks/BlockActionHandlerMock.swift
AnytypeTests/Markdown/Mocks/BlockActionServiceMock.swift

https://github.com/user-attachments/assets/c197a2da-b17f-40eb-b99b-2e3a580b1e70

iOS-4236 Editor | open media picker after create a block

---

.gitignore
Scripts/middle-install.sh

.libcache will be store last 10 mw versions

IOS-4272 Core | add cache for mw libs

---

Anytype/Sources/Models/Relations/SingleRelationBuilder.swift
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationListViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationOption.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/Model/ObjectSearchData.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/SearchWithMetaModelBuilder.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/LinkToObject/LinkToObjectSearchData.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ChatMentionList.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatInput.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageAttachmentDetails.swift
Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelView.swift
Anytype/Sources/PresentationLayer/Modules/MessageParticipantsReaction/MessageParticipantsReactionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/AllContent/WidgetObjectListAllContentViewModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Bin/WidgetObjectListBinViewModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Common/Models/WidgetObjectListRowModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Favorites/WidgetObjectListFavoritesViewModel.swift
Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Recent/WidgetObjectListRecentViewModel.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsViewModel.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/ObjectsSearchViewModel/ObjectsSearchViewModel.swift
Anytype/Sources/PresentationLayer/Settings/Personalization/PersonalizationViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionViewController/MentionsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashAction.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/BlockLinkCardView.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/Support/BlockLinkState+Text.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/List/RelationFilterBuilder.swift
Anytype/Sources/ServiceLayer/QuickActions/QuickActionShortcutBuilder.swift

IOS-4233 Use type display name instead of name

---

Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ChatActionPanel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Collection/ChatCollectionView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Collection/ChatCollectionViewContainer.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

iOS-4284 Counters | add buttons

---

Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Anytype/Sources/ServiceLayer/ParticipantSpacesStorage/Model/SpacePermissions.swift

Remove approve buttons for editor in space settings

IOS-4283 Space settings | Add approve requests permissions

---

Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift

https://github.com/user-attachments/assets/5f07afe4-202e-41f5-b90f-0d5f29c6457c

IOS-4282 New settings | Show share buttons only if invite available

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings

Field -> Property
Set -> Query

Ios-4263 Primitives | wording update

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift

https://github.com/user-attachments/assets/ed241a21-fad1-4db7-8dd0-a6a455a0047c

IOS-4182 Space hub | Show delete space confirmation

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Alerts/ObjectSettingsResolveConflictAlert.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSetting.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSettingBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSettingsPrimitivesConflictManager.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingRow.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsViewModel.swift
AnytypeTests/Markdown/Mocks/MockRelationsService.swift
Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x18/Attention.imageset/Contents.json
Modules/Services/Sources/Services/Relations/RelationsService.swift
Modules/Services/Sources/Services/Relations/RelationsServiceProtocol.swift

https://github.com/user-attachments/assets/9c77fd15-093f-41a0-a084-d7850328d214

IOS-4302 Primitives | Add resolve conflicts section to object settings

---

Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Views/SettingsInfoEditingView.swift

https://github.com/user-attachments/assets/0d0f2ffe-feb9-43e6-a688-f5e6491b3d37

IOS-4104 New settings | Supported custom fonts for editing view

---

Anytype/Sources/Models/Documents/Document/DocumentSyncStatusData.swift
Anytype/Sources/Models/Documents/Events/DocumentViewModelSetter.swift
Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
Anytype/Sources/Models/ObjectPermissions/ObjectPermissions.swift
Anytype/Sources/PresentationLayer/Common/Extensions/RelationValuesProtocol+PageCellTitle.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Text/Actions/TextRelationReloadContentActionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessageBuilder.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/ChatInputUploadedObject.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Attachments/MessageGridAttachmentsContainer.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Attachments/MessageListAttachmentsViewContainer.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageAttachmentDetails.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/ShareOptions/ShareOptionsViewModel.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/Support/BlockLinkState.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/HeaderBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeaderViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Object/ObjectIconPickerViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Layout/ObjectLayoutPickerViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSettingsPrimitivesConflictManager.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Models/SetContentViewDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SetViewSettings/SetViewSettingsList/SetViewSettingsListModel.swift
Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandler.swift
Modules/Services/Sources/Models/Details/BundledRelationValueProvider+CustomFields.swift
Modules/Services/Sources/Models/Details/FileDetails.swift
Modules/Services/Sources/Models/Details/ObjectIconBuilder.swift

IOS-4312 layoutValue -> resolvedLayoutValue

---

Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatInternalMessageStorage+Events.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessagesStorage.swift

https://github.com/user-attachments/assets/e8c68021-4e55-4a50-bd0d-34bfce76b685

iOS-4309 Counters | scroll to unread and scroll to bottom

---

Anytype/Sources/PresentationLayer/TextEditor/Set/Models/Builders/SetPermissionsBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetFullHeader.swift

Ios-4172 Primitives | Fix set permissions for type set

---

Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ChatActionPanel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Collection/ChatCollectionView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Collection/ChatCollectionViewCoordinator.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Section/MessageSectionItem.swift

https://github.com/user-attachments/assets/312ab59d-5291-401c-95b0-005d6938aa0e

iOS-4318 Chat | scroll to bottom without unread

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViewModel.swift
Anytype/Sources/ServiceLayer/UniversalLinks/UniversalLink.swift
Anytype/Sources/ServiceLayer/UniversalLinks/UniversalLinkParser.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/DeepLinks/Sources/DeepLinks/Array+Search.swift

https://github.com/user-attachments/assets/7467fe94-8916-4677-9049-26ee73dcffb2

iOS-4279 Add https links for copy action in objects

---

Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
Anytype/Sources/Models/ObjectPermissions/ObjectPermissions.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSettingBuilder.swift

IOS-4325 Primitives Fix type permissions

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/Model/ObjectSearchData.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/Model/SearchViewModelProtocol.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/SearchView/Cell/SearchCell.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/LinkToObject/LinkToObjectSearchData.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/SpaceSearch/SpaceSearchViewModel.swift

Made search api easier to extend & supported minimized presentation mode

IOS-4262 Simplified search api

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoViewModel.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/Model/RelationSearchData.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/Model/SearchViewModelProtocol.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/SearchView/Cell/SearchCell.swift
Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsModuleTarget.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsSearchViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationViewModel.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Models/Relations/Models/RelationLink.swift

https://github.com/user-attachments/assets/087f09ab-8bb2-4eb8-86e2-e1c697d6bc3f

Ios-4262 |  Implemented initial relation search design

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/RelationInfoData.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/Model/RelationSearchData.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/SearchView/SearchView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/LinkToObject/LinkToObjectSearchView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearch/ObjectSearchView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/SpaceSearch/SpaceSearchView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Common/CustomIcons/CustomIconGridView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/LegacyRelationsListSearch/RelationsSearchCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationViewModel.swift

https://github.com/user-attachments/assets/fbea12b0-6d51-4981-aa66-17bc948bcf53

Ios-4262 Supported new relations creation flow

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/FrameworkExtensions/SwiftUI/View+LegacyAdopt.swift
Anytype/Sources/PresentationLayer/Common/Extensions/RelationValuesProtocol+PageCellTitle.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/NewTypeCreation/NewTypeCreationView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/NewTypeCreation/NewTypeCreationViewModel.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Subscriptions/Set/SetSubscriptionDataBuilder.swift
Anytype/Sources/ServiceLayer/Object/TypesService/TypesService.swift
Anytype/Sources/ServiceLayer/Object/TypesService/TypesServiceProtocol.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Models/Details/Entities/CustomIcon/CustomIconData.swift
Modules/Services/Sources/Models/ObjectType.swift
Modules/Services/Sources/Models/SubscriptionData/BundledRelationKey+CommonKeys.swift

https://github.com/user-attachments/assets/785fd845-988f-4dcf-8491-ba4698af09f9

Ios-4332 Primitives | Add plural names creation support

---

Anytype/Sources/PresentationLayer/Common/Extensions/RelationValuesProtocol+PageCellTitle.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/Model/ObjectSearchData.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/SearchWithMetaModelBuilder.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Link/LinkWidgetViewModel.swift
Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift

https://github.com/user-attachments/assets/faeae18f-630d-4f70-a30b-ebfc6f8ff51c

IOS-4332 Primitives | Display plural names

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/LinkToObject/LinkToObjectSearchData.swift
Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/NewTypeCreation/NewTypeCreationView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/NewTypeCreation/NewTypeCreationViewModel.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/Legacy_ObjectTypeSearchViewModel/MultiselectObjectTypesSearchViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/ObjectsSearchViewModel/ObjectsSearchViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/Set/EditorSetModuleOutput.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetFullHeader.swift
Modules/Services/Sources/Models/Details/BundledDetails.swift

https://github.com/user-attachments/assets/b4300a44-a414-43e1-bf99-dad59a0faf98

Ios-4332 Primitives | provide plural name for types which for type set

---

Anytype/Sources/CoreLayer/MiddlewareHandler/MiddlewareHandlerConfigurator.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

This functionality provide glitches for fast scrolling on chat when we download a image

IOS-4347 Core | Pulse | Add toggle for URLSession handler

---

Anytype/Sources/Models/Extensions/ObjectType+Extensions.swift
Anytype/Sources/PresentationLayer/Common/Extensions/RelationValuesProtocol+PageCellTitle.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Object/ObjectRelationOption.swift
Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/NewTypeCreation/ObjectTypeInfoView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/NewTypeCreation/ObjectTypeInfoViewModel.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/Support/BlockLinkState.swift
Anytype/Sources/ServiceLayer/Object/TypeProvider/ObjectTypeProvider.swift
Modules/Services/Sources/Models/ObjectType.swift

Ios-4332 Primitives | Supported plurals in editor

---

Anytype/Sources/PresentationLayer/Flows/SpaceSettings/NewSpaceSettingsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/NewSpaceSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsModuleOutput.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift

Ios-4360 Add bin to space settings

---

Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ChatMessageHeaderView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ChatMessageUnreadView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Collection/ChatCollectionView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Collection/ChatCollectionViewCoordinator.swift

https://github.com/user-attachments/assets/95350402-8420-4e92-9199-0e4fdd0a5ad1

iOS-4324 Chat date header | make floating

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSettingBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetFullHeader.swift

https://github.com/user-attachments/assets/691d7646-ede0-41fb-b368-cfccea52fd73

IOS-4364 Primitives | Add description to object types

---

AnyTypeTests/Helpers/TypeFieldsMoveHandler/TypeFieldsMoveHandlerAdditionalTests.swift
AnyTypeTests/Helpers/TypeFieldsMoveHandler/TypeFieldsMoveHandlerMoveBetweenSectionTests.swift
AnyTypeTests/Helpers/TypeFieldsMoveHandler/TypeFieldsMoveHandlerMoveWithinSectionTests.swift
Anytype.xcodeproj/project.pbxproj
Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsInteractor.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/ObjectFieldsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsMoveHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationViewModel.swift
AnytypeTests/Helpers/TypeFieldsMoveHandler/TypeFieldsMoveHandlerGeneralTests.swift
AnytypeTests/Markdown/Mocks/MockRelationDetailsStorage.swift
AnytypeTests/Markdown/Mocks/MockRelationsService.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Services/Relations/RelationsService.swift
Modules/Services/Sources/Services/Relations/RelationsServiceProtocol.swift

No business logic have changed here.
Preparation for Type as Set updates.

Ios-4332 Primitives | Updated type relations API

---

Anytype/Sources/PresentationLayer/Common/UIKit/AnytypeUITextView/AnytypeUITextView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatInput.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatPasteboardHelper.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatTextView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatTextViewCoordinator.swift
Anytype/Sources/ServiceLayer/Block/File/FileActionsService.swift
Anytype/Sources/ServiceLayer/Block/File/FileActionsServiceProtocol.swift
Anytype/Sources/ServiceLayer/Block/Pastboard/Operations/PasteboardTask.swift
Anytype/Sources/ServiceLayer/Block/Pastboard/PasteboardHelper.swift

https://github.com/user-attachments/assets/1cc9746c-1733-4480-abe4-dbecfba88597

iOS-3914 Chat | Paste binary data

---

Anytype/Generated/Strings.swift
Anytype/Resources/Strings/en.lproj/Localizable.strings
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchViewModel.swift

iOS-4372 Move system widgets to top

---

Anytype/Sources/PresentationLayer/Migration/MigrationViewModel.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift
Modules/Loc/Sources/Loc/Resources/Strings/en.lproj/Localizable.strings
Modules/Services/Sources/Services/Migration/AccountMigrationError.swift

iOS-4382 Update notEnoughFreeSpace error copy

---

Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinatorView.swift
Anytype/Sources/ApplicationLayer/AutoWidgetAddedHandler/AutoWidgetAddedModifier.swift
Anytype/Sources/ApplicationLayer/AutoWidgetAddedHandler/AutoWidgetAddedModifierModel.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift
Modules/Loc/Sources/Loc/Resources/Strings/en.lproj/Localizable.strings

https://github.com/user-attachments/assets/ce507618-13ec-4385-8d24-8bd62d16d436

iOS-4334 Widget | Show toast when type widget is automatically added to sidebar

---

Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsInteractor.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsModuleTarget.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsSearchInteractor.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsSearchViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/ObjectFieldsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/Coordinator/SetRelationsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetRelationsViewModel.swift
Anytype/Sources/ServiceLayer/Extensions/RelationsServiceProtocolExtensions.swift
Modules/Services/Sources/Services/Relations/RelationsService.swift

https://github.com/user-attachments/assets/52347c5d-1359-4273-a6bc-215abed70679

Ios-4172 Primitives | Sync dataview and type relation lists

---

Anytype/Sources/Models/Extensions/ObjectType+Extensions.swift
Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsModuleTarget.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationViewModel.swift
Anytype/Sources/ServiceLayer/Extensions/RelationsServiceProtocolExtensions.swift

Fixed relation creation in editor
https://github.com/user-attachments/assets/9ae0220b-c270-4285-8727-5f2bafc5bcef

IOS-4371 Primitives | Fix relations not beeing created in editor

---

Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift

IOS-4332 Primitives | Fix plural name in widgets

---

Anytype/Sources/Models/Extensions/ObjectType+Extensions.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSettingsPrimitivesConflictManager.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
Anytype/Sources/ServiceLayer/Object/TypeProvider/ObjectTypeProvider.swift
Modules/Services/Sources/Models/Common/LayoutAlignment.swift
Modules/Services/Sources/Models/ObjectType.swift

Ios-4399 Primitives | Bug fixes

---

Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/AnytypeToggle.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift
Modules/AnytypeCore/AnytypeCore/Extensions/ProtobufExtensions.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift
Modules/Loc/Sources/Loc/Resources/Strings/en.lproj/Localizable.strings
Modules/Services/Sources/Models/Details/BundledDetails.swift

https://github.com/user-attachments/assets/1b22a46b-d81c-452c-8a00-fd67d3ee831f

iOS-4394 Settings | Setting to disable automated widgets creation logic

---

Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift

Ios-4441 spacing between wallpaper and bin

---

Anytype/Sources/PresentationLayer/Auth/Auth/AuthViewModel.swift
Anytype/Sources/PresentationLayer/Flows/GalleryInstallation/GalleryInstallationCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
Anytype/Sources/ServiceLayer/AppActions/AppAction.swift
Anytype/Sources/ServiceLayer/Object/Usecase/UsecaseService.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Services/Workspace/WorkspaceService.swift
Modules/Services/Sources/Services/Workspace/WorkspaceServiceModels.swift

https://github.com/user-attachments/assets/48bf7ea9-6b5d-421d-913d-cc2cb0d35431

iOS-4432 UseCase | Automatically open welcome object

---

Anytype/Sources/Models/Documents/Document/BaseDocument+Extensions.swift

https://github.com/user-attachments/assets/f92485f8-5b19-4fdd-ad82-9a22d66bf8f8

IOS-4386 Add object type featured relation movable

---

Anytype/Sources/Models/Relations/RelationsBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsMoveHandler.swift

https://github.com/user-attachments/assets/88520fe9-ace9-4e0c-9bab-7708d269b361

Ios-4439 Added ability to drop into empty hidden section

---

Anytype/Sources/Analytics/AnalyticsConstants.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorViewModel.swift

https://github.com/user-attachments/assets/22ec787c-d182-4c7b-982d-5a6bc4773b51

IOS-4467 Supported object type change from relations menu

---

Anytype/Sources/PresentationLayer/Common/UIKit/BottomSheets/TextStyleView/StyleView.swift

IOS-4483 Fix disappeared assets for markup menu

---

Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/NewTypeCreation/ObjectTypeInfoView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/NewTypeCreation/ObjectTypeInfoViewModel.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

https://github.com/user-attachments/assets/38b50772-043e-447f-b746-31d9770d91f6

IOS-4497 Primitives | Support restrictions for type name preview

---

Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Collection/ChatCollectionViewContainer.swift

May not fix all bugs. Will test.

iOS-3940 Chat | keyboard | fix by easy way

---

Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/FirebaseConfigurator.swift
Anytype/Sources/ApplicationLayer/AppDelegate.swift
Anytype/Sources/PresentationLayer/Flows/ChatCoordinator/ChatCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/ChatCoordinator/ChatCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/PushNotificationsAlert/PushNotificationsAlertView.swift
Anytype/Sources/PresentationLayer/PushNotificationsAlert/PushNotificationsAlertViewModel.swift
Anytype/Sources/ServiceLayer/PushNotifications/PushNotificationsAlertHandler/PushNotificationsAlertHandler.swift
Anytype/Sources/ServiceLayer/PushNotifications/PushNotificationsPermissionService.swift/PushNotificationsPermissionService.swift
Anytype/Sources/ServiceLayer/PushNotifications/PushNotificationsRegistrationService/PushNotificationsRegistrationService.swift
Anytype/Sources/ServiceLayer/ServicesDI.swift

https://github.com/user-attachments/assets/4a19b9d3-e2b2-40bf-8a76-08bbd9ba22d8

iOS-4500 Impl push notifications custom alert logic

---

Anytype/Sources/Models/Documents/Document/BaseDocument.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchInteractor.swift
Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchViewModel.swift

https://github.com/user-attachments/assets/e3d98db1-f10a-4b11-a8c5-e67d52b775ac

IOS-4401 System Widgets | Filter to add once

---

Anytype/Sources/PresentationLayer/Flows/SpaceLoadingContainer/SpaceLoadingContainerView.swift

- Temporary fix for private MPV

IOS-4504 Space Loading indicator | remove hidden bottom panel

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/NewSpaceHubView.swift
Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x32/add_filled.imageset/Contents.json
Modules/Loc/Sources/Loc/Generated/Strings.swift

https://github.com/user-attachments/assets/8603cd71-310c-4ed9-99b2-5bcbf1c7ff4f

Ios-4502 vault redesign | Add empty state for space hub

---

Anytype/Sources/ApplicationLayer/AppDelegate.swift
Anytype/Sources/PresentationLayer/Auth/Auth/AuthViewModel.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
Anytype/Sources/ServiceLayer/AppActions/AppAction.swift
AnytypeNotificationServiceExtension/NotificationService.swift
Modules/Services/Sources/Models/DecryptedPushKeys.swift

https://github.com/user-attachments/assets/1aa3642e-2342-4c6e-a47e-daf1000aa700

iOS-4542 Open exact chat by tap on push

---

Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessagesPreviewsStorage.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/Models/ChatMessagePreview.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Helpers/SpaceHubSpacesStorage.swift

IOS-4544 Chat preview counters | add chat Id

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/MentionBadge.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessagesPreviewsStorage.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/AllObjects/AllObjectsWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Bin/BinWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/BinLink/BinLinkWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/LinkWidgetDefaultHeader.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/LinkWidgetViewContainer.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetContainerView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpaceChat/SpaceChatWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpaceChat/SpaceChatWidgetViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Helpers/SpaceHubSpacesStorage.swift

iOS-4522 Chat widget | support counters

---

Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessagesPreviewsStorage.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/Models/ChatMessagePreview.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Helpers/ParticipantSpaceViewDataWithPreview.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Helpers/SpaceHubSpacesStorage.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Subviews/NewSpaceCardLabel.swift
Modules/Services/Sources/Models/ChatModels.swift

IOS-4516 Space hub | Add simple messaging preview

---

Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessagesPreviewsStorage.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/Models/ChatMessagePreview.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Helpers/ParticipantSpaceViewDataWithPreview.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Helpers/SpaceHubSpacesStorage.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Subviews/NewSpaceCardLabel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Subviews/SpaceCardLabel.swift

Ios-4516 Space hub | Substantially cleaned up interfaces + dummy attachments preview

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/NewSpaceHubView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Subviews/NewSpaceCardLabel.swift

https://github.com/user-attachments/assets/1334d6eb-bf70-469e-af59-35f051650b45

Ios-4502 vault redesign | Design review

---

Anytype/Sources/Helpers/Formatters/HistoryDateFormatter.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessagesPreviewsStorage.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/Models/ChatMessagePreview.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Subviews/NewSpaceCardLabel.swift
Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift
Modules/Services/Sources/Models/ChatModels.swift
Modules/Services/Sources/Services/ParticipantService/ParticipantService.swift

Ios-4516 Message preview | Author and date preview

---

Anytype/Sources/PresentationLayer/Modules/Chat/Services/Models/ChatMessagePreview.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Subviews/NewSpaceCard.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Subviews/NewSpaceCardLabel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Subviews/SpaceCardLabel.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Models/Details/ObjectDetails.swift

Ios-4516 Message preview | Attachements preview

---

Anytype/Sources/PresentationLayer/Modules/Chat/Services/Models/AttachmentsTextInfoBuilder.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/Models/ChatMessagePreview.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/Local/ChatInputLocalBinaryFileView.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/Actions/SlashActionMedia.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

Ios-4516 Message preview | Implemented comprehensive attachment naming

---

Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessagesPreviewsStorage.swift

The problem was that previews were stored by spaceId bases, and when you have several chats in one space, we stored just the last preview. Now I store previews by pair space and chat.

IOS-4590 Store preview per space AND chat basis

---

Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipStatusExtension.swift
Anytype/Sources/PresentationLayer/Modules/Membership/Models/Mocks/MembershipStatus+Mocks.swift
Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/OwnershipView/MembershipOwnerInfoSheetView.swift
Modules/Services/Sources/Services/Membership/MembershipModelBuilder.swift
Modules/Services/Sources/Services/Membership/Model/MembershipStatus.swift

IOS-4600 Membership | Supported forever availability dates for all tiers

---

Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/OwnershipView/MembershipOwnerInfoSheetView.swift
Anytype/Sources/ServiceLayer/MembershipTierInfoProvider/MembershipMetadataProvider.swift
Anytype/Sources/ServiceLayer/MembershipTierInfoProvider/MembershipTierOwningState.swift

IOS-4593 Membership | Remove hardcode for free tier email submission

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/SearchView/SearchView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearch/ObjectSearchView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationViewModel.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

https://github.com/user-attachments/assets/2514d148-0e21-4e2f-bd1b-d86ae81ccf57

IOS-4514 Support new property creation from empty state

---

Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessagesStorage.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatUpdate.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Collection/ChatCollectionViewCoordinator.swift

Look at "unread button"
OLD
https://github.com/user-attachments/assets/e714f22b-271f-4b1e-96d2-432f809cc5c4
NEW
https://github.com/user-attachments/assets/0c4c8ca1-ffab-4b12-91bc-93e5c91a0c41

IOS-4605 Chat | Improve open chat and mark unread

---

Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

I think it can lead to freezing app issues

iOS-4622 Disable doNotWaitCompletionInAnytypePreview toggle

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/TaskWithMemoryScope.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/NewSpaceHubView.swift

https://github.com/user-attachments/assets/ce3f461d-764d-4477-b905-56844857abec

IOS-4623 Space Hub | Update task lifecycle

---

Anytype/Sources/Models/Relations/RelationsBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/Model/TypePropertiesRowBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/TypePropertiesView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/TypePropertiesViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetRelationsViewModel.swift
Anytype/Sources/ServiceLayer/Extensions/RelationsServiceProtocolExtensions.swift

Ios-4421 Primitives | Add an ability to remove all properties from type

---

Anytype/Sources/Models/Relations/RelationDetails+Extensions.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetPropertiesView.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetPropertiesViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetViewSettingsProperty.swift

https://github.com/user-attachments/assets/be583b78-160f-4785-933d-df8d4eb51bc0

Ios-4421 Primitives | Added ability to delete properties from type set

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/TemplatePreview/TemplatePreviewModel.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/Dataview/MockSetObjectCreationSettingsInteractor.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/Dataview/SetObjectCreationSettingsInteractor.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsViewModel.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/TemplateOptionAction.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/ObjectType/ObjectTypeTemplatePickerViewModel.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

https://github.com/user-attachments/assets/79f07445-f029-464a-9626-7ce91dbc1b42

IOS-4400 Primitives | Added set/unset as default capabilities to type templates

---

AnytypeNotificationServiceExtension/NotificationService.swift

iOS-4429 Grouped pushes by chatId

---

Anytype/Sources/PresentationLayer/Flows/TypeSearchForNewObjectFlow/TypeSearchForNewObjectCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/ShareOptions/ShareOptionsInteractor.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/CreateObject/CreateBookmarkViewModel.swift
Anytype/Sources/ServiceLayer/ChatActionService/ChatActionService.swift
Modules/Services/Sources/Services/Bookmark/BookmarkService.swift
Modules/Services/Sources/Services/Bookmark/BookmarkServiceProtocol.swift

https://github.com/user-attachments/assets/c2447f83-b05c-4f29-a9b8-5518555ef5b5

IOS-4183 Primitives | Supported templates for bookmarks

---

Anytype/Sources/PresentationLayer/TextEditor/Set/Models/Builders/SetPermissionsBuilder.swift

https://github.com/user-attachments/assets/e6e7a571-7be8-4b13-84cb-6bb062b8df5a

IOS-4648 Primitives | Fix object creation for bookmarks

---

Anytype/Sources/Models/Documents/Document/BaseDocument.swift
Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
Anytype/Sources/Models/ObjectPermissions/ObjectPermissions.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSettingsPrimitivesConflictManager.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/Builders/SetPermissionsBuilder.swift

IOS-4650 Primitives | Fixed object creation logic for templates

---

Anytype.xcodeproj/project.pbxproj
AnytypeNotificationServiceExtension/NotificationService.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift
Modules/Services/Sources/Models/DecryptedPushContent.swift

iOS-4655 Add simple attachments handling in message (without plural for now)

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/Subviews/NewSpaceCardLabel.swift

IOS-4683 Fix empty preview messages

---

Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageFlash.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageView.swift
Modules/Assets/Sources/Assets/Generated/Assets.swift
Modules/Assets/Sources/Assets/Generated/Color+Assets.swift
Modules/Assets/Sources/Assets/Generated/Color+Info.swift
Modules/Assets/Sources/Assets/Generated/UIColor+Assets.swift
Modules/Assets/Sources/Assets/Resources/SystemColors.xcassets/DesignSystem/Background/Chat/bubbleFlash.colorset/Contents.json

https://github.com/user-attachments/assets/f1e4b1e4-3191-45fc-91f1-46c719a7a83b

iOS-4499 Chat Message | highlight for reply

---

.claude/settings.json
.mcp.json
CLAUDE.md

- Added Linear MCP server configuration and permissions
- Updated CLAUDE.md with Linear issue workflow guidelines
- Reorganized Claude settings to separate safe/read-only from write permissions

IOS-4743 Setup Linear MCP server integration

---

.claude/settings.json
.mcp.json
Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics.swift
Anytype/Sources/Analytics/AnytypeAnalytics/MembershipTier+Analytics.swift
CLAUDE.md

- Added complete enum mapping for all MembershipTier analytics values
- Added tierId to user properties

IOS-4760 Add complete MembershipTier analytics enum mapping

---

Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Base/BlockViewModelProtocol.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageController.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/EditorItem.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Utils/EditorMainItemModelsHolder.swift

https://github.com/user-attachments/assets/cd5b75d1-8103-4bbe-ae4a-091d21763115

IOS-4790 Support complex reconfigure method

---

Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Home/HomeView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/OldSpaceHubView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubOutput.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Subviews/OldSpaceCard.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/Subviews/OldSpaceCardLabel.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

https://github.com/user-attachments/assets/8a4737f9-924f-4286-94dd-62035cd2754f

Ios-4814 New home | Prototype for initial UX testing

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Segment/SegmentLine.swift

- Fix visual alignment of storage segments by ensuring proper proportions while maintaining minimum visibility

IOS-4779 Fix storage segment proportional layout

---

CLAUDE.md

- Added comprehensive Feature Flags system documentation
- Added Icon system documentation with naming conventions
- Enhanced Localization section with hierarchical naming and large file handling tips

IOS-4784 Update CLAUDE.md with Feature Flags and Icon System documentation

---

Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessagesStorage.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/LinkObject/Common/MessageImageView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/LinkObject/Common/MessageUploadingStatus.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageAttachmentDetails.swift
Modules/Services/Sources/Models/Aliases.swift
Modules/Services/Sources/Models/Details/BundledPropertyValueProvider+CustomProperties.swift

https://github.com/user-attachments/assets/b4afee58-2164-41cc-b5b8-37d021ccd8ee

iOS-4837 Chat | Image uploading | support status

---

Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/LinkObject/Common/MessageUploadingStatus.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/LinkObject/Common/MessageVideoView.swift

https://github.com/user-attachments/assets/d2dbc490-28f6-4cf5-8d37-ce7f520fd42d

iOS-4838 Chat | Video uploading | support status 

---

CLAUDE.md

- Restructured sections with logical flow and emoji navigation for better usability
- Consolidated scattered localization guidance into streamlined workflow
- Unified commands into Quick Start section and removed duplication
- Condensed from 400+ lines to 250 while preserving all essential information

IOS-4845 Refactor and organize CLAUDE.md documentation

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/Modifiers/ObjectIconCornerRadiusModifier.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/ChatInputObjectView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/LinkObject/Common/MessageCommonObjectView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/LinkObject/Common/MessageFileUploadingStatus.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/LinkObject/Common/MessageImageView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/LinkObject/Common/MessageMediaUploadingStatus.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/LinkObject/Common/MessageVideoView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Attachments/MessageAttachmentView.swift

https://github.com/user-attachments/assets/38f7088b-4378-499b-a6e7-752118cd26e5

iOS-4838 Chat | File uploading | support status 

---

CLAUDE.md

- Added explicit instructions to never include AI signatures in commits or pull requests
- Emphasized keeping commits and PRs professional without AI attribution

IOS-4845 Update CLAUDE.md to prohibit AI signatures

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

- Add search bar to spaces list with real-time filtering by space name
- Implement proper empty states for different scenarios (no spaces vs no search results)  
https://github.com/user-attachments/assets/96578325-5997-4522-b878-22f3d72a8a7d

IOS-4819 Add spaces search functionality

---

Anytype/Sources/Models/Documents/Document/BaseDocument+Extensions.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorCollectionFlowLayout+LayoutDetails.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorCollectionFlowLayout.swift

IOS-4855 [EDITOR] Moved layout static func logic to separate file

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/FlowLayout/EditorCollectionFlowLayout.swift

Ios-4855 Editor | FIX of indentation issue

---

Anytype/Sources/DesignSystem/COLOR_SYSTEM.md
Anytype/Sources/PresentationLayer/Common/DESIGN_SYSTEM_MAPPING.md

- Created comprehensive COLOR_SYSTEM.md documentation explaining asset-based color workflow
- Documents step-by-step process for renaming colors using .xcassets and code generation

IOS-4877 Document color system workflow

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/EmbedContentView/EmbedContentDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Embed/BlockLatex+Extentions.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Embed/EmbedBlockViewModel.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Services/Sources/Models/Block/BlockConverters/BlocksModelsConverter.swift

Also add toggle
https://github.com/user-attachments/assets/e062c9d5-c81c-486c-aee0-33c97473028f

iOS-4786 Embed blocks | Part 4 (final) | Extract and handling url where possible (will be discussed)

---

Anytype/Sources/Models/ObjectPermissions/ObjectPermissions.swift
Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Settings/PublishToWeb/PublishToWebView.swift
Anytype/Sources/PresentationLayer/Settings/PublishToWeb/PublishToWebViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSetting.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsViewModel.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

Add a simple publishing screen
- Fix publishing permissions to check archive status
https://github.com/user-attachments/assets/9ed27153-03a9-442e-a6ef-fdaf731e79b0

IOS-4815 Add publishing screen and improve permissions

---

Anytype/Sources/PresentationLayer/Settings/PublishToWeb/PublishToWebInternalView.swift
Anytype/Sources/PresentationLayer/Settings/PublishToWeb/PublishToWebInternalViewModel.swift
Anytype/Sources/PresentationLayer/Settings/PublishToWeb/PublishToWebView.swift
Anytype/Sources/PresentationLayer/Settings/PublishToWeb/PublishToWebViewModel.swift
Modules/Services/Sources/Services/Publishing/Models/PublishingModels.swift
Modules/Services/Sources/Services/Publishing/PublishingService.swift

https://github.com/user-attachments/assets/804b9c39-579f-4808-a84a-08bf7a93279c
https://github.com/user-attachments/assets/55032513-72b8-4497-8fe1-884e4165a8a6

IOS-4815 Use wrapper view for publishing to handle data load

---

Anytype/Sources/PresentationLayer/Settings/PublishToWeb/PublishToWebInternalView.swift
Anytype/Sources/PresentationLayer/Settings/PublishToWeb/PublishToWebInternalViewModel.swift
Modules/Services/Sources/Services/Publishing/PublishingService.swift

https://github.com/user-attachments/assets/da9e0625-8d4e-4013-bf11-f987b7b4ddf3

IOS-4815 Supported publishing actions

---

Anytype/Sources/PresentationLayer/Modules/PublishToWeb/PublishToWebViewModel.swift
Anytype/Sources/PresentationLayer/Modules/PublishToWeb/View/PublishingPreview.swift
Anytype/Sources/PresentationLayer/Modules/PublishToWeb/View/PublishingPreviewBuilder.swift

https://github.com/user-attachments/assets/75f10740-be8b-4db3-8cc3-caf483e17022

IOS-4908 Implement publishing screen preview 

---

Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatInput.swift

https://github.com/user-attachments/assets/126d08e6-f633-4731-83ff-506c3fb3817a

iOS-4862 Chat | send button loading state

---

Anytype/Sources/PresentationLayer/Auth/Auth/AuthViewModel.swift
Anytype/Sources/PresentationLayer/Auth/JoinFlow/SoulView/SoulView.swift
Anytype/Sources/PresentationLayer/Auth/JoinFlow/SoulView/SoulViewModel.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

https://github.com/user-attachments/assets/5e8f8abd-2969-4de0-ab43-7cb5ad00081d

iOS-4791 Support auto-generated Identity Name

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/TemplatePreview/TemplatePreview.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/Dataview/MockSetObjectCreationSettingsInteractor.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageController.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewInput.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Utils/EditorNavigationBarHelper/EditorNavigationBarHelper.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Utils/EditorNavigationBarHelper/EditorNavigationBarView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Empty/ObjectHeaderEmptyConfiguration.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Empty/ObjectHeaderEmptyContentView.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/HeaderBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeader+Mutation.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeader.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeaderViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Filled/Subviews/HeaderViewSizeConfiguration.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/NavigationBar/SyncStatus/EditorBarItemState.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/NavigationBar/SyncStatus/EditorSyncStatusItem.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/NavigationBar/SyncStatus/EditorWebBannerItem.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetFullHeader.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

https://github.com/user-attachments/assets/bb774942-cb9f-4864-a9b1-3d85586d1099

IOS-4898 Editor x Publishing | Web publishing state banner in editor

---

Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageController.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModelProtocol.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/NavigationBar/SyncStatus/EditorWebBannerItem.swift
Modules/DesignKit/Sources/DesignKit/Fonts/Config/UIKitFont.swift

https://github.com/user-attachments/assets/0dc69b94-a11b-408e-9782-cafd1aa29e1a

Ios 4898 Editor x Publishing | Supported publishing banner tap

---

Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/NotificationsCore/Sources/NotificationsCore/Center/NotificationsCenterService.swift

Maybe will be changed from the onAppear()

iOS-4956 Remove notifications on chat appear (under the toggle)

---

Anytype/Sources/PresentationLayer/Modules/PublishToWeb/PublishToWebInternalView.swift
Anytype/Sources/PresentationLayer/Modules/PublishToWeb/PublishToWebInternalViewModel.swift
Anytype/Sources/PresentationLayer/Modules/PublishToWeb/View/PublishingPreview.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsView.swift

IOS-4908 Web publishing | Design review

---

Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceTypePicker/SpaceTypePickerView.swift

IOS-5002 Show qr code picker

---

Anytype/Sources/Models/Extensions/Participant+Extensions.swift
Anytype/Sources/PresentationLayer/Modules/NewSpaceShare/NewSpaceShareViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceShareParticipantView.swift
Anytype/Sources/PresentationLayer/Modules/SpceMembers/SpaceMembersViewModel.swift

https://github.com/user-attachments/assets/6bb5d97d-166b-4ef1-94fc-0049b6e3cc08

Ios-4993 new design of participant row

---

Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ConversationEmptyStateView/ConversationEmptyStateView.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

IOS-4975 Updated chat empty state

---

Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceShareParticipantView.swift

IOS-5008 Add badge for pending participants

---

Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/MediaFileScreenData.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/ScreenData+Details.swift
Anytype/Sources/PresentationLayer/TextEditor/Assembly/ScreenData.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift

https://github.com/user-attachments/assets/56acffe6-2063-413f-9506-5132ff7f3f1f

iOS-4976 Fullscreen media carousel for widgets

---

Anytype/Sources/PresentationLayer/Modules/PublishToWeb/PublishToWebInternalViewModel.swift

https://github.com/user-attachments/assets/638db344-4d34-420d-9d5f-a58ebd3133d9

IOS-5017 Url encode publishing uri

---

Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionViewController/MentionsViewController.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Search/EditorSearchCell.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Search/EditorSearchCellData.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Builders/FilterModels/SlashMenuComparator.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Builders/FilterModels/SlashMenuItemFilterMatch.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Builders/SlashMenuCellDataBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/Actions/SlashActionMedia.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/Actions/SlashActionSingle.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/Actions/SlashActionStyle.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashAction.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashMenuItemDisplayData.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashMenuItemType.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/TableView/SlashMenuContentConfigurationFactory.swift
Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/TableView/SlashMenuViewController+TableView.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

Ios-4889 Updated visual representation of slash menu cells

---

Anytype/Sources/PresentationLayer/Modules/AllObjects/Models/ObjectTypeSection.swift

https://github.com/user-attachments/assets/67e2fab0-416c-4d7e-9d8f-c5516e4f9fb1

IOS-5010 Display types in lists section of search

---

Anytype/Sources/PresentationLayer/Modules/SpaceJoin/SpaceJoinViewModel.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

https://github.com/user-attachments/assets/63a216e9-7ba5-4e05-8804-72cdd56847e8

IOS-4699 Added toast for  successful join without approval

---

Anytype/Sources/PresentationLayer/Modules/SharingExtension/SharingExtensionView.swift
Anytype/Sources/PresentationLayer/Modules/SharingExtension/SharingExtensionViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SharingExtensionShareTo/SharingExtensionShareToView.swift
Anytype/Sources/PresentationLayer/Modules/SharingExtensionShareTo/SharingExtensionShareToViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SharingExtensionShareTo/Subviews/SharingExtensionsChatRow.swift
Anytype/Sources/ServiceLayer/SharingExtensionActionService/SharingExtensionActionService.swift
Modules/AnytypeCore/AnytypeCore/Extensions/Array+Extensions.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

https://github.com/user-attachments/assets/35dd6c8d-decc-455d-8218-a2320909462a

iOS-4922 Sharing Extension | Create chat message

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/ImagePickerView/ImagePickerView.swift
Anytype/Sources/PresentationLayer/Flows/ChatCoordinator/ChatCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Flows/ChatCoordinator/Models/FilesPickerData.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Input/ChatInput.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelView.swift
Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelViewModel.swift
Anytype/Sources/ServiceLayer/Auth/LoginStateService.swift
Anytype/Sources/ServiceLayer/ServicesDI.swift
Anytype/Sources/ServiceLayer/SpaceFileUploadService/SpaceFileUploadService.swift
Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Modules/Loc/Sources/Loc/Generated/Strings.swift

https://github.com/user-attachments/assets/ec404234-0fdf-4baf-a6ef-983ca91f8960

iOS-4820 Direct files and media upload to space (without indicator)

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/Alerts/AlertView.swift

iOS-5064 New auth | Update custom alert view style

---

Anytype/Sources/PresentationLayer/Auth/JoinFlow/EmailCollectionView/EmailCollectionView.swift
Anytype/Sources/PresentationLayer/Auth/JoinFlow/EmailCollectionView/EmailCollectionViewModel.swift
Anytype/Sources/PresentationLayer/Auth/JoinFlow/Models/JoinFlowStepOutput.swift
Anytype/Sources/PresentationLayer/AuthNew/AuthCoordinatorView.swift
Anytype/Sources/PresentationLayer/AuthNew/AuthCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/AuthNew/Join/JoinCoordinatorView.swift
Anytype/Sources/PresentationLayer/AuthNew/Join/JoinCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/AuthNew/Join/JoinView/JoinBaseOutput.swift
Anytype/Sources/PresentationLayer/AuthNew/Join/JoinView/JoinStep.swift
Anytype/Sources/PresentationLayer/AuthNew/Join/JoinView/JoinView.swift
Anytype/Sources/PresentationLayer/AuthNew/Join/JoinView/JoinViewModel.swift
Anytype/Sources/PresentationLayer/AuthNew/PrimaryAuthView/PrimaryAuthViewModel.swift

Do not update email collection screen yet
https://github.com/user-attachments/assets/c001c602-4d30-4fd5-926b-b48034fcac9f

iOS-5066 New auth | Add new join flow (based on prev navigation)

---

Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsModuleOutput.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsView.swift
Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift

https://github.com/user-attachments/assets/7c37d006-004f-4f77-b8cd-85b06076bd81

IOS-4947 Update invite link state upon closing members screen

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift

https://github.com/user-attachments/assets/43e8bd44-47c9-4ab1-bc3b-d1d3c65c51c4

IOS-5079 Fixed empty search state

---

Anytype/Sources/PresentationLayer/AuthNew/Join/JoinView/JoinViewModel.swift

https://github.com/user-attachments/assets/9ff96d32-83d1-4785-86b3-172fd377dd3f

iOS-5087 New auth | Skip email step if needed (for local only)

---

Anytype.xcodeproj/project.pbxproj
Anytype/Resources/AssetConstants.swift
Anytype/Sources/ApplicationLayer/Launch/LaunchCircle.swift
Anytype/Sources/PresentationLayer/AuthNew/AuthCoordinatorView.swift
Anytype/Sources/PresentationLayer/AuthNew/Circle/AuthCircle.swift
Anytype/Sources/PresentationLayer/AuthNew/Circle/AuthCircleEnv.swift
Anytype/Sources/PresentationLayer/AuthNew/Circle/AuthOverlayCircle.swift
Anytype/Sources/PresentationLayer/AuthNew/PrimaryAuthView/PrimaryAuthView.swift

https://github.com/user-attachments/assets/2a344f9e-9638-4a1f-919c-239a9f990ecf

IOS-5058 Auth | Add circle with animation

---

.github/workflows/update_middleware.yaml

- Migrate to any-association user
- Github user make a approve (like crowdin PRs)

iOS-5108 Update middleware with auto approve

---

Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/Block/SimpleTableCellsBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/Block/TextBlock/SimpleTablesTextBlockActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockActionHandler.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Common/LinkToSearchHandling.swift

Reused logic from editor
https://github.com/user-attachments/assets/464f5783-5163-45ef-9698-506c67c51843

Ios-2858 Supported links in simple tables 🤪

---

Anytype/Sources/Analytics/Converters/LayoutAlignmentExtension.swift
Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/TemplatePreview/TemplatePreview.swift
Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/HeaderBuilder.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetFullHeader.swift
Modules/Services/Sources/Models/Block/BlockRestrictions/TitleBlockRestrictions.swift
Modules/Services/Sources/Models/SubscriptionData/BundledPropertyKey+CommonKeys.swift

https://github.com/user-attachments/assets/22ca3912-d362-4aef-8fc5-00384a869292

Ios-4828 Primitives | Use layout align for title and icon derived from type

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubTip/SpaceCreationTip.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/SpaceShareParticipantView.swift
Modules/DesignKit/Sources/DesignKit/Components/AttentionDot/AttentionDotView.swift

https://github.com/user-attachments/assets/7109c12d-0330-46fb-a721-0762fc278ab4

Ios 4913 Space creation tip

---

Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift
Anytype/Sources/PresentationLayer/Modules/SpacesManager/SpacesManagerView.swift
Anytype/Sources/PresentationLayer/Modules/SpacesManager/SpacesManagerViewModel.swift

https://github.com/user-attachments/assets/a9a6a684-e580-4427-beaf-c17b19ee5550

Ios 3874 updated empty state for spaces menu

---

Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsDI.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/ObjectType/ObjectTypeWidgetInfo.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/ObjectType/ObjectTypeWidgetRowType.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/ObjectType/ObjectTypeWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/ObjectType/ObjectTypeWidgetViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SetCommon/SetObjectWidgetOrderHelper.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocument.swift
Modules/Services/Sources/Models/Extensions/DetailsLayoutExtension.swift

https://github.com/user-attachments/assets/187b80f4-a568-4021-a946-5cd04d6f6feb

IOS-5129 Object Type widget | Show data

---

Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/HomeWidgetsGroupView.swift

IOS-5132 Home Widgets | Show groups

---

Anytype/Sources/PresentationLayer/Flows/HomeWidgetsCoordinator/HomeWidgetsCoordinatorView.swift
Anytype/Sources/PresentationLayer/Flows/HomeWidgetsCoordinator/HomeWidgetsCoordinatorViewModel.swift
Anytype/Sources/PresentationLayer/Modules/CreateObjectType/CreateObjectTypeView.swift
Anytype/Sources/PresentationLayer/Modules/CreateObjectType/CreateObjectTypeViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsModuleOutput.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift

https://github.com/user-attachments/assets/8c2c0488-6613-4324-ae63-9a4fcd6bbe5a

iOS-5133 Home | create object type by plus

---

Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/ObjectType/ObjectTypeWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/ObjectType/ObjectTypeWidgetViewModel.swift
Modules/Services/Sources/Models/Extensions/DetailsLayoutExtension.swift

https://github.com/user-attachments/assets/0ea61c3f-356a-4db4-840b-8e0398a1df20

IOS-5146 Create object in type widget

---

Anytype/Sources/Models/Extensions/ObjectType+Extensions.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/DragAndDrop/DragAndDropVerticalDelegate.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/ObjectType/ObjectTypeWidgetView.swift
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/ObjectType/ObjectTypeWidgetViewModel.swift
Anytype/Sources/ServiceLayer/Object/TypeProvider/ObjectTypeProvider.swift
Modules/Services/Sources/Models/ObjectType.swift
Modules/Services/Sources/Services/ObjectType/ObjectTypeService.swift
Modules/Services/Sources/ServicesDI.swift

https://github.com/user-attachments/assets/ed9b4f13-5cb8-4a8e-9180-d68e9249252b

iOS-5142 Object type widgets | dnd

---

Anytype/Sources/PresentationLayer/Common/SwiftUI/DashboardWallpaper.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Common/ImageCharIconView.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/IconColorStorage.swift
Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/SpaceIconView.swift
Anytype/Sources/PresentationLayer/Debug/Examples/GradientIconsExamples.swift
Anytype/Sources/ServiceLayer/IconColorService/IconColorService.swift

IOS-5162 Supported colored space icon

---

.github/workflows/branch_build.yaml
.github/workflows/dev_build.yaml
Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/BinLink/BinLinkWidgetView.swift

IOS-5176 CI | Remove downloadPlatform (it was added for beta)

---

Modules/DesignKit/Sources/DesignKit/Toast/ToastManager.swift
Modules/DesignKit/Sources/DesignKit/Toast/ToastView.swift

- Updated toast corner radius from fixed 8pt to dynamically calculated half of toast height
- Changed corner curve style from `.circular` to `.continuous` for smoother appearance

IOS-5236 Update toast corner radius to half height
